use crate::{Object, Offset, Rect, SentinelValue, Size, TextDirection};

// The front end refused 12 member(s) in this library:
// NOT TRANSLATED: AlignmentGeometry: unsupported factory constructor: const factory AlignmentGeometry.xy(double x, double y) = Alignment;
// NOT TRANSLATED: AlignmentGeometry: unsupported factory constructor: const factory AlignmentGeometry.directional(double start, double y) = AlignmentDirectional;
// NOT TRANSLATED: AlignmentGeometry: unsupported top-level call `identical`: identical(a, b)
// NOT TRANSLATED: AlignmentGeometry: unsupported expression StringInterpolationImpl: '${Alignment._stringify(_x, _y)} + ${AlignmentDirectional._stringify(_start, 0.0)}'
// NOT TRANSLATED: AlignmentGeometry: unsupported default `sentinelValue` is not a literal: Object.hash(_x, _start, _y)
// NOT TRANSLATED: Alignment: unsupported top-level call `identical`: identical(a, b)
// NOT TRANSLATED: Alignment: unsupported expression SwitchExpressionImpl: switch ((x, y)) {(-1.0, -1.0) => 'Alignment.topLeft', (0.0, -1.0) => 'Alignment.topCenter', (1.0, -1.0) => 'Alignment.topRight', (-1.0, 0.0) => 'Alignment.centerLeft', (0.0, 0.0) => 'Alignment.center', (1.0, 0.0) => 'Alignment.centerRight', (-1.0, 1.0) => 'Alignment.bottomLeft', (0.0, 1.0) => 'Alignment.bottomCenter', (1.0, 1.0) => 'Alignment.bottomRight', _ => 'Alignment(${x.toStringAsFixed(1)}, ${y.toStringAsFixed(1)})'}
// NOT TRANSLATED: AlignmentDirectional: unsupported top-level call `identical`: identical(a, b)
// NOT TRANSLATED: AlignmentDirectional: unsupported expression StringInterpolationImpl: '$AlignmentDirectional'
// NOT TRANSLATED: AlignmentDirectional: unsupported expression SwitchExpressionImpl: switch ((start, y)) {(-1.0, -1.0) => 'AlignmentDirectional.topStart', (0.0, -1.0) => 'AlignmentDirectional.topCenter', (1.0, -1.0) => 'AlignmentDirectional.topEnd', (-1.0, 0.0) => 'AlignmentDirectional.centerStart', (0.0, 0.0) => 'AlignmentDirectional.center', (1.0, 0.0) => 'AlignmentDirectional.centerEnd', (-1.0, 1.0) => 'AlignmentDirectional.bottomStart', (0.0, 1.0) => 'AlignmentDirectional.bottomCenter', (1.0, 1.0) => 'AlignmentDirectional.bottomEnd', _ => 'AlignmentDirectional(${start.toStringAsFixed(1)}, ${y.toStringAsFixed(1)})'}
// NOT TRANSLATED: _MixedAlignment: unsupported expression StringInterpolationImpl: '$_MixedAlignment'
// NOT TRANSLATED: TextAlignVertical: unsupported expression StringInterpolationImpl: '${objectRuntimeType(this, 'TextAlignVertical')}(y: $y)'

// Generated by tools/dart2rust from upstream `AlignmentGeometry`
// (abstract -> trait).

/// Base class for [Alignment] that allows for text-direction aware
/// resolution.
///
/// A property or argument of this type accepts classes created either with
/// [Alignment] and its variants, or [AlignmentDirectional.new].
///
/// To convert an [AlignmentGeometry] object of indeterminate type into an
/// [Alignment] object, call the [resolve] method.

/// The body of `AlignmentGeometry.add`, reachable from an
/// override the way Dart's `super.add` is.
pub fn alignment_geometry_super_add<S: AlignmentGeometry + ?Sized>(
    this_: &S,
    other: &dyn AlignmentGeometry,
) -> Box<dyn AlignmentGeometry> {
    Box::new(_MixedAlignment::new(
        (this_._x() + other._x()),
        (this_._start() + other._start()),
        (this_._y() + other._y()),
    ))
}
// NOT TRANSLATED: alignment_geometry_super_op_eq
//   unsupported `is` in the value subset: `is` needs the class hierarchy, which this backend does not model yet

pub trait AlignmentGeometry {
    fn _x(&self) -> f32;

    fn _start(&self) -> f32;

    fn _y(&self) -> f32;

    /// Returns the negation of the given [AlignmentGeometry] object.
    ///
    /// This is the same as multiplying the object by -1.0.
    ///
    /// This operator returns an object of the same type as the operand.
    fn op_neg(&self) -> Box<dyn AlignmentGeometry>;

    /// Scales the [AlignmentGeometry] object in each dimension by the given factor.
    ///
    /// This operator returns an object of the same type as the operand.
    fn op_mul(&self, other: f32) -> Box<dyn AlignmentGeometry>;

    /// Divides the [AlignmentGeometry] object in each dimension by the given factor.
    ///
    /// This operator returns an object of the same type as the operand.
    fn op_div(&self, other: f32) -> Box<dyn AlignmentGeometry>;

    /// Integer divides the [AlignmentGeometry] object in each dimension by the given factor.
    ///
    /// This operator returns an object of the same type as the operand.
    fn int_div(&self, other: f32) -> Box<dyn AlignmentGeometry>;

    /// Computes the remainder in each dimension by the given factor.
    ///
    /// This operator returns an object of the same type as the operand.
    fn op_rem(&self, other: f32) -> Box<dyn AlignmentGeometry>;

    /// Convert this instance into an [Alignment], which uses literal
    /// coordinates (the `x` coordinate being explicitly a distance from the
    /// left).
    ///
    /// See also:
    ///
    /// * [Alignment], for which this is a no-op (returns itself).
    /// * [AlignmentDirectional], which flips the horizontal direction
    /// based on the `direction` argument.
    fn resolve(&self, direction: Option<TextDirection>) -> Alignment;

    /// Returns the sum of two [AlignmentGeometry] objects.
    ///
    /// If you know you are adding two [Alignment] or two [AlignmentDirectional]
    /// objects, consider using the `+` operator instead, which always returns an
    /// object of the same type as the operands, and is typed accordingly.
    ///
    /// If [add] is applied to two objects of the same type ([Alignment] or
    /// [AlignmentDirectional]), an object of that type will be returned (though
    /// this is not reflected in the type system). Otherwise, an object
    /// representing a combination of both is returned. That object can be turned
    /// into a concrete [Alignment] using [resolve].
    fn add(&self, other: &dyn AlignmentGeometry) -> Box<dyn AlignmentGeometry> {
        alignment_geometry_super_add(self, other)
    }

    fn op_eq(&self, other: Object) -> bool {
        todo!("AlignmentGeometry.== did not translate")
    }
}

// Generated by tools/dart2rust from upstream `Alignment`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// A point within a rectangle.
///
/// `Alignment(0.0, 0.0)` represents the center of the rectangle. The distance
/// from -1.0 to +1.0 is the distance from one side of the rectangle to the
/// other side of the rectangle. Therefore, 2.0 units horizontally (or
/// vertically) is equivalent to the width (or height) of the rectangle.
///
/// `Alignment(-1.0, -1.0)` represents the top left of the rectangle.
///
/// `Alignment(1.0, 1.0)` represents the bottom right of the rectangle.
///
/// `Alignment(0.0, 3.0)` represents a point that is horizontally centered with
/// respect to the rectangle and vertically below the bottom of the rectangle by
/// the height of the rectangle.
///
/// `Alignment(0.0, -0.5)` represents a point that is horizontally centered with
/// respect to the rectangle and vertically half way between the top edge and
/// the center.
///
/// `Alignment(x, y)` in a rectangle with height h and width w describes
/// the point (x * w/2 + w/2, y * h/2 + h/2) in the coordinate system of the
/// rectangle.
///
/// [Alignment] uses visual coordinates, which means increasing [x] moves the
/// point from left to right. To support layouts with a right-to-left
/// [TextDirection], consider using [AlignmentDirectional], in which the
/// direction the point moves when increasing the horizontal value depends on
/// the [TextDirection].
///
/// A variety of widgets use [Alignment] in their configuration, most
/// notably:
///
/// * [Align] positions a child according to an [Alignment].
///
/// See also:
///
/// * [AlignmentDirectional], which has a horizontal coordinate orientation
/// that depends on the [TextDirection].
/// * [AlignmentGeometry], which is an abstract type that is agnostic as to
/// whether the horizontal direction depends on the [TextDirection].
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Alignment {
    /// The distance fraction in the horizontal direction.
    ///
    /// A value of -1.0 corresponds to the leftmost edge. A value of 1.0
    /// corresponds to the rightmost edge. Values are not limited to that range;
    /// values less than -1.0 represent positions to the left of the left edge,
    /// and values greater than 1.0 represent positions to the right of the right
    /// edge.
    pub x: f32,
    /// The distance fraction in the vertical direction.
    ///
    /// A value of -1.0 corresponds to the topmost edge. A value of 1.0
    /// corresponds to the bottommost edge. Values are not limited to that range;
    /// values less than -1.0 represent positions above the top, and values
    /// greater than 1.0 represent positions below the bottom.
    pub y: f32,
}

impl Alignment {
    /// Creates an alignment.
    pub const fn new(x: f32, y: f32) -> Self {
        Self { x: x, y: y }
    }

    /// The top left corner.
    pub const TOP_LEFT: Alignment = Alignment::new((-1.0), (-1.0));
    /// The center point along the top edge.
    pub const TOP_CENTER: Alignment = Alignment::new(0.0, (-1.0));
    /// The top right corner.
    pub const TOP_RIGHT: Alignment = Alignment::new(1.0, (-1.0));
    /// The center point along the left edge.
    pub const CENTER_LEFT: Alignment = Alignment::new((-1.0), 0.0);
    /// The center point, both horizontally and vertically.
    pub const CENTER: Alignment = Alignment::new(0.0, 0.0);
    /// The center point along the right edge.
    pub const CENTER_RIGHT: Alignment = Alignment::new(1.0, 0.0);
    /// The bottom left corner.
    pub const BOTTOM_LEFT: Alignment = Alignment::new((-1.0), 1.0);
    /// The center point along the bottom edge.
    pub const BOTTOM_CENTER: Alignment = Alignment::new(0.0, 1.0);
    /// The bottom right corner.
    pub const BOTTOM_RIGHT: Alignment = Alignment::new(1.0, 1.0);

    fn _x(&self) -> f32 {
        self.x
    }

    fn _start(&self) -> f32 {
        0.0
    }

    fn _y(&self) -> f32 {
        self.y
    }

    // NOT TRANSLATED: Alignment.add
    //   unsupported `is` in the value subset: `is` needs the class hierarchy, which this backend does not model yet

    /// Returns the offset that is this fraction in the direction of the given offset.
    pub fn along_offset(&self, other: Offset) -> Offset {
        let center_x: f32 = (other.dx() / 2.0);
        let center_y: f32 = (other.dy() / 2.0);
        Offset::new(
            (center_x + (self.x * center_x)),
            (center_y + (self.y * center_y)),
        )
    }

    /// Returns the offset that is this fraction within the given size.
    pub fn along_size(&self, other: Size) -> Offset {
        let center_x: f32 = (other.width() / 2.0);
        let center_y: f32 = (other.height() / 2.0);
        Offset::new(
            (center_x + (self.x * center_x)),
            (center_y + (self.y * center_y)),
        )
    }

    /// Returns the point that is this fraction within the given rect.
    pub fn within_rect(&self, rect: Rect) -> Offset {
        let half_width: f32 = (rect.width() / 2.0);
        let half_height: f32 = (rect.height() / 2.0);
        Offset::new(
            ((rect.left + half_width) + (self.x * half_width)),
            ((rect.top + half_height) + (self.y * half_height)),
        )
    }

    /// Returns a rect of the given size, aligned within given rect as specified
    /// by this alignment.
    ///
    /// For example, a 100×100 size inscribed on a 200×200 rect using
    /// [Alignment.topLeft] would be the 100×100 rect at the top left of
    /// the 200×200 rect.
    pub fn inscribe(&self, size: Size, rect: Rect) -> Rect {
        let half_width_delta: f32 = ((rect.width() - size.width()) / 2.0);
        let half_height_delta: f32 = ((rect.height() - size.height()) / 2.0);
        Rect::from_l_t_w_h(
            ((rect.left + half_width_delta) + (self.x * half_width_delta)),
            ((rect.top + half_height_delta) + (self.y * half_height_delta)),
            size.width(),
            size.height(),
        )
    }

    pub fn resolve(&self, direction: Option<TextDirection>) -> Alignment {
        *self
    }

    // NOT TRANSLATED: Alignment.toString
    //   unsupported call to `Alignment._stringify`, which was not translated: Alignment._stringify(...)
}

/// Returns the difference between two [Alignment]s.
impl std::ops::Sub<Alignment> for Alignment {
    type Output = Alignment;

    fn sub(self, other: Alignment) -> Self::Output {
        Alignment::new((self.x - other.x), (self.y - other.y))
    }
}

/// Returns the sum of two [Alignment]s.
impl std::ops::Add<Alignment> for Alignment {
    type Output = Alignment;

    fn add(self, other: Alignment) -> Self::Output {
        Alignment::new((self.x + other.x), (self.y + other.y))
    }
}

/// Returns the negation of the given [Alignment].
impl std::ops::Neg for Alignment {
    type Output = Alignment;

    fn neg(self) -> Self::Output {
        Alignment::new((-self.x), (-self.y))
    }
}

/// Scales the [Alignment] in each dimension by the given factor.
impl std::ops::Mul<f32> for Alignment {
    type Output = Alignment;

    fn mul(self, other: f32) -> Self::Output {
        Alignment::new((self.x * other), (self.y * other))
    }
}

/// Divides the [Alignment] in each dimension by the given factor.
impl std::ops::Div<f32> for Alignment {
    type Output = Alignment;

    fn div(self, other: f32) -> Self::Output {
        Alignment::new((self.x / other), (self.y / other))
    }
}

impl Alignment {
    /// Integer divides the [Alignment] in each dimension by the given factor.
    pub fn int_div(&self, other: f32) -> Alignment {
        Alignment::new(((self.x / other).trunc()), ((self.y / other).trunc()))
    }
}

/// Computes the remainder in each dimension by the given factor.
impl std::ops::Rem<f32> for Alignment {
    type Output = Alignment;

    fn rem(self, other: f32) -> Self::Output {
        Alignment::new((self.x % other), (self.y % other))
    }
}

impl AlignmentGeometry for Alignment {
    fn _x(&self) -> f32 {
        Alignment::_x(self)
    }

    fn _start(&self) -> f32 {
        Alignment::_start(self)
    }

    fn _y(&self) -> f32 {
        Alignment::_y(self)
    }

    fn op_neg(&self) -> Box<dyn AlignmentGeometry> {
        Box::new(-*self)
    }

    fn op_mul(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self * other)
    }

    fn op_div(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self / other)
    }

    fn int_div(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(Alignment::int_div(self, other))
    }

    fn op_rem(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self % other)
    }

    fn resolve(&self, direction: Option<TextDirection>) -> Alignment {
        Alignment::resolve(self, direction)
    }

    fn add(&self, other: &dyn AlignmentGeometry) -> Box<dyn AlignmentGeometry> {
        Alignment::add(self, other)
    }
}

// Generated by tools/dart2rust from upstream `AlignmentDirectional`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// An offset that's expressed as a fraction of a [Size], but whose horizontal
/// component is dependent on the writing direction.
///
/// This can be used to indicate an offset from the left in [TextDirection.ltr]
/// text and an offset from the right in [TextDirection.rtl] text without having
/// to be aware of the current text direction.
///
/// See also:
///
/// * [Alignment], a variant that is defined in physical terms (i.e.
/// whose horizontal component does not depend on the text direction).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct AlignmentDirectional {
    /// The distance fraction in the horizontal direction.
    ///
    /// A value of -1.0 corresponds to the edge on the "start" side, which is the
    /// left side in [TextDirection.ltr] contexts and the right side in
    /// [TextDirection.rtl] contexts. A value of 1.0 corresponds to the opposite
    /// edge, the "end" side. Values are not limited to that range; values less
    /// than -1.0 represent positions beyond the start edge, and values greater than
    /// 1.0 represent positions beyond the end edge.
    ///
    /// This value is normalized into an [Alignment.x] value by the [resolve]
    /// method.
    pub start: f32,
    /// The distance fraction in the vertical direction.
    ///
    /// A value of -1.0 corresponds to the topmost edge. A value of 1.0
    /// corresponds to the bottommost edge. Values are not limited to that range;
    /// values less than -1.0 represent positions above the top, and values
    /// greater than 1.0 represent positions below the bottom.
    ///
    /// This value is passed through to [Alignment.y] unmodified by the
    /// [resolve] method.
    pub y: f32,
}

impl AlignmentDirectional {
    /// Creates a directional alignment.
    pub const fn new(start: f32, y: f32) -> Self {
        Self { start: start, y: y }
    }

    /// The top corner on the "start" side.
    pub const TOP_START: AlignmentDirectional = AlignmentDirectional::new((-1.0), (-1.0));
    /// The center point along the top edge.
    ///
    /// Consider using [Alignment.topCenter] instead, as it does not need
    /// to be [resolve]d to be used.
    pub const TOP_CENTER: AlignmentDirectional = AlignmentDirectional::new(0.0, (-1.0));
    /// The top corner on the "end" side.
    pub const TOP_END: AlignmentDirectional = AlignmentDirectional::new(1.0, (-1.0));
    /// The center point along the "start" edge.
    pub const CENTER_START: AlignmentDirectional = AlignmentDirectional::new((-1.0), 0.0);
    /// The center point, both horizontally and vertically.
    ///
    /// Consider using [Alignment.center] instead, as it does not need to
    /// be [resolve]d to be used.
    pub const CENTER: AlignmentDirectional = AlignmentDirectional::new(0.0, 0.0);
    /// The center point along the "end" edge.
    pub const CENTER_END: AlignmentDirectional = AlignmentDirectional::new(1.0, 0.0);
    /// The bottom corner on the "start" side.
    pub const BOTTOM_START: AlignmentDirectional = AlignmentDirectional::new((-1.0), 1.0);
    /// The center point along the bottom edge.
    ///
    /// Consider using [Alignment.bottomCenter] instead, as it does not
    /// need to be [resolve]d to be used.
    pub const BOTTOM_CENTER: AlignmentDirectional = AlignmentDirectional::new(0.0, 1.0);
    /// The bottom corner on the "end" side.
    pub const BOTTOM_END: AlignmentDirectional = AlignmentDirectional::new(1.0, 1.0);

    fn _x(&self) -> f32 {
        0.0
    }

    fn _start(&self) -> f32 {
        self.start
    }

    fn _y(&self) -> f32 {
        self.y
    }

    // NOT TRANSLATED: AlignmentDirectional.add
    //   unsupported `is` in the value subset: `is` needs the class hierarchy, which this backend does not model yet

    // NOT TRANSLATED: AlignmentDirectional.toString
    //   unsupported call to `AlignmentDirectional._stringify`, which was not translated: AlignmentDirectional._stringify(...)
}

/// Returns the difference between two [AlignmentDirectional]s.
impl std::ops::Sub<AlignmentDirectional> for AlignmentDirectional {
    type Output = AlignmentDirectional;

    fn sub(self, other: AlignmentDirectional) -> Self::Output {
        AlignmentDirectional::new((self.start - other.start), (self.y - other.y))
    }
}

/// Returns the sum of two [AlignmentDirectional]s.
impl std::ops::Add<AlignmentDirectional> for AlignmentDirectional {
    type Output = AlignmentDirectional;

    fn add(self, other: AlignmentDirectional) -> Self::Output {
        AlignmentDirectional::new((self.start + other.start), (self.y + other.y))
    }
}

/// Returns the negation of the given [AlignmentDirectional].
impl std::ops::Neg for AlignmentDirectional {
    type Output = AlignmentDirectional;

    fn neg(self) -> Self::Output {
        AlignmentDirectional::new((-self.start), (-self.y))
    }
}

/// Scales the [AlignmentDirectional] in each dimension by the given factor.
impl std::ops::Mul<f32> for AlignmentDirectional {
    type Output = AlignmentDirectional;

    fn mul(self, other: f32) -> Self::Output {
        AlignmentDirectional::new((self.start * other), (self.y * other))
    }
}

/// Divides the [AlignmentDirectional] in each dimension by the given factor.
impl std::ops::Div<f32> for AlignmentDirectional {
    type Output = AlignmentDirectional;

    fn div(self, other: f32) -> Self::Output {
        AlignmentDirectional::new((self.start / other), (self.y / other))
    }
}

impl AlignmentDirectional {
    /// Integer divides the [AlignmentDirectional] in each dimension by the given factor.
    pub fn int_div(&self, other: f32) -> AlignmentDirectional {
        AlignmentDirectional::new(((self.start / other).trunc()), ((self.y / other).trunc()))
    }
}

/// Computes the remainder in each dimension by the given factor.
impl std::ops::Rem<f32> for AlignmentDirectional {
    type Output = AlignmentDirectional;

    fn rem(self, other: f32) -> Self::Output {
        AlignmentDirectional::new((self.start % other), (self.y % other))
    }
}

impl AlignmentGeometry for AlignmentDirectional {
    fn _x(&self) -> f32 {
        AlignmentDirectional::_x(self)
    }

    fn _start(&self) -> f32 {
        AlignmentDirectional::_start(self)
    }

    fn _y(&self) -> f32 {
        AlignmentDirectional::_y(self)
    }

    fn op_neg(&self) -> Box<dyn AlignmentGeometry> {
        Box::new(-*self)
    }

    fn op_mul(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self * other)
    }

    fn op_div(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self / other)
    }

    fn int_div(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(AlignmentDirectional::int_div(self, other))
    }

    fn op_rem(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self % other)
    }

    fn resolve(&self, direction: Option<TextDirection>) -> Alignment {
        todo!("AlignmentDirectional does not translate resolve yet")
    }

    fn add(&self, other: &dyn AlignmentGeometry) -> Box<dyn AlignmentGeometry> {
        AlignmentDirectional::add(self, other)
    }
}

// Generated by tools/dart2rust from upstream `_MixedAlignment`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
struct _MixedAlignment {
    _x: f32,
    _start: f32,
    _y: f32,
}

impl _MixedAlignment {
    const fn new(_x: f32, _start: f32, _y: f32) -> Self {
        Self {
            _x: _x,
            _start: _start,
            _y: _y,
        }
    }
}

impl std::ops::Neg for _MixedAlignment {
    type Output = _MixedAlignment;

    fn neg(self) -> Self::Output {
        _MixedAlignment::new((-self._x), (-self._start), (-self._y))
    }
}

impl std::ops::Mul<f32> for _MixedAlignment {
    type Output = _MixedAlignment;

    fn mul(self, other: f32) -> Self::Output {
        _MixedAlignment::new((self._x * other), (self._start * other), (self._y * other))
    }
}

impl std::ops::Div<f32> for _MixedAlignment {
    type Output = _MixedAlignment;

    fn div(self, other: f32) -> Self::Output {
        _MixedAlignment::new((self._x / other), (self._start / other), (self._y / other))
    }
}

impl _MixedAlignment {
    pub fn int_div(&self, other: f32) -> _MixedAlignment {
        _MixedAlignment::new(
            ((self._x / other).trunc()),
            ((self._start / other).trunc()),
            ((self._y / other).trunc()),
        )
    }
}

impl std::ops::Rem<f32> for _MixedAlignment {
    type Output = _MixedAlignment;

    fn rem(self, other: f32) -> Self::Output {
        _MixedAlignment::new((self._x % other), (self._start % other), (self._y % other))
    }
}

impl AlignmentGeometry for _MixedAlignment {
    fn _x(&self) -> f32 {
        todo!("_MixedAlignment does not translate _x yet")
    }

    fn _start(&self) -> f32 {
        todo!("_MixedAlignment does not translate _start yet")
    }

    fn _y(&self) -> f32 {
        todo!("_MixedAlignment does not translate _y yet")
    }

    fn op_neg(&self) -> Box<dyn AlignmentGeometry> {
        Box::new(-*self)
    }

    fn op_mul(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self * other)
    }

    fn op_div(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self / other)
    }

    fn int_div(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(_MixedAlignment::int_div(self, other))
    }

    fn op_rem(&self, other: f32) -> Box<dyn AlignmentGeometry> {
        Box::new(*self % other)
    }

    fn resolve(&self, direction: Option<TextDirection>) -> Alignment {
        todo!("_MixedAlignment does not translate resolve yet")
    }
}

// Generated by tools/dart2rust from upstream `TextAlignVertical`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// The vertical alignment of text within an input box.
///
/// A single [y] value that can range from -1.0 to 1.0. -1.0 aligns to the top
/// of an input box so that the top of the first line of text fits within the
/// box and its padding. 0.0 aligns to the center of the box. 1.0 aligns so that
/// the bottom of the last line of text aligns with the bottom interior edge of
/// the input box.
///
/// See also:
///
/// * [TextField.textAlignVertical], which is passed on to the [InputDecorator].
/// * [CupertinoTextField.textAlignVertical], which behaves in the same way as
/// the parameter in TextField.
/// * [InputDecorator.textAlignVertical], which defines the alignment of
/// prefix, input, and suffix within an [InputDecorator].
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TextAlignVertical {
    /// A value ranging from -1.0 to 1.0 that defines the topmost and bottommost
    /// locations of the top and bottom of the input box.
    pub y: f32,
}

impl TextAlignVertical {
    /// Creates a TextAlignVertical from any y value between -1.0 and 1.0.
    pub const fn new(y: f32) -> Self {
        debug_assert!(((y >= (-1.0)) && (y <= 1.0)));
        Self { y: y }
    }

    /// Aligns a TextField's input Text with the topmost location within a
    /// TextField's input box.
    pub const TOP: TextAlignVertical = TextAlignVertical::new((-1.0));
    /// Aligns a TextField's input Text to the center of the TextField.
    pub const CENTER: TextAlignVertical = TextAlignVertical::new(0.0);
    /// Aligns a TextField's input Text with the bottommost location within a
    /// TextField.
    pub const BOTTOM: TextAlignVertical = TextAlignVertical::new(1.0);
}
