use crate::{Offset, Rect, Size, TextDirection};

// Generated by tools/dart2rust from upstream `Alignment`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// A point within a rectangle.
///
/// `Alignment(0.0, 0.0)` represents the center of the rectangle. The distance
/// from -1.0 to +1.0 is the distance from one side of the rectangle to the
/// other side of the rectangle. Therefore, 2.0 units horizontally (or
/// vertically) is equivalent to the width (or height) of the rectangle.
///
/// `Alignment(-1.0, -1.0)` represents the top left of the rectangle.
///
/// `Alignment(1.0, 1.0)` represents the bottom right of the rectangle.
///
/// `Alignment(0.0, 3.0)` represents a point that is horizontally centered with
/// respect to the rectangle and vertically below the bottom of the rectangle by
/// the height of the rectangle.
///
/// `Alignment(0.0, -0.5)` represents a point that is horizontally centered with
/// respect to the rectangle and vertically half way between the top edge and
/// the center.
///
/// `Alignment(x, y)` in a rectangle with height h and width w describes
/// the point (x * w/2 + w/2, y * h/2 + h/2) in the coordinate system of the
/// rectangle.
///
/// [Alignment] uses visual coordinates, which means increasing [x] moves the
/// point from left to right. To support layouts with a right-to-left
/// [TextDirection], consider using [AlignmentDirectional], in which the
/// direction the point moves when increasing the horizontal value depends on
/// the [TextDirection].
///
/// A variety of widgets use [Alignment] in their configuration, most
/// notably:
///
/// * [Align] positions a child according to an [Alignment].
///
/// See also:
///
/// * [AlignmentDirectional], which has a horizontal coordinate orientation
/// that depends on the [TextDirection].
/// * [AlignmentGeometry], which is an abstract type that is agnostic as to
/// whether the horizontal direction depends on the [TextDirection].
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Alignment {
    /// The distance fraction in the horizontal direction.
    ///
    /// A value of -1.0 corresponds to the leftmost edge. A value of 1.0
    /// corresponds to the rightmost edge. Values are not limited to that range;
    /// values less than -1.0 represent positions to the left of the left edge,
    /// and values greater than 1.0 represent positions to the right of the right
    /// edge.
    pub x: f32,
    /// The distance fraction in the vertical direction.
    ///
    /// A value of -1.0 corresponds to the topmost edge. A value of 1.0
    /// corresponds to the bottommost edge. Values are not limited to that range;
    /// values less than -1.0 represent positions above the top, and values
    /// greater than 1.0 represent positions below the bottom.
    pub y: f32,
}

impl Alignment {
    /// Creates an alignment.
    pub const fn new(x: f32, y: f32) -> Self {
        Self { x: x, y: y }
    }

    /// The top left corner.
    pub const TOP_LEFT: Alignment = Alignment::new((-1.0), (-1.0));
    /// The center point along the top edge.
    pub const TOP_CENTER: Alignment = Alignment::new(0.0, (-1.0));
    /// The top right corner.
    pub const TOP_RIGHT: Alignment = Alignment::new(1.0, (-1.0));
    /// The center point along the left edge.
    pub const CENTER_LEFT: Alignment = Alignment::new((-1.0), 0.0);
    /// The center point, both horizontally and vertically.
    pub const CENTER: Alignment = Alignment::new(0.0, 0.0);
    /// The center point along the right edge.
    pub const CENTER_RIGHT: Alignment = Alignment::new(1.0, 0.0);
    /// The bottom left corner.
    pub const BOTTOM_LEFT: Alignment = Alignment::new((-1.0), 1.0);
    /// The center point along the bottom edge.
    pub const BOTTOM_CENTER: Alignment = Alignment::new(0.0, 1.0);
    /// The bottom right corner.
    pub const BOTTOM_RIGHT: Alignment = Alignment::new(1.0, 1.0);

    /// Returns the offset that is this fraction in the direction of the given offset.
    pub fn along_offset(&self, other: Offset) -> Offset {
        let center_x: f32 = (other.dx / 2.0);
        let center_y: f32 = (other.dy / 2.0);
        Offset::new(
            (center_x + (self.x * center_x)),
            (center_y + (self.y * center_y)),
        )
    }

    /// Returns the offset that is this fraction within the given size.
    pub fn along_size(&self, other: Size) -> Offset {
        let center_x: f32 = (other.width / 2.0);
        let center_y: f32 = (other.height / 2.0);
        Offset::new(
            (center_x + (self.x * center_x)),
            (center_y + (self.y * center_y)),
        )
    }

    /// Returns the point that is this fraction within the given rect.
    pub fn within_rect(&self, rect: Rect) -> Offset {
        let half_width: f32 = (rect.width / 2.0);
        let half_height: f32 = (rect.height / 2.0);
        Offset::new(
            ((rect.left + half_width) + (self.x * half_width)),
            ((rect.top + half_height) + (self.y * half_height)),
        )
    }

    /// Returns a rect of the given size, aligned within given rect as specified
    /// by this alignment.
    ///
    /// For example, a 100×100 size inscribed on a 200×200 rect using
    /// [Alignment.topLeft] would be the 100×100 rect at the top left of
    /// the 200×200 rect.
    pub fn inscribe(&self, size: Size, rect: Rect) -> Rect {
        let half_width_delta: f32 = ((rect.width - size.width) / 2.0);
        let half_height_delta: f32 = ((rect.height - size.height) / 2.0);
        Rect::from_l_t_w_h(
            ((rect.left + half_width_delta) + (self.x * half_width_delta)),
            ((rect.top + half_height_delta) + (self.y * half_height_delta)),
            size.width,
            size.height,
        )
    }

    pub fn resolve(&self, direction: Option<TextDirection>) -> Alignment {
        *self
    }
}

/// Returns the difference between two [Alignment]s.
impl std::ops::Sub<Alignment> for Alignment {
    type Output = Alignment;

    fn sub(self, other: Alignment) -> Self::Output {
        Alignment::new((self.x - other.x), (self.y - other.y))
    }
}

/// Returns the sum of two [Alignment]s.
impl std::ops::Add<Alignment> for Alignment {
    type Output = Alignment;

    fn add(self, other: Alignment) -> Self::Output {
        Alignment::new((self.x + other.x), (self.y + other.y))
    }
}

/// Returns the negation of the given [Alignment].
impl std::ops::Neg for Alignment {
    type Output = Alignment;

    fn neg(self) -> Self::Output {
        Alignment::new((-self.x), (-self.y))
    }
}

/// Scales the [Alignment] in each dimension by the given factor.
impl std::ops::Mul<f32> for Alignment {
    type Output = Alignment;

    fn mul(self, other: f32) -> Self::Output {
        Alignment::new((self.x * other), (self.y * other))
    }
}

/// Divides the [Alignment] in each dimension by the given factor.
impl std::ops::Div<f32> for Alignment {
    type Output = Alignment;

    fn div(self, other: f32) -> Self::Output {
        Alignment::new((self.x / other), (self.y / other))
    }
}

impl Alignment {
    /// Integer divides the [Alignment] in each dimension by the given factor.
    pub fn int_div(&self, other: f32) -> Alignment {
        Alignment::new(((self.x / other).trunc()), ((self.y / other).trunc()))
    }
}

/// Computes the remainder in each dimension by the given factor.
impl std::ops::Rem<f32> for Alignment {
    type Output = Alignment;

    fn rem(self, other: f32) -> Self::Output {
        Alignment::new((self.x % other), (self.y % other))
    }
}
