// Generated by tools/dart2rust from upstream `Asserts`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Asserts {
    pub value: f32,
}

impl Asserts {
    /// The constructor's own check, from the initialiser list.
    pub fn new(value: f32) -> Self {
        debug_assert!((value >= 0.0), "value must not be negative");
        Self { value: value }
    }

    /// A check in a body, with a message.
    pub fn halved(&self) -> f32 {
        debug_assert!((self.value > 0.0), "halving zero is not useful");
        (self.value / 2.0)
    }

    /// A check whose message is an interpolation, which is not translated -- the
    /// condition is the contract, the message is diagnostics.
    pub fn doubled(&self) -> f32 {
        // assert message, not translated: 'value $value is too large to double'
        debug_assert!((self.value < 1000.0));
        (self.value * 2.0)
    }

    /// No message at all.
    pub fn squared(&self) -> f32 {
        debug_assert!((self.value >= 0.0));
        (self.value * self.value)
    }
}
