use crate::DartAny;

// Generated by tools/dart2rust from upstream `Assignment`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Assignment {
    pub step: f64,
}

impl Assignment {
    pub const fn new(step: f64) -> Self {
        Self { step: step }
    }

    /// Plain reassignment. `total` is reassigned, `factor` never is.
    pub fn accumulate(&self) -> f64 {
        let mut total: f64 = 0.0;
        let factor: f64 = 2.0;
        total = (total + (self.step * factor));
        total = (total + self.step);
        total
    }

    /// Compound assignment, which Kernel has already expanded to `x = x + y`.
    pub fn compound(&self) -> f64 {
        let mut total: f64 = 10.0;
        total = (total + self.step);
        total = (total - 1.0);
        total = (total * 2.0);
        total
    }

    /// Assigned in one branch only -- still needs `mut`.
    pub fn branch(&self, big: bool) -> f64 {
        let mut value: f64 = 1.0;
        if big {
            value = 100.0;
        }
        value
    }

    /// A parameter reassigned in the body. Rust spells that `mut start: f32` in
    /// the signature, which is the parameter's own declaration.
    pub fn shadow(&self, mut start: f64) -> f64 {
        start = (start + 1.0);
        start
    }
}

impl DartAny for Assignment {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}
