use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Assignment`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Assignment {
    pub step: f64,
}

impl Assignment {
    pub const fn new(step: f64) -> Self {
        Self { step: step }
    }

    pub fn accumulate(&self) -> f64 {
        let mut total: f64 = 0.0;
        let factor: f64 = 2.0;
        total = (total + (self.step * factor));
        total = (total + self.step);
        total
    }

    pub fn compound(&self) -> f64 {
        let mut total: f64 = 10.0;
        total = (total + self.step);
        total = (total - 1.0);
        total = (total * 2.0);
        total
    }

    pub fn branch(&self, big: bool) -> f64 {
        let mut value: f64 = 1.0;
        if big {
            value = 100.0;
        }
        value
    }

    pub fn shadow(&self, mut start: f64) -> f64 {
        start = (start + 1.0);
        start
    }
}

impl DartAny for Assignment {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Assignment" }
    }
}
