use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// The front end refused 1 member(s) in this library:
// NOT TRANSLATED: Placement: unsupported break out of a switch from inside a case: break;

// Generated by tools/dart2rust from upstream `Corner`
// (Dart enum -> Rust enum).

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Corner {
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
}

impl Corner {
    pub fn index(&self) -> i64 {
        *self as i64
    }
    pub fn name(&self) -> String {
        match self {
            Corner::TopLeft => "topLeft".to_string(),
            Corner::TopRight => "topRight".to_string(),
            Corner::BottomLeft => "bottomLeft".to_string(),
            Corner::BottomRight => "bottomRight".to_string(),
        }
    }
}

impl DartEnum for Corner {
    fn name(&self) -> String {
        Corner::name(self)
    }
    fn index(&self) -> i64 {
        Corner::index(self)
    }
}

impl FromDynamic for Corner {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Corner {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Corner was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Corner was declared")
    }
}

impl DartNullable for Corner {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Corner {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Corner {
    fn dart_runtime_type(&self) -> Type {
        Type::of("Corner")
    }
    fn dart_to_string(&self) -> String {
        format!("Corner.{}", DartEnum::name(self))
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}

// Generated by tools/dart2rust from upstream `Placement`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Placement {
    pub width: f64,
    pub height: f64,
}

impl Placement {
    pub const fn new(width: f64, height: f64) -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({
            Self {
                width: width,
                height: height,
            }
        })
    }

    /// Exhaustive, no default -- which Rust checks and Dart does not.
    pub fn offset_x(&self, corner: Corner) -> Result<f64, std::rc::Rc<dyn Object>> {
        match corner {
            Corner::TopLeft => {
                return Ok(0.0);
            }
            Corner::TopRight => {
                return Ok(self.width);
            }
            Corner::BottomLeft => {
                return Ok(0.0);
            }
            Corner::BottomRight => {
                return Ok(self.width);
            }
            _ => {}
        }
    }

    /// Two values on one arm, a default, and a `break` at the end of each case.
    pub fn depth(&self, corner: Corner) -> Result<f64, std::rc::Rc<dyn Object>> {
        let mut result: f64 = 0.0;
        match corner {
            Corner::TopLeft | Corner::TopRight => {
                result = 3.0;
            }
            Corner::BottomLeft => {
                result = 11.0;
            }
            _ => {
                result = 29.0;
            }
        }
        Ok(result)
    }

    /// `max` and `clamp`, which Rust spells the same way for floats. `max` is
    /// one spelling for integers too, since `f32::max` is inherent and `Ord::max`
    /// covers the rest -- 372 calls upstream.
    pub fn bounded(&self, mut value: f64) -> Result<f64, std::rc::Rc<dyn Object>> {
        Ok((value.clamp(self.width, self.height) as f64).max(1.0))
    }

    /// A switch on a **string**. Rust's `match` takes patterns, and
    /// `"wide".to_string()` is a call, not one -- so this comes out as the
    /// if-else chain it always was. 266 arms upstream are like this.
    ///
    /// The carriage return is here on purpose: written raw into a Rust literal
    /// it is a hard error, and upstream has 108 of them.
    pub fn by_name(&self, name: String) -> Result<f64, std::rc::Rc<dyn Object>> {
        if name == "wide".to_string() {
            return Ok(7.0);
        } else if name == "narrow".to_string() || name == "thin".to_string() {
            return Ok(13.0);
        } else if name == "crlf\r\n".to_string() {
            return Ok(17.0);
        } else {
            return Ok(23.0);
        }
    }
}

impl FromDynamic for Placement {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Placement {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Placement was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Placement was declared")
    }
}

impl DartNullable for Placement {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Placement {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Placement {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Placement")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Placement")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}
