use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// The front end refused 1 member(s) in this library:
// NOT TRANSLATED: Placement: unsupported break out of a switch from inside a case: BreakStatement(break label0;)

// Generated by tools/dart2rust from upstream `Corner`
// (Dart enum -> Rust enum).

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Corner {
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
}

impl Corner {
    pub fn index(&self) -> i64 {
        *self as i64
    }
}

// Generated by tools/dart2rust from upstream `Placement`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Placement {
    pub width: f64,
    pub height: f64,
}

impl Placement {
    pub const fn new(width: f64, height: f64) -> Self {
        Self {
            width: width,
            height: height,
        }
    }

    pub fn offset_x(&self, corner: Corner) -> f64 {
        match corner {
            Corner::TopLeft => {
                return 0.0;
            }
            Corner::TopRight => {
                return self.width;
            }
            Corner::BottomLeft => {
                return 0.0;
            }
            _ => {
                return self.width;
            }
        }
    }

    pub fn depth(&self, corner: Corner) -> f64 {
        let mut result: f64 = 0.0;
        match corner {
            Corner::TopLeft | Corner::TopRight => {
                result = 3.0;
            }
            Corner::BottomLeft => {
                result = 11.0;
            }
            _ => {
                result = 29.0;
            }
        }
        result
    }

    pub fn bounded(&self, mut value: f64) -> f64 {
        (value.clamp(self.width, self.height) as f64).max(1.0)
    }

    pub fn by_name(&self, name: String) -> f64 {
        if name == "wide".to_string() {
            return 7.0;
        } else if name == "narrow".to_string() || name == "thin".to_string() {
            return 13.0;
        } else if name == "crlf\r\n".to_string() {
            return 17.0;
        } else {
            return 23.0;
        }
    }
}

impl DartAny for Placement {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Placement" }
    }
}
