use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Paint`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Paint {
    pub width: f64,
    pub alpha: f64,
    pub blur: f64,
}

impl Paint {
    pub fn new() -> Self {
        Self {
            width: 0.0,
            alpha: 0.0,
            blur: 0.0,
        }
    }

    pub fn widen(&mut self, by: f64) -> () {
        self.width = (self.width + by);
    }
}

impl DartAny for Paint {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Paint" }
    }
}

// Generated by tools/dart2rust from upstream `Tinted`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tinted {
    pub opacity: f64,
    pub tint: f64,
}

impl Tinted {
    pub fn new(value: f64) -> Self {
        Self {
            opacity: value,
            tint: 0.5,
        }
    }
}

impl DartAny for Tinted {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Tinted" }
    }
}

// Generated by tools/dart2rust from upstream `Painter`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Painter {}

impl Painter {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn thin(&self) -> Paint {
        {
            let mut cascaded: Paint = Paint::new();
            cascaded.width = 1.0;
            cascaded
        }
    }

    pub fn styled(&self) -> Paint {
        {
            let mut cascaded: Paint = Paint::new();
            cascaded.width = 2.0;
            cascaded.alpha = 3.0;
            cascaded.blur = 4.0;
            cascaded
        }
    }

    pub fn widened(&self) -> Paint {
        {
            let mut cascaded: Paint = Paint::new();
            cascaded.width = 5.0;
            cascaded.widen(2.0);
            cascaded
        }
    }
}

impl DartAny for Painter {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Painter" }
    }
}
