// The front end refused 1 member(s) in this library:
// NOT TRANSLATED: Closures: unsupported closure capturing `this`: (double v) => scaled(v)

// Generated by tools/dart2rust from upstream `Closures`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Closures {
    pub factor: f64,
}

impl Closures {
    pub const fn new(factor: f64) -> Self {
        Self { factor: factor }
    }

    /// A static method rather than a top-level function: top-level functions are
    /// not translated yet (964 refusals of their own), and a fixture that needs
    /// an untranslated construct tests nothing.
    pub fn apply_twice(f: impl Fn(f64) -> f64, x: f64) -> f64 {
        (f)((f)(x))
    }

    /// Captures nothing: a plain function in Rust terms.
    pub fn doubled(&self, x: f64) -> f64 {
        Closures::apply_twice(|v: f64| (v + 1.0), x)
    }

    /// Reads an outer local. Rust borrows it; nothing has to be said.
    pub fn scaled_by(&self, amount: f64, x: f64) -> f64 {
        Closures::apply_twice(|v: f64| (v * amount), x)
    }

    /// Two captured locals, so pairing them wrongly changes the answer.
    pub fn blend(&self, a: f64, b: f64, x: f64) -> f64 {
        Closures::apply_twice(|v: f64| ((v * a) + b), x)
    }

    /// A two-parameter closure whose arguments are **not** interchangeable: with
    /// one parameter, reversing the list is a no-op and a mutation that shuffles
    /// them survives. Round twenty-one learned the same thing about `super`.
    pub fn combine(f: impl Fn(f64, f64) -> f64) -> f64 {
        (f)(10.0, 3.0)
    }

    pub fn subtracted(&self) -> f64 {
        Closures::combine(|a: f64, b: f64| (a - b))
    }

    /// Reads a field of `this` from a closure written as a call argument. The
    /// borrow lasts exactly as long as `applyTwice` does, so this translates.
    pub fn by_factor(&self, x: f64) -> f64 {
        Closures::apply_twice(|v: f64| (v * self.factor), x)
    }

    pub fn scaled(&self, v: f64) -> f64 {
        (v * self.factor)
    }

    /// A **method used as a value**: `applyTwice(scaled, x)` hands the method
    /// over without calling it. In Rust that is a closure that calls it, so it
    /// is the same question as any other closure and gets the same answer --
    /// here it is an argument, a borrowed position, so it may borrow `this`.
    pub fn by_tear_off(&self, x: f64) -> f64 {
        Closures::apply_twice(|v: f64| self.scaled(v), x)
    }

    /// Reads a `final` field and is **returned**, so it outlives the call.
    ///
    /// It cannot hold `this`, and it does not have to: `factor` is `final`, so a
    /// copy taken when the closure is made is the same value a read at call time
    /// would give. That is what makes copying sound here and not in general --
    /// a field that can change would give two different answers.
    pub fn scaler(&self) -> Box<dyn Fn(f64) -> f64> {
        Box::new({
            let factor = self.factor;
            move |v: f64| (v * factor)
        })
    }
}
