use crate::DartAny;
use crate::Type;

// Generated from fixtures/constinstance.dart by the **Kernel** front end.
//
// Every other file here comes from the analyzer one, because that is what
// dart2rust.dart runs. That round's work is Kernel-only -- the analyzer never
// meets an evaluated constant -- so testing it means testing that side's
// output. fixtures.py still checks the two agree on everything but the
// constants themselves, which the fixture declares with // DIFFERS:.

// Generated by tools/dart2rust from upstream `Spacing`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Spacing {
    pub amount: f64,
}

impl Spacing {
    pub(crate) const fn new_(amount: f64) -> Self {
        Self { amount: amount }
    }

    pub const TIGHT: Spacing = (Spacing { amount: 3.0 });
    pub const WIDE: Spacing = (Spacing { amount: 17.0 });

    pub fn twice(&self) -> f64 {
        (self.amount * 2.0)
    }
}

impl DartAny for Spacing {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Spacing" }
    }
}

// Generated by tools/dart2rust from upstream `InsetBase`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct InsetBase {
    pub(crate) _h: f64,
    pub(crate) _v: f64,
}

impl InsetBase {
    pub const fn new(_h: f64, _v: f64) -> Self {
        Self { _h: _h, _v: _v }
    }
}

impl DartAny for InsetBase {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "InsetBase" }
    }
}

// Generated by tools/dart2rust from upstream `Inset`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Inset {
    pub(crate) _h: f64,
    pub(crate) _v: f64,
}

impl Inset {
    pub const fn new(h: f64, v: f64) -> Self {
        Self { _h: h, _v: v }
    }

    pub const SMALL: Inset = (Inset { _h: 5.0, _v: 7.0 });
    pub const LARGE: Inset = (Inset { _h: 23.0, _v: 29.0 });

    pub fn span(&self) -> f64 {
        (self._h + self._v)
    }
}

impl DartAny for Inset {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Inset" }
    }
}

// Generated by tools/dart2rust from upstream `Span`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Span {
    pub start: i64,
    pub end: i64,
}

impl Span {
    pub const fn new(start: i64, length: i64) -> Self {
        Self {
            start: start,
            end: (start + length),
        }
    }

    pub const FIRST: Span = (Span { start: 2, end: 13 });
    pub const SECOND: Span = (Span {
        start: 40,
        end: 100,
    });

    pub fn width(&self) -> i64 {
        (self.end - self.start)
    }
}

impl DartAny for Span {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Span" }
    }
}
