use crate::RangeError;

// Generated by tools/dart2rust from upstream `Sieve`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Sieve {
    pub limit: i64,
}

impl Sieve {
    pub const fn new(limit: i64) -> Self {
        Self { limit: limit }
    }

    /// `throw` in expression position -- the right side of `??`.
    pub fn at_least_one(&self, given: Option<i64>) -> Result<i64, RangeError> {
        Ok(match given {
            Some(__value) => __value,
            None => return Err(RangeError::new("nothing given".to_string())),
        })
    }

    /// `break` leaves the loop, and the statement after it still runs.
    pub fn first_over(&self, bound: i64) -> i64 {
        let mut found: i64 = (-1);
        let mut i: i64 = 0;
        while (i < self.limit) {
            if (i > bound) {
                found = i;
                break;
            }
            found = (-2);
            i = (i + 1);
        }
        found
    }

    /// Both in one loop, which is the case that needs the labels to be told
    /// apart: the `continue` leaves the body block and lands on the update, and
    /// the `break` has to cross that block to leave the loop -- which Rust will
    /// not let an unlabelled `break` do.
    pub fn first_odd_over(&self, bound: i64) -> i64 {
        let mut found: i64 = (-1);
        let mut i: i64 = 0;
        '__l0: while (i < self.limit) {
            '__l1: {
                if ((i % 2) == 0) {
                    break '__l1;
                }
                if (i > bound) {
                    found = i;
                    break '__l0;
                }
            }
            i = (i + 1);
        }
        found
    }

    /// `continue` is the other half: Kernel spells it as a `break` out of a label
    /// wrapped around the body rather than around the loop.
    pub fn odds_below(&self) -> i64 {
        let mut total: i64 = 0;
        let mut i: i64 = 0;
        while (i < self.limit) {
            '__l2: {
                if ((i % 2) == 0) {
                    break '__l2;
                }
                total = (total + i);
            }
            i = (i + 1);
        }
        total
    }
}
