use crate::dart_prelude::*;
use crate::DartAny;
use crate::RangeError;
use crate::Type;

// Generated by tools/dart2rust from upstream `Sieve`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Sieve {
    pub limit: i64,
}

impl Sieve {
    pub const fn new(limit: i64) -> Self {
        Self { limit: limit }
    }

    pub fn at_least_one(&self, given: Option<i64>) -> i64 {
        match given {
            Some(__value) => __value,
            None => panic!(
                "uncaught Dart exception: {:?}",
                RangeError::new("nothing given".to_string())
            ),
        }
    }

    pub fn first_over(&self, bound: i64) -> i64 {
        let mut found: i64 = (-1);
        let mut i: i64 = 0;
        while (i < self.limit) {
            if (i > bound) {
                found = i;
                break;
            }
            found = (-2);
            i = (i + 1);
        }
        found
    }

    pub fn first_odd_over(&self, bound: i64) -> i64 {
        let mut found: i64 = (-1);
        let mut i: i64 = 0;
        '__l0: while (i < self.limit) {
            '__l1: {
                if ((i % 2) == 0) {
                    break '__l1;
                }
                if (i > bound) {
                    found = i;
                    break '__l0;
                }
            }
            i = (i + 1);
        }
        found
    }

    pub fn odds_below(&self) -> i64 {
        let mut total: i64 = 0;
        let mut i: i64 = 0;
        while (i < self.limit) {
            '__l2: {
                if ((i % 2) == 0) {
                    break '__l2;
                }
                total = (total + i);
            }
            i = (i + 1);
        }
        total
    }
}

impl DartAny for Sieve {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Sieve" }
    }
}
