// Generated by tools/dart2rust. See lib/prelude.dart.
//
// `dart:core` and `dart:typed_data` names with no library of their own to be
// translated from. Hand-written, not translated.
#![allow(dead_code, non_snake_case)]

use std::fmt;

/// Dart's `Object`, as the one thing Rust has for "anything": a trait every
/// type implements. `&dyn Object` then accepts what `Object` accepted.
pub trait Object {}

impl<T: ?Sized> Object for T {}

/// What a Dart value can be *asked*.
///
/// `x is Foo` wants to know what a value really is, and a Rust trait object
/// cannot be asked unless the trait says it can. `Any` is the mechanism; this
/// is the one line of it that every translated trait inherits, so every trait
/// object can answer.
///
/// Not a blanket impl. `Box<dyn Widget>` would then implement it *itself*, and
/// `.as_any()` would answer about the box rather than about what is in it --
/// a downcast that is always false and never says so. Each translated struct
/// gets its own one-line impl instead, so the only way to reach `as_any` from
/// a box is through the trait inside it.
pub trait DartAny: 'static {
    fn as_any(&self) -> &dyn std::any::Any;
}

/// Dart's `Duration`: a signed span counted in whole microseconds.
///
/// Not `std::time::Duration`, which is unsigned and counts nanoseconds.
/// Upstream subtracts durations and checks `isNegative`, so the sign has to
/// survive, and every Dart constructor and getter is in microseconds.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Default, Hash)]
pub struct Duration {
    pub microseconds: i64,
}

impl Duration {
    pub const ZERO: Duration = Duration { microseconds: 0 };

    pub const fn from_microseconds(microseconds: i64) -> Self {
        Duration { microseconds }
    }

    pub const fn from_milliseconds(milliseconds: i64) -> Self {
        Duration {
            microseconds: milliseconds * 1000,
        }
    }

    pub const fn from_seconds(seconds: i64) -> Self {
        Duration {
            microseconds: seconds * 1000000,
        }
    }

    /// Truncating, like Dart's: `inMilliseconds` of 1500us is 1, not 2.
    pub fn in_microseconds(&self) -> i64 {
        self.microseconds
    }

    pub fn in_milliseconds(&self) -> i64 {
        self.microseconds / 1000
    }

    pub fn in_seconds(&self) -> i64 {
        self.microseconds / 1000000
    }

    pub fn in_minutes(&self) -> i64 {
        self.microseconds / 60000000
    }

    pub fn in_hours(&self) -> i64 {
        self.microseconds / 3600000000
    }

    pub fn in_days(&self) -> i64 {
        self.microseconds / 86400000000
    }

    pub fn is_negative(&self) -> bool {
        self.microseconds < 0
    }

    pub fn abs(&self) -> Duration {
        Duration {
            microseconds: self.microseconds.abs(),
        }
    }

    pub fn compare_to(&self, other: Duration) -> i64 {
        match self.microseconds.cmp(&other.microseconds) {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        }
    }
}

impl std::ops::Add for Duration {
    type Output = Duration;
    fn add(self, other: Duration) -> Duration {
        Duration {
            microseconds: self.microseconds + other.microseconds,
        }
    }
}

impl std::ops::Sub for Duration {
    type Output = Duration;
    fn sub(self, other: Duration) -> Duration {
        Duration {
            microseconds: self.microseconds - other.microseconds,
        }
    }
}

impl std::ops::Neg for Duration {
    type Output = Duration;
    fn neg(self) -> Duration {
        Duration {
            microseconds: -self.microseconds,
        }
    }
}

impl std::ops::Mul<i64> for Duration {
    type Output = Duration;
    fn mul(self, by: i64) -> Duration {
        Duration {
            microseconds: self.microseconds * by,
        }
    }
}

impl fmt::Display for Duration {
    /// Dart prints `0:00:01.500000`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let us = self.microseconds.abs();
        if self.microseconds < 0 {
            write!(f, "-")?;
        }
        write!(
            f,
            "{}:{:02}:{:02}.{:06}",
            us / 3600000000,
            (us / 60000000) % 60,
            (us / 1000000) % 60,
            us % 1000000
        )
    }
}

/// Dart's `StringBuffer`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StringBuffer {
    text: String,
}

impl StringBuffer {
    pub fn new() -> Self {
        StringBuffer {
            text: String::new(),
        }
    }

    pub fn write(&mut self, value: &str) {
        self.text.push_str(value);
    }

    pub fn writeln(&mut self, value: &str) {
        self.text.push_str(value);
        self.text.push('\n');
    }

    pub fn write_char_code(&mut self, code: i64) {
        if let Some(c) = char::from_u32(code as u32) {
            self.text.push(c);
        }
    }

    pub fn clear(&mut self) {
        self.text.clear();
    }

    pub fn length(&self) -> i64 {
        self.text.chars().count() as i64
    }

    pub fn is_empty(&self) -> bool {
        self.text.is_empty()
    }

    pub fn is_not_empty(&self) -> bool {
        !self.text.is_empty()
    }
}

impl fmt::Display for StringBuffer {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}

/// Dart's `Set`, backed by a `Vec`.
///
/// Not `HashSet`: Dart puts `double`s and objects with no `hashCode` of their
/// own into sets, and requiring `Hash + Eq` here would refuse code that is
/// perfectly ordinary in Dart. Membership is therefore linear, which is the
/// right trade for a translation -- correct first, and the sets upstream keeps
/// are small.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Set<T> {
    items: Vec<T>,
}

impl<T: PartialEq + Clone> Set<T> {
    pub fn new() -> Self {
        Set { items: Vec::new() }
    }

    pub fn from(items: Vec<T>) -> Self {
        let mut set = Set::new();
        for item in items {
            set.add(item);
        }
        set
    }

    /// Dart returns whether the value was new.
    pub fn add(&mut self, value: T) -> bool {
        if self.contains(&value) {
            return false;
        }
        self.items.push(value);
        true
    }

    pub fn add_all(&mut self, values: Vec<T>) {
        for value in values {
            self.add(value);
        }
    }

    pub fn contains(&self, value: &T) -> bool {
        self.items.iter().any(|item| item == value)
    }

    pub fn remove(&mut self, value: &T) -> bool {
        match self.items.iter().position(|item| item == value) {
            Some(at) => {
                self.items.remove(at);
                true
            }
            None => false,
        }
    }

    pub fn clear(&mut self) {
        self.items.clear();
    }

    pub fn length(&self) -> i64 {
        self.items.len() as i64
    }

    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    pub fn is_not_empty(&self) -> bool {
        !self.items.is_empty()
    }

    pub fn to_list(&self) -> Vec<T> {
        self.items.clone()
    }

    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.items.iter()
    }

    pub fn union(&self, other: &Set<T>) -> Set<T> {
        let mut out = self.clone();
        out.add_all(other.to_list());
        out
    }

    pub fn intersection(&self, other: &Set<T>) -> Set<T> {
        Set {
            items: self
                .items
                .iter()
                .filter(|item| other.contains(item))
                .cloned()
                .collect(),
        }
    }

    pub fn difference(&self, other: &Set<T>) -> Set<T> {
        Set {
            items: self
                .items
                .iter()
                .filter(|item| !other.contains(item))
                .cloned()
                .collect(),
        }
    }
}

impl<T> IntoIterator for Set<T> {
    type Item = T;
    type IntoIter = std::vec::IntoIter<T>;
    fn into_iter(self) -> Self::IntoIter {
        self.items.into_iter()
    }
}

/// Dart's `StackTrace`.
///
/// Opaque on purpose. Dart's is captured by the runtime at the point a throw
/// happens, and there is no runtime here to capture one; what upstream does
/// with it is print it or pass it along, and both work with a string that says
/// so honestly.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StackTrace {
    text: String,
}

impl StackTrace {
    pub fn empty() -> Self {
        StackTrace {
            text: String::new(),
        }
    }

    pub fn current() -> Self {
        StackTrace {
            text: "<no stack trace: translated from Dart>".to_string(),
        }
    }
}

impl fmt::Display for StackTrace {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}

/// Dart's `DateTime`: an instant, counted in microseconds from the epoch.
///
/// `now()` is the one thing here that needs the outside world, and it uses the
/// system clock. Dart's is the same clock. `isUtc` is carried because upstream
/// compares on it, and the arithmetic ignores it exactly as Dart's does --
/// a `Duration` is a span, not a calendar step.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Default, Hash)]
pub struct DateTime {
    pub microseconds_since_epoch: i64,
    pub is_utc: bool,
}

impl DateTime {
    pub fn now() -> Self {
        let since = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_micros() as i64)
            .unwrap_or(0);
        DateTime {
            microseconds_since_epoch: since,
            is_utc: false,
        }
    }

    pub fn from_microseconds_since_epoch(microseconds: i64) -> Self {
        DateTime {
            microseconds_since_epoch: microseconds,
            is_utc: false,
        }
    }

    pub fn from_milliseconds_since_epoch(milliseconds: i64) -> Self {
        DateTime {
            microseconds_since_epoch: milliseconds * 1000,
            is_utc: false,
        }
    }

    pub fn milliseconds_since_epoch(&self) -> i64 {
        self.microseconds_since_epoch / 1000
    }

    pub fn difference(&self, other: DateTime) -> Duration {
        Duration {
            microseconds: self.microseconds_since_epoch - other.microseconds_since_epoch,
        }
    }

    pub fn add(&self, span: Duration) -> DateTime {
        DateTime {
            microseconds_since_epoch: self.microseconds_since_epoch + span.microseconds,
            is_utc: self.is_utc,
        }
    }

    pub fn subtract(&self, span: Duration) -> DateTime {
        DateTime {
            microseconds_since_epoch: self.microseconds_since_epoch - span.microseconds,
            is_utc: self.is_utc,
        }
    }

    pub fn is_before(&self, other: DateTime) -> bool {
        self.microseconds_since_epoch < other.microseconds_since_epoch
    }

    pub fn is_after(&self, other: DateTime) -> bool {
        self.microseconds_since_epoch > other.microseconds_since_epoch
    }
}

/// A value that belongs to one isolate, standing in a Rust `static`.
///
/// Dart's `static` is one **per isolate**, and an isolate is a thread. Rust's
/// `static` is one per *process*, so what it holds must be `Sync` -- and a
/// `Box<dyn Fn(..)>`, which is what half of Flutter's statics hold, is not and
/// never will be.
///
/// `thread_local!` says the same thing safely, and would be the right answer if
/// its value could be reached without a closure; it cannot, and
/// `Box<dyn Fn(..)>` is not `Clone`, so every read would have to be
/// restructured. This says it instead, and the `unsafe` is carrying exactly
/// one claim:
///
/// **the translated program runs on one thread.**
///
/// That is true of a Dart isolate by construction, and it is the thing to
/// check before running anything translated here: the moment this program
/// spawns a thread that touches a static, this is unsound. Nothing translated
/// so far can spawn one -- `Isolate.spawn` and `compute` are not translated --
/// and if that changes, this is where it breaks.
pub struct Isolate<T>(pub T);

unsafe impl<T> Sync for Isolate<T> {}
unsafe impl<T> Send for Isolate<T> {}

impl<T> std::ops::Deref for Isolate<T> {
    type Target = T;
    fn deref(&self) -> &T {
        &self.0
    }
}

impl<T> std::ops::DerefMut for Isolate<T> {
    fn deref_mut(&mut self) -> &mut T {
        &mut self.0
    }
}

/// `dart:core`'s "no argument was passed" marker.
///
/// Upstream's `copyWith` methods take a sentinel as the default so that
/// passing `null` and passing nothing can be told apart. What is done with it
/// is compare identities, so an empty struct says everything it says -- and it
/// is `Copy`, which is what makes the comparison free.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct SentinelValue;

/// Dart's `MapEntry`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct MapEntry<K, V> {
    pub key: K,
    pub value: V,
}

impl<K, V> MapEntry<K, V> {
    pub fn new(key: K, value: V) -> Self {
        MapEntry { key, value }
    }
}

/// Dart's `Map`: a lookup that **keeps insertion order**.
///
/// A Dart map literal is a `LinkedHashMap`, and `keys`, `values`, `entries`
/// and `forEach` walk it in the order things were put in. A
/// `std::collections::HashMap` does not, so those five members were refused --
/// 97 of them -- rather than reorder anything quietly.
///
/// A `Vec` of pairs keeps the order and costs a linear lookup. That is the
/// same trade `Set<T>` next door has always made, and taking it here too
/// makes one decision instead of two: whatever these containers cost, they
/// cost it the same way.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Map<K, V> {
    entries: Vec<(K, V)>,
}

impl<K: PartialEq + Clone, V: Clone> Map<K, V> {
    pub fn new() -> Self {
        Map {
            entries: Vec::new(),
        }
    }

    pub fn from<const N: usize>(items: [(K, V); N]) -> Self {
        let mut map = Map::new();
        for (key, value) in items {
            map.insert(key, value);
        }
        map
    }

    fn at(&self, key: &K) -> Option<usize> {
        self.entries.iter().position(|(k, _)| k == key)
    }

    pub fn get(&self, key: &K) -> Option<&V> {
        self.at(key).map(|i| &self.entries[i].1)
    }

    /// Dart gives back what was there; so does Rust's `HashMap::insert`.
    /// Replacing a value keeps the key where it was, which is what insertion
    /// order means once a key is written twice.
    pub fn insert(&mut self, key: K, value: V) -> Option<V> {
        match self.at(&key) {
            Some(i) => Some(std::mem::replace(&mut self.entries[i].1, value)),
            None => {
                self.entries.push((key, value));
                None
            }
        }
    }

    pub fn contains_key(&self, key: &K) -> bool {
        self.at(key).is_some()
    }

    pub fn remove(&mut self, key: &K) -> Option<V> {
        self.at(key).map(|i| self.entries.remove(i).1)
    }

    pub fn clear(&mut self) {
        self.entries.clear();
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// In insertion order, which is the whole reason for this type.
    pub fn keys(&self) -> Vec<K> {
        self.entries.iter().map(|(k, _)| k.clone()).collect()
    }

    pub fn values(&self) -> Vec<V> {
        self.entries.iter().map(|(_, v)| v.clone()).collect()
    }

    pub fn entries(&self) -> Vec<MapEntry<K, V>> {
        self.entries
            .iter()
            .map(|(k, v)| MapEntry {
                key: k.clone(),
                value: v.clone(),
            })
            .collect()
    }

    pub fn for_each(&self, mut f: impl FnMut(K, V)) {
        for (key, value) in &self.entries {
            f(key.clone(), value.clone());
        }
    }

    /// Dart's `putIfAbsent`: the value that is there afterwards, either way.
    pub fn put_if_absent(&mut self, key: K, make: impl FnOnce() -> V) -> V {
        if let Some(i) = self.at(&key) {
            return self.entries[i].1.clone();
        }
        let value = make();
        self.entries.push((key, value.clone()));
        value
    }

    pub fn extend(&mut self, other: Map<K, V>) {
        for (key, value) in other.entries {
            self.insert(key, value);
        }
    }
}

impl<K, V> IntoIterator for Map<K, V> {
    type Item = (K, V);
    type IntoIter = std::vec::IntoIter<(K, V)>;
    fn into_iter(self) -> Self::IntoIter {
        self.entries.into_iter()
    }
}

/// `dart:collection`'s public map and set classes.
///
/// Dart's `LinkedHashMap` keeps insertion order and `HashMap` does not. Both
/// are the ordered `Map` here: keeping an order nothing asked for is a
/// promise too strong, never one too weak. `SplayTreeMap` is sorted, and
/// `BTreeMap` would be the same promise -- it is not translated.
pub type LinkedHashMap<K, V> = Map<K, V>;
pub type HashMap<K, V> = Map<K, V>;
pub type LinkedHashSet<T> = Set<T>;
pub type HashSet<T> = Set<T>;

/// Dart's `Queue` and its two concrete kinds, backed by a `VecDeque`.
///
/// `LinkedList` in Dart is an intrusive list -- its elements carry their own
/// links -- and a `VecDeque` is not that. Nothing translated so far uses the
/// intrusive part, and this is where to look if something does.
pub type Queue<T> = std::collections::VecDeque<T>;
pub type ListQueue<T> = std::collections::VecDeque<T>;
pub type DoubleLinkedQueue<T> = std::collections::VecDeque<T>;
pub type LinkedList<T> = std::collections::VecDeque<T>;

/// Dart's `Stopwatch`.
///
/// Real, and the one other thing here that reaches the outside world: it uses
/// the monotonic clock, as Dart's does. `elapsedTicks` is microseconds, and
/// `frequency` says so, which is what Dart reports on every platform Flutter
/// ships to.
#[derive(Clone, Copy, Debug)]
pub struct Stopwatch {
    started: Option<std::time::Instant>,
    accumulated: u128,
}

impl Default for Stopwatch {
    fn default() -> Self {
        Stopwatch::new()
    }
}

impl Stopwatch {
    pub const FREQUENCY: i64 = 1000000;

    pub fn new() -> Self {
        Stopwatch {
            started: None,
            accumulated: 0,
        }
    }

    pub fn start(&mut self) {
        if self.started.is_none() {
            self.started = Some(std::time::Instant::now());
        }
    }

    pub fn stop(&mut self) {
        if let Some(at) = self.started.take() {
            self.accumulated += at.elapsed().as_micros();
        }
    }

    pub fn reset(&mut self) {
        self.accumulated = 0;
        if self.started.is_some() {
            self.started = Some(std::time::Instant::now());
        }
    }

    pub fn is_running(&self) -> bool {
        self.started.is_some()
    }

    pub fn elapsed_microseconds(&self) -> i64 {
        let running = self.started.map(|at| at.elapsed().as_micros()).unwrap_or(0);
        (self.accumulated + running) as i64
    }

    pub fn elapsed_milliseconds(&self) -> i64 {
        self.elapsed_microseconds() / 1000
    }

    pub fn elapsed(&self) -> Duration {
        Duration {
            microseconds: self.elapsed_microseconds(),
        }
    }
}

/// Dart's `Uri`, as far as upstream uses one.
///
/// The whole text, plus the pieces that can be taken from it without a parser
/// worth the name. Upstream builds asset keys and compares them; it does not
/// resolve relative references here, and `resolve` is left out rather than
/// written wrong. `parse` never fails, which Dart's does -- another reason not
/// to reach for this where correctness of the parse matters.
#[derive(Clone, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Uri {
    pub text: String,
}

impl Uri {
    pub fn parse(text: String) -> Self {
        Uri { text }
    }

    pub fn scheme(&self) -> String {
        match self.text.find(':') {
            Some(at) if !self.text[..at].contains('/') => self.text[..at].to_string(),
            _ => String::new(),
        }
    }

    pub fn path(&self) -> String {
        let rest = match self.text.find("://") {
            Some(at) => &self.text[at + 3..],
            None => &self.text[..],
        };
        let rest = match rest.find('/') {
            Some(at) => &rest[at..],
            None => rest,
        };
        rest.split(['?', '#']).next().unwrap_or("").to_string()
    }

    pub fn path_segments(&self) -> Vec<String> {
        self.path()
            .split('/')
            .filter(|s| !s.is_empty())
            .map(|s| s.to_string())
            .collect()
    }

    pub fn has_scheme(&self) -> bool {
        !self.scheme().is_empty()
    }
}

impl fmt::Display for Uri {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}

/// Dart's `Type`, as `runtimeType` gives it.
///
/// A name and nothing else. Upstream prints it, compares it, and uses it as a
/// map key; none of that needs the reflection Dart's `Type` can do and Rust
/// cannot. What it does *not* support is being turned back into a class, and
/// nothing here tries.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Type {
    pub name: &'static str,
}

impl Type {
    pub const fn of(name: &'static str) -> Self {
        Type { name }
    }
}

impl fmt::Display for Type {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name)
    }
}

/// Dart's `Zone`.
///
/// A zone is the async context a callback was registered in, so that running
/// it later runs it under the same error handling. Upstream stores one beside
/// each callback -- `dart:ui` keeps a `_zone` next to every platform handler --
/// and then runs the callback in it.
///
/// There is exactly one zone here, because there is no runtime to make a
/// second: `Zone::CURRENT` is it, and `run` calls the callback directly. That
/// is what the root zone does in Dart too. A program that installs a zone of
/// its own to catch errors would not get that behaviour, and this is where to
/// look when it does not.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Zone;

impl Zone {
    pub const CURRENT: Zone = Zone;

    pub fn run<T>(&self, body: impl FnOnce() -> T) -> T {
        body()
    }

    pub fn run_unary<A, T>(&self, body: impl FnOnce(A) -> T, argument: A) -> T {
        body(argument)
    }

    pub fn register_callback<T>(&self, body: impl Fn() -> T) -> impl Fn() -> T {
        body
    }
}

/// The isolate's event loop: microtasks, then timers, the way Dart's runs.
///
/// This is the smallest thing that can honestly be called a scheduler. It is
/// here because the translated code *uses* `Timer` -- 37 places name it -- and
/// a type that records nothing would be a stub. What is not here is anybody
/// calling `run_until_idle`: a translated `main` would, and there is no
/// translated `main` yet. That gap is the loop's, not the timer's.
///
/// Dart's ordering is kept because programs depend on it: every microtask
/// drains before any timer runs, and a microtask queued by a microtask runs
/// before the timers too.
pub struct Scheduler {
    microtasks: std::collections::VecDeque<Box<dyn FnOnce()>>,
    timers: Vec<Scheduled>,
    next_id: i64,
}

struct Scheduled {
    id: i64,
    due: std::time::Instant,
    period: Option<std::time::Duration>,
    callback: std::rc::Rc<dyn Fn()>,
    active: bool,
}

pub static SCHEDULER: std::sync::LazyLock<Isolate<std::cell::RefCell<Scheduler>>> =
    std::sync::LazyLock::new(|| {
        Isolate(std::cell::RefCell::new(Scheduler {
            microtasks: std::collections::VecDeque::new(),
            timers: Vec::new(),
            next_id: 1,
        }))
    });

/// Dart's `scheduleMicrotask`.
pub fn schedule_microtask(callback: Box<dyn FnOnce()>) {
    (**SCHEDULER).borrow_mut().microtasks.push_back(callback);
}

/// Runs everything that is due, and returns when nothing is.
///
/// Does **not** sleep waiting for a timer that is not due yet: sleeping is a
/// policy the host decides, and a translated program has no host here.
/// `next_due` says when to come back.
pub fn run_until_idle() {
    loop {
        let task = (**SCHEDULER).borrow_mut().microtasks.pop_front();
        match task {
            Some(task) => {
                task();
                continue;
            }
            None => {}
        }
        let now = std::time::Instant::now();
        let due: Vec<(i64, std::rc::Rc<dyn Fn()>)> = {
            let scheduler = (**SCHEDULER).borrow();
            scheduler
                .timers
                .iter()
                .filter(|t| t.active && t.due <= now)
                .map(|t| (t.id, t.callback.clone()))
                .collect()
        };
        if due.is_empty() {
            return;
        }
        for (id, callback) in due {
            // Rescheduled or dropped *before* the callback runs, so that a
            // callback cancelling its own timer wins over the reschedule.
            {
                let mut scheduler = (**SCHEDULER).borrow_mut();
                if let Some(timer) = scheduler.timers.iter_mut().find(|t| t.id == id) {
                    match timer.period {
                        Some(period) => timer.due = now + period,
                        None => timer.active = false,
                    }
                }
            }
            callback();
        }
    }
}

/// When the next timer comes due, for a host that wants to sleep until then.
pub fn next_due() -> Option<std::time::Instant> {
    (**SCHEDULER)
        .borrow()
        .timers
        .iter()
        .filter(|t| t.active)
        .map(|t| t.due)
        .min()
}

/// Dart's `Timer`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Timer {
    id: i64,
}

impl Timer {
    pub fn new(delay: Duration, callback: std::rc::Rc<dyn Fn()>) -> Self {
        Timer::schedule(delay, callback, None)
    }

    pub fn periodic(period: Duration, callback: std::rc::Rc<dyn Fn()>) -> Self {
        Timer::schedule(period, callback, Some(period))
    }

    /// Dart's `Timer.run`: a callback on the next turn of the loop.
    pub fn run(callback: std::rc::Rc<dyn Fn()>) -> Self {
        Timer::new(Duration::ZERO, callback)
    }

    fn schedule(
        delay: Duration,
        callback: std::rc::Rc<dyn Fn()>,
        period: Option<Duration>,
    ) -> Self {
        let wait = std::time::Duration::from_micros(delay.microseconds.max(0) as u64);
        let mut scheduler = (**SCHEDULER).borrow_mut();
        let id = scheduler.next_id;
        scheduler.next_id += 1;
        scheduler.timers.push(Scheduled {
            id,
            due: std::time::Instant::now() + wait,
            period: period.map(|p| std::time::Duration::from_micros(p.microseconds.max(0) as u64)),
            callback,
            active: true,
        });
        Timer { id }
    }

    pub fn cancel(&self) {
        let mut scheduler = (**SCHEDULER).borrow_mut();
        if let Some(timer) = scheduler.timers.iter_mut().find(|t| t.id == self.id) {
            timer.active = false;
        }
    }

    pub fn is_active(&self) -> bool {
        (**SCHEDULER)
            .borrow()
            .timers
            .iter()
            .any(|t| t.id == self.id && t.active)
    }
}

/// Dart's `Completer`: a future somebody else finishes.
///
/// Real, and correct against any executor. The value and the waker share one
/// cell; `complete` puts the value in and wakes whoever is waiting, and the
/// future takes the value when it is there. That is the whole of what a
/// completer is, and none of it needs a runtime -- which is why this one is
/// written out rather than left to the executor round.
///
/// `Rc`, not `Arc`: everything here belongs to one isolate. See `Isolate`.
pub struct Completer<T> {
    shared: std::rc::Rc<std::cell::RefCell<CompleterState<T>>>,
}

struct CompleterState<T> {
    value: Option<T>,
    waker: Option<std::task::Waker>,
    completed: bool,
}

impl<T> Default for Completer<T> {
    fn default() -> Self {
        Completer::new()
    }
}

impl<T> Completer<T> {
    pub fn new() -> Self {
        Completer {
            shared: std::rc::Rc::new(std::cell::RefCell::new(CompleterState {
                value: None,
                waker: None,
                completed: false,
            })),
        }
    }

    /// Dart's `Completer.sync`, which completes its future synchronously
    /// rather than through a microtask. There are no microtasks here, so the
    /// two are the same thing and this is not a stub -- it is the same
    /// behaviour arrived at from the other side.
    pub fn sync() -> Self {
        Completer::new()
    }

    pub fn complete(&self, value: T) {
        let mut state = self.shared.borrow_mut();
        if state.completed {
            panic!("Completer completed twice");
        }
        state.completed = true;
        state.value = Some(value);
        if let Some(waker) = state.waker.take() {
            waker.wake();
        }
    }

    pub fn is_completed(&self) -> bool {
        self.shared.borrow().completed
    }

    pub fn future(&self) -> CompleterFuture<T> {
        CompleterFuture {
            shared: self.shared.clone(),
        }
    }
}

pub struct CompleterFuture<T> {
    shared: std::rc::Rc<std::cell::RefCell<CompleterState<T>>>,
}

impl<T> std::future::Future for CompleterFuture<T> {
    type Output = T;

    fn poll(self: std::pin::Pin<&mut Self>, cx: &mut std::task::Context<'_>) -> std::task::Poll<T> {
        let mut state = self.shared.borrow_mut();
        match state.value.take() {
            Some(value) => std::task::Poll::Ready(value),
            None => {
                state.waker = Some(cx.waker().clone());
                std::task::Poll::Pending
            }
        }
    }
}

/// Dart's `RegExp`, as a name and a pattern and nothing else.
///
/// There is no regular-expression engine here and writing one is not this
/// project's job. What upstream does with a `RegExp` is match and replace, and
/// both `panic!` with the pattern in the message -- the same answer the
/// backend gives for a method it cannot translate, and for the same reason: a
/// loud failure at the point of use beats a quiet wrong answer, and beats a
/// missing name that stops a thousand lines from compiling.
///
/// Pulling in a regex crate would work and is deliberately not done: the
/// generated crate has no dependencies, which is what makes it possible to say
/// that everything in it came from the Dart or from this file.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RegExp {
    pub pattern: String,
}

impl RegExp {
    pub fn new(pattern: String) -> Self {
        RegExp { pattern }
    }

    pub fn has_match(&self, _input: &str) -> bool {
        panic!("RegExp has no engine here: {}", self.pattern)
    }

    pub fn string_match(&self, _input: &str) -> Option<String> {
        panic!("RegExp has no engine here: {}", self.pattern)
    }

    pub fn all_matches(&self, _input: &str) -> Vec<String> {
        panic!("RegExp has no engine here: {}", self.pattern)
    }
}

/// Dart's error and exception classes.
///
/// One shape for all of them: a message, and a `Display` that prints what Dart
/// prints. They are thrown and caught by *type* upstream, and the `Result<T,
/// E>` the backend emits carries the type, so nothing else about them is
/// reached.
macro_rules! dart_error {
    ($name:ident, $prefix:literal) => {
        #[derive(Clone, Debug, Default, PartialEq, Eq)]
        pub struct $name {
            pub message: String,
        }

        impl $name {
            pub fn new(message: String) -> Self {
                $name { message }
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                if self.message.is_empty() {
                    f.write_str($prefix)
                } else {
                    write!(f, "{}: {}", $prefix, self.message)
                }
            }
        }
    };
}

dart_error!(Exception, "Exception");
dart_error!(StateError, "Bad state");
dart_error!(ArgumentError, "Invalid argument(s)");
dart_error!(UnsupportedError, "Unsupported operation");
dart_error!(UnimplementedError, "UnimplementedError");
dart_error!(FormatException, "FormatException");
dart_error!(AssertionError, "Assertion failed");
dart_error!(ConcurrentModificationError, "Concurrent modification");

/// `RangeError`, which carries the bounds it was given.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct RangeError {
    pub message: String,
    pub start: Option<f64>,
    pub end: Option<f64>,
}

impl RangeError {
    pub fn new(message: String) -> Self {
        RangeError {
            message,
            start: None,
            end: None,
        }
    }

    pub fn range(invalid: f64, min: f64, max: f64) -> Self {
        RangeError {
            message: format!("Invalid value: not in range {}..{}: {}", min, max, invalid),
            start: Some(min),
            end: Some(max),
        }
    }
}

impl fmt::Display for RangeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RangeError: {}", self.message)
    }
}

/// `dart:typed_data`'s fixed-element lists.
///
/// Aliases rather than wrappers: a Dart typed list *is* a list of that element
/// type as far as everything upstream does with it, and an alias keeps every
/// `List` operation the backend already emits working on it.
pub type Uint8List = Vec<u8>;
pub type Int8List = Vec<i8>;
pub type Uint16List = Vec<u16>;
pub type Int16List = Vec<i16>;
pub type Uint32List = Vec<u32>;
pub type Int32List = Vec<i32>;
pub type Uint64List = Vec<u64>;
pub type Int64List = Vec<i64>;
pub type Float32List = Vec<f32>;
pub type Float64List = Vec<f64>;

/// Dart's `ByteData`: a view over bytes with typed accessors.
///
/// Little-endian by default, which is what `Endian.host` is on every platform
/// Flutter ships to. Dart's accessors take an optional `Endian`; the ones that
/// pass one explicitly are not translated yet and will say so rather than
/// silently reading the other way round.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ByteData {
    bytes: Vec<u8>,
}

impl ByteData {
    pub fn new(length: i64) -> Self {
        ByteData {
            bytes: vec![0; length.max(0) as usize],
        }
    }

    pub fn view(bytes: Vec<u8>) -> Self {
        ByteData { bytes }
    }

    pub fn length_in_bytes(&self) -> i64 {
        self.bytes.len() as i64
    }

    pub fn buffer(&self) -> Vec<u8> {
        self.bytes.clone()
    }

    pub fn get_uint8(&self, at: i64) -> i64 {
        self.bytes[at as usize] as i64
    }

    pub fn set_uint8(&mut self, at: i64, value: i64) {
        self.bytes[at as usize] = value as u8;
    }

    pub fn get_int8(&self, at: i64) -> i64 {
        self.bytes[at as usize] as i8 as i64
    }

    pub fn set_int8(&mut self, at: i64, value: i64) {
        self.bytes[at as usize] = value as i8 as u8;
    }

    pub fn get_uint16(&self, at: i64) -> i64 {
        u16::from_le_bytes(self.four(at, 2)[..2].try_into().unwrap()) as i64
    }

    pub fn get_int32(&self, at: i64) -> i64 {
        i32::from_le_bytes(self.four(at, 4)[..4].try_into().unwrap()) as i64
    }

    pub fn set_int32(&mut self, at: i64, value: i64) {
        let at = at as usize;
        self.bytes[at..at + 4].copy_from_slice(&(value as i32).to_le_bytes());
    }

    pub fn get_uint32(&self, at: i64) -> i64 {
        u32::from_le_bytes(self.four(at, 4)[..4].try_into().unwrap()) as i64
    }

    pub fn set_uint32(&mut self, at: i64, value: i64) {
        let at = at as usize;
        self.bytes[at..at + 4].copy_from_slice(&(value as u32).to_le_bytes());
    }

    pub fn get_float32(&self, at: i64) -> f64 {
        f32::from_le_bytes(self.four(at, 4)[..4].try_into().unwrap()) as f64
    }

    pub fn set_float32(&mut self, at: i64, value: f64) {
        let at = at as usize;
        self.bytes[at..at + 4].copy_from_slice(&(value as f32).to_le_bytes());
    }

    pub fn get_float64(&self, at: i64) -> f64 {
        f64::from_le_bytes(self.eight(at)[..8].try_into().unwrap())
    }

    pub fn set_float64(&mut self, at: i64, value: f64) {
        let at = at as usize;
        self.bytes[at..at + 8].copy_from_slice(&value.to_le_bytes());
    }

    fn four(&self, at: i64, n: usize) -> [u8; 4] {
        let at = at as usize;
        let mut out = [0u8; 4];
        out[..n].copy_from_slice(&self.bytes[at..at + n]);
        out
    }

    fn eight(&self, at: i64) -> [u8; 8] {
        let at = at as usize;
        let mut out = [0u8; 8];
        out.copy_from_slice(&self.bytes[at..at + 8]);
        out
    }
}
