use crate::DartAny;

// Generated by tools/dart2rust from upstream `Axis`
// (Dart enum -> Rust enum).

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Axis {
    Horizontal,
    Vertical,
}

// Generated by tools/dart2rust from upstream `MainAxisAlignment`
// (Dart enum -> Rust enum).

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MainAxisAlignment {
    Start,
    End,
    Center,
    SpaceBetween,
    SpaceAround,
}

// Generated by tools/dart2rust from upstream `Season`
// (Dart enum -> Rust enum).

/// Enhanced: it has a method, so translating it as a plain enum would lose one.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Season {
    Spring,
    Summer,
}

impl Season {
    pub fn is_warm(&self) -> bool {
        (*self == Season::Summer)
    }
}

// Generated by tools/dart2rust from upstream `Layout`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Layout {
    pub axis: Axis,
    pub alignment: MainAxisAlignment,
}

impl Layout {
    pub const fn new(axis: Axis, alignment: MainAxisAlignment) -> Self {
        Self {
            axis: axis,
            alignment: alignment,
        }
    }

    pub fn is_horizontal(&self) -> bool {
        (self.axis == Axis::Horizontal)
    }

    /// Reads a value of another enum, so the two do not get confused.
    pub fn is_centred(&self) -> bool {
        (self.alignment == MainAxisAlignment::Center)
    }

    /// A multi-word value, where the renaming actually does something.
    pub fn is_spaced(&self) -> bool {
        (self.alignment == MainAxisAlignment::SpaceBetween)
    }
}

impl DartAny for Layout {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

// Generated by tools/dart2rust from upstream `Tristate`
// (Dart enum -> Rust enum).

/// An **enhanced** enum whose values carry state of their own.
///
/// `none(0)` gives each variant a `value`, and that used to be refused: a Rust
/// enum would need a payload per variant to say the same thing. It would not.
/// The value is a constant *of* the variant, so the Rust is a `match` in a
/// getter -- which is also what makes it free to read.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Tristate {
    None,
    IsTrue,
    IsFalse,
    Quoted,
}

impl Tristate {
    pub fn value(&self) -> i64 {
        match self {
            Tristate::None => 0,
            Tristate::IsTrue => 1,
            Tristate::IsFalse => 2,
            Tristate::Quoted => 3,
        }
    }

    pub fn label(&self) -> String {
        match self {
            Tristate::None => "none".to_string(),
            Tristate::IsTrue => "yes".to_string(),
            Tristate::IsFalse => "no".to_string(),
            Tristate::Quoted => "a \"quoted\" name".to_string(),
        }
    }

    pub fn is_set(&self) -> bool {
        (self.value() > 0)
    }
}

// Generated by tools/dart2rust from upstream `UsesTristate`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct UsesTristate {}

impl UsesTristate {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn weigh(&self, state: Tristate) -> i64 {
        (state.value() * 10)
    }

    /// Names all three values. The Kernel front end recovers an enum's variants
    /// from the *constants* that name them -- the dill keeps no fields for them
    /// -- so a fixture that declares an enum and never uses it tests nothing on
    /// that side, and the two front ends came out 18 lines apart until this
    /// method existed.
    pub fn pick(&self, n: i64) -> Tristate {
        if (n > 0) {
            return Tristate::IsTrue;
        }
        if (n < 0) {
            return Tristate::IsFalse;
        }
        Tristate::None
    }
}

impl DartAny for UsesTristate {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}
