use crate::DartAny;
use crate::RangeError;

// Generated by tools/dart2rust from upstream `Bounds`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Bounds {
    pub limit: f64,
}

impl Bounds {
    pub const fn new(limit: f64) -> Self {
        Self { limit: limit }
    }

    /// Throws directly. Its Rust signature becomes `Result<f32, RangeError>`.
    pub fn checked(&self, value: f64) -> Result<f64, RangeError> {
        if (value > self.limit) {
            return Err(RangeError::new("over the limit".to_string()));
        }
        Ok(value)
    }

    /// Calls one that can fail, so the failure spreads here. Nothing in the Dart
    /// says so -- it is computed.
    pub fn doubled(&self, value: f64) -> Result<f64, RangeError> {
        Ok((self.checked(value)? * 2.0))
    }

    /// Two hops. One pass over the call graph would find `doubled` and miss this,
    /// the same way it did for `&mut self` in round twelve.
    pub fn quadrupled(&self, value: f64) -> Result<f64, RangeError> {
        Ok((self.doubled(value)? * 2.0))
    }

    /// Cannot fail, and must not be given a `Result` it does not need.
    pub fn halved(&self, value: f64) -> f64 {
        (value / 2.0)
    }
}

impl DartAny for Bounds {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}
