use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

pub fn halve(v: f64) -> Result<f64, std::rc::Rc<dyn Object>> {
    Ok((v / 2.0))
}

pub fn thrice(v: f64) -> Result<f64, std::rc::Rc<dyn Object>> {
    Ok((v * 3.0))
}

// Generated by tools/dart2rust from upstream `Gauge`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Gauge {
    pub value: f64,
}

impl Gauge {
    pub const fn new(value: f64) -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({ Self { value: value } })
    }

    pub fn reduced(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Ok(halve(self.value))
    }

    /// A top-level function calling another one, and a class calling both.
    pub fn amplified(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Ok(thrice(halve(self.value)))
    }
}

impl FromDynamic for Gauge {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Gauge {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Gauge was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Gauge was declared")
    }
}

impl DartNullable for Gauge {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Gauge {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Gauge {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Gauge")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Gauge")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}
