use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Pair`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Debug, PartialEq)]
pub struct Pair<
    A: Clone + PartialEq + std::fmt::Debug + 'static,
    B: Clone + PartialEq + std::fmt::Debug + 'static,
> {
    pub first: A,
    pub second: B,
}

impl<
        A: Clone + PartialEq + std::fmt::Debug + 'static,
        B: Clone + PartialEq + std::fmt::Debug + 'static,
    > Pair<A, B>
{
    pub fn new(first: A, second: B) -> Self {
        Self {
            first: first.clone(),
            second: second.clone(),
        }
    }
}

impl<
        A: Clone + PartialEq + std::fmt::Debug + 'static,
        B: Clone + PartialEq + std::fmt::Debug + 'static,
    > DartAny for Pair<A, B>
{
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Pair" }
    }
}

// Generated by tools/dart2rust from upstream `Tagged`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tagged<T: Clone + PartialEq + std::fmt::Debug + 'static> {
    pub count: i64,
    _phantom_t: std::marker::PhantomData<T>,
}

impl<T: Clone + PartialEq + std::fmt::Debug + 'static> Tagged<T> {
    pub const fn new(count: i64) -> Self {
        Self {
            count: count,
            _phantom_t: std::marker::PhantomData,
        }
    }

    pub fn doubled(&self) -> i64 {
        (self.count * 2)
    }
}

impl<T: Clone + PartialEq + std::fmt::Debug + 'static> DartAny for Tagged<T> {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Tagged" }
    }
}

// Generated by tools/dart2rust from upstream `Boxes`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Boxes {}

impl Boxes {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn first_of<T: Clone + PartialEq + std::fmt::Debug + 'static>(&self, mut a: T, b: T) -> T {
        a.clone()
    }

    pub fn made(&self) -> Pair<i64, f64> {
        Pair::<i64, f64>::new(3, 4.5)
    }
}

impl DartAny for Boxes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Boxes" }
    }
}

// Generated by tools/dart2rust from upstream `Store`
// (abstract -> trait).

pub trait Store: DartAny + std::fmt::Debug {
    fn count_of<T: Clone + PartialEq + std::fmt::Debug + 'static>(
        &self,
        items: Vec<T>,
        ignored: T,
    ) -> i64
    where
        Self: Sized;

    fn size(&self) -> i64;
}
impl Object for dyn Store {
    fn as_any(&self) -> &dyn std::any::Any {
        DartAny::as_any(self)
    }
    fn runtime_type(&self) -> Type {
        DartAny::dart_runtime_type(self)
    }
}
impl PartialEq for dyn Store {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Store {}
impl std::hash::Hash for dyn Store {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Shelf`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Shelf {
    pub width: i64,
}

impl Shelf {
    pub const fn new(width: i64) -> Self {
        Self { width: width }
    }

    pub fn count_of<T: Clone + PartialEq + std::fmt::Debug + 'static>(
        &self,
        mut items: Vec<T>,
        ignored: T,
    ) -> i64 {
        ((items.len() as i64) + self.width)
    }

    pub fn size(&self) -> i64 {
        self.width
    }
}

impl DartAny for Shelf {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Shelf" }
    }
}

impl Store for Shelf {
    fn count_of<T: Clone + PartialEq + std::fmt::Debug + 'static>(
        &self,
        items: Vec<T>,
        ignored: T,
    ) -> i64
    where
        Self: Sized,
    {
        Shelf::count_of(self, items, ignored)
    }

    fn size(&self) -> i64 {
        Shelf::size(self)
    }
}

// Generated by tools/dart2rust from upstream `Shelves`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Shelves {}

impl Shelves {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn size_of(mut s: std::rc::Rc<dyn Store>) -> i64 {
        s.size()
    }
}

impl DartAny for Shelves {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Shelves" }
    }
}
