use crate::DartAny;

// Generated by tools/dart2rust from upstream `Node`
// (abstract -> trait).

pub trait Node: DartAny {
    fn id(&self) -> i64;
}

// Generated by tools/dart2rust from upstream `Watcher`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Watcher {
    pub tag: i64,
}

impl Watcher {
    pub fn new(tag: i64) -> std::rc::Rc<Self> {
        std::rc::Rc::new(Self { tag: tag })
    }

    pub fn id(&self) -> i64 {
        self.tag
    }

    pub fn bump(&self) -> () {}

    /// Hands out a closure that calls a method on `this`, so this method's
    /// receiver is `&Rc<Self>` rather than `&Self` -- and `identical(this, ..)`
    /// in the same body has to look through the handle to the object.
    pub fn watching(self: &std::rc::Rc<Self>, other: &dyn Node) -> bool {
        let f: Box<dyn Fn() -> ()> = Box::new({
            let __me = self.clone();
            move || {
                __me.bump();
            }
        });
        (f)();
        std::ptr::eq(
            &**self as *const _ as *const (),
            other as *const _ as *const (),
        )
    }
}

impl DartAny for Watcher {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

impl Node for Watcher {
    fn id(&self) -> i64 {
        Watcher::id(self)
    }
}

// Generated by tools/dart2rust from upstream `Nodes`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Nodes {}

impl Nodes {
    pub const fn new() -> Self {
        Self {}
    }

    /// Two trait objects: both sides are already references.
    pub fn same(a: &dyn Node, b: &dyn Node) -> bool {
        std::ptr::eq(a as *const _ as *const (), b as *const _ as *const ())
    }

    pub fn different(a: &dyn Node, b: &dyn Node) -> bool {
        (!std::ptr::eq(a as *const _ as *const (), b as *const _ as *const ()))
    }
}

impl DartAny for Nodes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}
