use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Node`
// (abstract -> trait).

pub trait Node: DartAny + std::fmt::Debug {
    fn id(&self) -> i64;
}
impl Object for dyn Node {
    fn as_any(&self) -> &dyn std::any::Any {
        DartAny::as_any(self)
    }
    fn runtime_type(&self) -> Type {
        DartAny::dart_runtime_type(self)
    }
}
impl PartialEq for dyn Node {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Node {}
impl std::hash::Hash for dyn Node {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Watcher`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Watcher {
    pub tag: i64,
}

impl Watcher {
    pub fn new(tag: i64) -> std::rc::Rc<Self> {
        std::rc::Rc::new(Self { tag: tag })
    }

    pub fn id(&self) -> i64 {
        self.tag
    }

    pub fn bump(&self) -> () {}

    pub fn watching(self: &std::rc::Rc<Self>, other: std::rc::Rc<dyn Node>) -> bool {
        let f: std::rc::Rc<dyn Fn() -> ()> = std::rc::Rc::new({
            let __me = self.clone();
            move || {
                __me.bump();
            }
        });
        (f)();
        std::ptr::eq(
            &**self as *const _ as *const (),
            std::rc::Rc::as_ptr(&other) as *const u8 as *const (),
        )
    }
}

impl DartAny for Watcher {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Watcher" }
    }
}

impl Node for Watcher {
    fn id(&self) -> i64 {
        Watcher::id(self)
    }
}

// Generated by tools/dart2rust from upstream `Nodes`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Nodes {}

impl Nodes {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn same(a: std::rc::Rc<dyn Node>, b: std::rc::Rc<dyn Node>) -> bool {
        std::ptr::eq(
            std::rc::Rc::as_ptr(&a) as *const u8 as *const (),
            std::rc::Rc::as_ptr(&b) as *const u8 as *const (),
        )
    }

    pub fn different(a: std::rc::Rc<dyn Node>, b: std::rc::Rc<dyn Node>) -> bool {
        (!std::ptr::eq(
            std::rc::Rc::as_ptr(&a) as *const u8 as *const (),
            std::rc::Rc::as_ptr(&b) as *const u8 as *const (),
        ))
    }
}

impl DartAny for Nodes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Nodes" }
    }
}
