// Generated by tools/dart2rust from upstream `Engine`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// Something to be `late` about that is not `Copy`, so a read cannot just take
/// the value out.
#[derive(Clone, Debug, PartialEq)]
pub struct Engine {
    pub name: String,
}

impl Engine {
    pub const fn new(name: String) -> Self {
        Self { name: name }
    }

    pub fn run(&self, x: f64) -> f64 {
        (x * 2.0)
    }
}

// Generated by tools/dart2rust from upstream `Machine`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Debug, PartialEq)]
pub struct Machine {
    /// A `Copy` one: the read takes the value out whole, which is what a field
    /// read does anyway.
    pub steps: Option<i64>,
    /// A `late final`: assigned once, and never again. Still `Option<T>` -- what
    /// `final` promises is one write, not an early one.
    pub engine: Option<Engine>,
}

impl Machine {
    pub fn new() -> Self {
        Self {
            steps: None,
            engine: None,
        }
    }

    pub fn start(&mut self, e: Engine) -> () {
        self.engine = Some(e);
        self.steps = Some(0);
    }

    /// Reads both kinds in one body: the reference one through `as_ref`, the
    /// value one by unwrapping the `Option` itself.
    pub fn advance(&mut self, x: f64) -> f64 {
        self.steps = Some((self.steps.unwrap() + 1));
        self.engine.as_ref().unwrap().run(x)
    }

    pub fn taken(&self) -> i64 {
        self.steps.unwrap()
    }

    /// A read that only borrows, which is the common case: a method call and a
    /// field read on the thing that was `late`.
    pub fn describe(&self) -> String {
        format!(
            "ran {} {} times",
            self.engine.as_ref().unwrap().name,
            self.steps.unwrap()
        )
    }
}
