use crate::dart_iter;
use crate::dart_prelude::*;
use crate::dart_str;
use crate::DartAny;
use crate::Isolate;
use crate::Map;
use crate::Type;

// Generated by tools/dart2rust from upstream `Marks`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Debug, PartialEq)]
pub struct Marks {
    pub marks: Vec<i64>,
    pub notes: Map<String, i64>,
}

impl Marks {
    pub fn new(marks: Vec<i64>) -> Self {
        Self {
            marks: marks.clone(),
            notes: Map::from([]),
        }
    }

    // NOT TRANSLATED: Marks.fixed
    //   unsupported a `const` cannot hold a collection: Marks.fixed

    pub fn total(&self) -> i64 {
        let mut sum: i64 = 0;
        let mut i: i64 = 0;
        while (i < (self.marks.clone().len() as i64)) {
            sum = (sum + self.marks.clone()[i as usize].clone());
            i = (i + 1);
        }
        sum
    }

    pub fn doubled_total(&self) -> i64 {
        let mut sum: i64 = 0;
        let __t0 = dart_iter(self.marks.clone().clone());
        for mark in self.marks.clone().iter().cloned() {
            sum = (sum + (mark * 2));
        }
        sum
    }

    pub fn note(&mut self, mark: i64) -> () {
        self.marks.clone().push(mark);
    }

    pub fn overwrite_first(&mut self, mark: i64) -> () {
        {
            let __i = 0 as usize;
            self.marks[__i] = mark;
        }
    }

    pub fn empty(&self) -> bool {
        self.marks.clone().is_empty()
    }

    pub fn starting() -> Vec<i64> {
        vec![3, 11, 29]
    }

    pub fn any(&self) -> bool {
        !self.marks.clone().is_empty()
    }

    pub fn highest(&self) -> i64 {
        self.marks.clone()[self.marks.clone().len() - 1]
    }

    pub fn lowest(&self) -> i64 {
        self.marks.clone()[0].clone()
    }

    pub fn tripled(&self) -> Vec<i64> {
        self.marks
            .clone()
            .iter()
            .map(|m| (m * 3))
            .collect::<Vec<_>>()
    }

    pub fn defaults_total() -> i64 {
        let mut sum: i64 = 0;
        let __t1 = dart_iter((**MARKS_DEFAULTS).clone().clone());
        for d in (**MARKS_DEFAULTS).clone().iter().cloned() {
            sum = (sum + d);
        }
        sum
    }

    pub fn span() -> (i64, i64) {
        (3, 29)
    }

    pub fn span_width() -> i64 {
        let s: (i64, i64) = Marks::span();
        (s.1 - s.0)
    }

    pub fn sizes() -> Map<String, i64> {
        Map::from([("small".to_string(), 4), ("large".to_string(), 40)])
    }

    pub fn look_up(mut sizes: Map<String, i64>, mut name: String) -> i64 {
        if sizes.contains_key(&name.clone()) {
            return sizes.get(&name.clone()).cloned().unwrap();
        }
        (-1)
    }
}

impl DartAny for Marks {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Marks" }
    }
}
pub static MARKS_DEFAULTS: std::sync::LazyLock<Isolate<Vec<i64>>> =
    std::sync::LazyLock::new(|| Isolate(vec![5, 13]));

// Generated by tools/dart2rust from upstream `Members`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Members {}

impl Members {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn any_over(mut xs: Vec<i64>, limit: i64) -> bool {
        xs.iter().cloned().any(|x| (x > limit))
    }

    pub fn all_over(mut xs: Vec<i64>, limit: i64) -> bool {
        xs.iter().cloned().all(|x| (x > limit))
    }

    pub fn joined(mut xs: Vec<String>) -> String {
        xs.iter()
            .map(|__e| dart_str(__e))
            .collect::<Vec<_>>()
            .join(&"-".to_string())
    }

    pub fn run(mut xs: Vec<String>) -> String {
        xs.iter()
            .map(|__e| dart_str(__e))
            .collect::<Vec<_>>()
            .join("")
    }

    pub fn with_inserted(mut xs: Vec<i64>, at: i64, value: i64) -> Vec<i64> {
        xs.insert(at as usize, value);
        xs.clone()
    }

    pub fn taken_out(mut xs: Vec<i64>, at: i64) -> i64 {
        xs.remove(at as usize)
    }

    pub fn nth(mut xs: Vec<i64>, at: i64) -> i64 {
        xs[at as usize]
    }

    pub fn middle(mut xs: Vec<i64>, from: i64, to: i64) -> Vec<i64> {
        xs[from as usize..to as usize].to_vec()
    }

    pub fn tail(mut xs: Vec<i64>, from: i64) -> Vec<i64> {
        xs[from as usize..].to_vec()
    }

    pub fn backwards(mut xs: Vec<i64>) -> Vec<i64> {
        {
            let mut __r = xs.clone();
            __r.reverse();
            __r
        }
        .clone()
    }

    pub fn has_any(mut m: Map<String, i64>) -> bool {
        !m.is_empty()
    }
}

impl DartAny for Members {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Members" }
    }
}

// Generated by tools/dart2rust from upstream `Ordered`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Ordered {}

impl Ordered {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn built() -> Map<String, i64> {
        let mut m: Map<String, i64> = Map::from([]);
        m.insert("b".to_string(), 2);
        m.insert("a".to_string(), 1);
        m.insert("c".to_string(), 3);
        m.clone()
    }

    pub fn names_of(mut m: Map<String, i64>) -> Vec<String> {
        m.keys().clone()
    }

    pub fn values_of(mut m: Map<String, i64>) -> Vec<i64> {
        m.values().clone()
    }

    pub fn total(mut m: Map<String, i64>) -> i64 {
        let sum: std::rc::Rc<std::cell::Cell<i64>> = std::rc::Rc::new(std::cell::Cell::new(0));
        m.for_each({
            let sum = sum.clone();
            move |k: String, v: i64| {
                sum.set((sum.get() + v));
            }
        });
        sum.get()
    }

    pub fn seeded(mut m: Map<String, i64>, mut name: String) -> i64 {
        m.put_if_absent(name.clone(), || 9)
    }
}

impl DartAny for Ordered {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Ordered" }
    }
}
