use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Isolate;
use crate::Map;
use crate::Set;
use crate::Type;

// Generated by tools/dart2rust from upstream `Marks`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Debug, PartialEq)]
pub struct Marks {
    pub marks: Vec<i64>,
    /// A map in a field, which is what stops the class being `Copy`.
    pub notes: Map<String, i64>,
}

impl Marks {
    pub fn new(marks: Vec<i64>) -> Result<Self, std::rc::Rc<dyn Object>> {
        dart_register::<Self>();
        Ok({
            Self {
                marks: marks,
                notes: Map::<String, i64>::from_pairs([]),
            }
        })
    }

    // NOT TRANSLATED: Marks.fixed
    //   unsupported a `const` cannot hold a collection: Marks.fixed

    pub fn total(&self) -> Result<i64, std::rc::Rc<dyn Object>> {
        let mut sum: i64 = 0;
        let mut i: i64 = 0;
        while (i < (self.marks.clone().len() as i64)) {
            sum = (sum + self.marks.clone()[i as usize].clone());
            i = (i + 1);
        }
        Ok(sum)
    }

    /// `for (final x in xs)`. The CFE writes this as an iterator loop -- bind
    /// `xs.iterator`, loop while `moveNext()`, read `current` -- and 405 of
    /// upstream's 592 `for` statements are really this shape. Put back together
    /// rather than carried across in pieces, so both front ends land on Rust's
    /// own `for x in &xs`.
    pub fn doubled_total(&self) -> Result<i64, std::rc::Rc<dyn Object>> {
        let mut sum: i64 = 0;
        for mark in self.marks.clone().iter().cloned() {
            sum = (sum + (mark * 2));
        }
        Ok(sum)
    }

    pub fn note(&mut self, mark: i64) -> Result<(), std::rc::Rc<dyn Object>> {
        self.marks.push(mark);
        Ok(())
    }

    pub fn overwrite_first(&mut self, mark: i64) -> Result<(), std::rc::Rc<dyn Object>> {
        {
            let __i = 0 as usize;
            self.marks[__i] = mark;
        }
        Ok(())
    }

    pub fn empty(&self) -> Result<bool, std::rc::Rc<dyn Object>> {
        Ok(self.marks.clone().is_empty())
    }

    /// A list literal, with its element type coming from the declaration rather
    /// than from the elements -- an empty one still has to know what it holds.
    pub fn starting() -> Result<Vec<i64>, std::rc::Rc<dyn Object>> {
        Ok(vec![3, 11, 29])
    }

    pub fn any(&self) -> Result<bool, std::rc::Rc<dyn Object>> {
        Ok(!self.marks.clone().is_empty())
    }

    pub fn highest(&self) -> Result<i64, std::rc::Rc<dyn Object>> {
        Ok(self.marks.clone()[self.marks.clone().len() - 1].clone())
    }

    pub fn lowest(&self) -> Result<i64, std::rc::Rc<dyn Object>> {
        Ok(self.marks.clone()[0].clone())
    }

    /// A chain that is collected right there. Dart's `map` and Rust's are only
    /// the same when the chain ends -- `xs.iter().map(f)` is lazy and its
    /// elements are references -- so the whole chain is recognised at once. 72
    /// of upstream's 126 such calls are collected like this; the 54 that escape
    /// as a lazy Iterable are refused.
    pub fn tripled(&self) -> Result<Vec<i64>, std::rc::Rc<dyn Object>> {
        Ok(self
            .marks
            .clone()
            .iter()
            .map(|__p_m| {
                let m = (*__p_m).clone();
                (m * 3)
            })
            .collect::<Vec<_>>())
    }

    pub fn defaults_total() -> Result<i64, std::rc::Rc<dyn Object>> {
        let mut sum: i64 = 0;
        for d in (**MARKS_DEFAULTS).clone().iter().cloned() {
            sum = (sum + d);
        }
        Ok(sum)
    }

    /// A record, which is a Rust tuple. Positional only: a named field would
    /// need a struct with a name, and there is no name to give it.
    pub fn span() -> Result<(i64, i64), std::rc::Rc<dyn Object>> {
        Ok((3, 29))
    }

    /// Reading a record's fields back. Dart counts them from one and Rust
    /// counts tuple fields from zero.
    pub fn span_width() -> Result<i64, std::rc::Rc<dyn Object>> {
        let s: (i64, i64) = Marks::span();
        Ok((s.1.clone() - s.0.clone()))
    }

    /// A map literal. `HashMap::from([..])`, which is safe because the members
    /// that would need the insertion order are refused wherever they are used.
    pub fn sizes() -> Result<Map<String, i64>, std::rc::Rc<dyn Object>> {
        Ok(Map::<String, i64>::from_pairs([
            ("small".to_string(), 4),
            ("large".to_string(), 40),
        ]))
    }

    /// A lookup-only map. `keys`, `values`, `entries` and `forEach` are refused
    /// because a Dart map iterates in insertion order and a `HashMap` does not,
    /// which would quietly reorder 109 places upstream.
    pub fn look_up(
        mut sizes: Map<String, i64>,
        name: String,
    ) -> Result<i64, std::rc::Rc<dyn Object>> {
        if sizes.contains_key(&name) {
            return Ok(sizes.get(name).unwrap());
        }
        Ok((-1))
    }
}

impl FromDynamic for Marks {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Marks {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Marks was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Marks was declared")
    }
}

impl DartNullable for Marks {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Marks {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Marks {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Marks")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Marks")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}
/// A `static final`: computed once on first use, which is what Rust's
/// `LazyLock` is. It goes at *module* scope, because an `impl` block may
/// hold a `const` and not a `static`, and its name carries the class so two
/// classes' `defaults` cannot collide.
pub static MARKS_DEFAULTS: std::sync::LazyLock<Isolate<Vec<i64>>> =
    std::sync::LazyLock::new(|| Isolate(vec![5, 13]));

// Generated by tools/dart2rust from upstream `Members`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// The `List` and `Map` members Rust says differently rather than renames.
///
/// Measured rather than guessed at: 232 refusals named a `List` member and 22
/// a `Map` one, and the ones here are the ones whose Rust is exact. `sort`
/// takes a comparator returning an `int` where Rust wants an `Ordering`, and
/// `forEach` hands its closure a value where `iter()` hands it a reference --
/// those are not renames and are still refused.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Members {}

impl Members {
    pub const fn new() -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({ Self {} })
    }

    pub fn any_over(mut xs: Vec<i64>, limit: i64) -> Result<bool, std::rc::Rc<dyn Object>> {
        Ok(xs.iter().cloned().any(|x| (x > limit)))
    }

    pub fn all_over(mut xs: Vec<i64>, limit: i64) -> Result<bool, std::rc::Rc<dyn Object>> {
        Ok(xs.iter().cloned().all(|x| (x > limit)))
    }

    pub fn joined(mut xs: Vec<String>) -> Result<String, std::rc::Rc<dyn Object>> {
        Ok(xs
            .iter()
            .map(|__e| dart_object_str(__e.clone()))
            .collect::<Vec<_>>()
            .join(&"-".to_string()))
    }

    pub fn run(mut xs: Vec<String>) -> Result<String, std::rc::Rc<dyn Object>> {
        Ok(xs
            .iter()
            .map(|__e| dart_object_str(__e.clone()))
            .collect::<Vec<_>>()
            .join(""))
    }

    pub fn with_inserted(
        mut xs: Vec<i64>,
        at: i64,
        value: i64,
    ) -> Result<Vec<i64>, std::rc::Rc<dyn Object>> {
        xs.insert(at as usize, value);
        Ok(xs)
    }

    pub fn taken_out(mut xs: Vec<i64>, at: i64) -> Result<i64, std::rc::Rc<dyn Object>> {
        Ok(xs.remove(at as usize))
    }

    pub fn nth(mut xs: Vec<i64>, at: i64) -> Result<i64, std::rc::Rc<dyn Object>> {
        Ok(xs[at as usize].clone())
    }

    pub fn middle(
        mut xs: Vec<i64>,
        from: i64,
        to: i64,
    ) -> Result<Vec<i64>, std::rc::Rc<dyn Object>> {
        Ok(xs[from as usize..to as usize].to_vec())
    }

    pub fn tail(mut xs: Vec<i64>, from: i64) -> Result<Vec<i64>, std::rc::Rc<dyn Object>> {
        Ok(xs[from as usize..].to_vec())
    }

    pub fn backwards(mut xs: Vec<i64>) -> Result<Vec<i64>, std::rc::Rc<dyn Object>> {
        Ok({
            let mut __r = xs.clone();
            __r.reverse();
            __r
        }
        .clone())
    }

    /// `Map.isNotEmpty` was on the `List` map and not the `Map` one, which is
    /// the same shape as every other "and the other half?" in this compiler.
    pub fn has_any(mut m: Map<String, i64>) -> Result<bool, std::rc::Rc<dyn Object>> {
        Ok(!m.is_empty())
    }
}

impl FromDynamic for Members {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Members {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Members was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Members was declared")
    }
}

impl DartNullable for Members {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Members {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Members {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Members")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Members")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}

// Generated by tools/dart2rust from upstream `Ordered`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// A `Map` that keeps the order things were put in.
///
/// Dart's map literal is a `LinkedHashMap` and its `keys`, `values`, `entries`
/// and `forEach` walk in insertion order. `std::collections::HashMap` does
/// not, so those five were refused -- 97 across the package -- rather than
/// reorder anything quietly. The prelude's `Map` is a `Vec` of pairs now, the
/// same trade `Set<T>` next door had already made.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Ordered {}

impl Ordered {
    pub const fn new() -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({ Self {} })
    }

    /// Not alphabetical, and not hash order either: `b`, `a`, `c`.
    pub fn built() -> Result<Map<String, i64>, std::rc::Rc<dyn Object>> {
        let mut m: Map<String, i64> = Map::<String, i64>::from_pairs([]);
        m.insert("b".to_string(), 2);
        m.insert("a".to_string(), 1);
        m.insert("c".to_string(), 3);
        Ok(m)
    }

    pub fn names_of(mut m: Map<String, i64>) -> Result<Vec<String>, std::rc::Rc<dyn Object>> {
        Ok(m.keys().clone())
    }

    pub fn values_of(mut m: Map<String, i64>) -> Result<Vec<i64>, std::rc::Rc<dyn Object>> {
        Ok(m.values().clone())
    }

    pub fn total(mut m: Map<String, i64>) -> Result<i64, std::rc::Rc<dyn Object>> {
        let mut sum: i64 = 0;
        m.for_each(|k: String, v: i64| -> Result<_, std::rc::Rc<dyn Object>> {
            sum = (sum + v);
            Ok(())
        })?;
        Ok(sum)
    }

    /// Gives back what is there afterwards, either way.
    pub fn seeded(mut m: Map<String, i64>, name: String) -> Result<i64, std::rc::Rc<dyn Object>> {
        Ok(m.put_if_absent(name, || -> Result<_, std::rc::Rc<dyn Object>> { Ok(9) })?)
    }
}

impl FromDynamic for Ordered {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Ordered {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Ordered was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Ordered was declared")
    }
}

impl DartNullable for Ordered {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Ordered {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Ordered {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Ordered")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Ordered")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}
