// Generated by tools/dart2rust from upstream `Marks`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Debug, PartialEq)]
pub struct Marks {
    pub marks: Vec<i64>,
}

impl Marks {
    pub fn new(marks: Vec<i64>) -> Self {
        Self { marks: marks }
    }

    pub fn total(&self) -> i64 {
        let mut sum: i64 = 0;
        let mut i: i64 = 0;
        while (i < (self.marks.len() as i64)) {
            sum = (sum + self.marks[i as usize]);
            i = (i + 1);
        }
        sum
    }

    /// `for (final x in xs)`. The CFE writes this as an iterator loop -- bind
    /// `xs.iterator`, loop while `moveNext()`, read `current` -- and 405 of
    /// upstream's 592 `for` statements are really this shape. Put back together
    /// rather than carried across in pieces, so both front ends land on Rust's
    /// own `for x in &xs`.
    pub fn doubled_total(&self) -> i64 {
        let mut sum: i64 = 0;
        for mark in &self.marks {
            sum = (sum + (mark * 2));
        }
        sum
    }

    pub fn note(&mut self, mark: i64) -> () {
        self.marks.push(mark);
    }

    pub fn overwrite_first(&mut self, mark: i64) -> () {
        self.marks[0 as usize] = mark;
    }

    pub fn empty(&self) -> bool {
        self.marks.is_empty()
    }

    /// A list literal, with its element type coming from the declaration rather
    /// than from the elements -- an empty one still has to know what it holds.
    pub fn starting() -> Vec<i64> {
        vec![3, 11, 29]
    }

    pub fn any(&self) -> bool {
        !self.marks.is_empty()
    }

    pub fn highest(&self) -> i64 {
        self.marks[self.marks.len() - 1]
    }

    pub fn lowest(&self) -> i64 {
        self.marks[0]
    }

    /// A chain that is collected right there. Dart's `map` and Rust's are only
    /// the same when the chain ends -- `xs.iter().map(f)` is lazy and its
    /// elements are references -- so the whole chain is recognised at once. 72
    /// of upstream's 126 such calls are collected like this; the 54 that escape
    /// as a lazy Iterable are refused.
    pub fn tripled(&self) -> Vec<i64> {
        self.marks.iter().map(|m| (m * 3)).collect::<Vec<_>>()
    }

    /// A lookup-only map. `keys`, `values`, `entries` and `forEach` are refused
    /// because a Dart map iterates in insertion order and a `HashMap` does not,
    /// which would quietly reorder 109 places upstream.
    pub fn look_up(sizes: std::collections::HashMap<String, i64>, name: String) -> i64 {
        if sizes.contains_key(&name) {
            return sizes.get(&name).cloned().unwrap();
        }
        (-1)
    }
}
