use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Rung`
// (abstract -> trait).

pub trait Rung: DartAny + std::fmt::Debug {
    fn steps(&self) -> i64;
}
impl Object for dyn Rung {
    fn as_any(&self) -> &dyn std::any::Any {
        DartAny::as_any(self)
    }
    fn runtime_type(&self) -> Type {
        DartAny::dart_runtime_type(self)
    }
}
impl PartialEq for dyn Rung {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Rung {}
impl std::hash::Hash for dyn Rung {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Ladder`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Ladder {
    pub steps: i64,
}

impl Ladder {
    pub const fn new(steps: i64) -> Self {
        Self { steps: steps }
    }

    pub fn climbed(&self) -> f64 {
        let mut total: f64 = 0.0;
        let mut i: i64 = 0;
        while (i < self.steps) {
            total = (total + (i as f64));
            i = (i + 1);
        }
        total
    }

    pub fn climbed_the_long_way(&self) -> f64 {
        let mut total: f64 = 0.0;
        let mut i: i64 = 0;
        while (i < self.steps) {
            total = (total + (i as f64));
            i = (i + 1);
        }
        total
    }

    pub fn paired(&self) -> f64 {
        let mut total: f64 = 0.0;
        let mut i: i64 = 0;
        let j: i64 = 10;
        while (i < j) {
            total = (total + 1.0);
            if (total > 3.0) {
                return total;
            }
            i = (i + 1);
        }
        total
    }

    pub fn is_the(&self, other: std::rc::Rc<dyn Rung>) -> bool {
        std::ptr::eq(
            self as *const _ as *const (),
            std::rc::Rc::as_ptr(&other) as *const u8 as *const (),
        )
    }

    // NOT TRANSLATED: Ladder.isTheCopy
    //   unsupported `identical` on something that is not a reference: other
}

impl DartAny for Ladder {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Ladder" }
    }
}

impl Rung for Ladder {
    fn steps(&self) -> i64 {
        todo!("Ladder does not translate steps yet")
    }
}
