use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Measured`
// (abstract -> trait).

/// The body of `Measured.base`, reachable from an
/// override the way Dart's `super.base` is.
pub fn measured_super_base<__Self: Measured + ?Sized + 'static>(
    this_: &__Self,
) -> Result<f64, std::rc::Rc<dyn Object>> {
    Ok(2.0)
}

impl DartEq for dyn Measured {
    fn dart_eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self as *const Self, other as *const Self)
    }
    fn dart_hash_code(&self) -> i64 {
        (self as *const Self as *const u8 as usize as i64) & 0x3fff_ffff
    }
}

pub trait Measured: DartAny + std::fmt::Debug {
    fn dart_self_measured(&self) -> std::rc::Rc<dyn Measured>;

    fn base(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        measured_super_base(self)
    }
}
impl PartialEq for dyn Measured {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Measured {}
impl std::hash::Hash for dyn Measured {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Scaled`
// (abstract -> trait).

/// An `abstract mixin class` rather than a bare `mixin`: a `mixin`
/// declaration is not a class in the analyzer's AST and this compiler does not
/// lower one yet, so a fixture using it would be testing that hole instead of
/// this one. Abstract because that is what a mixin declaration is in Kernel,
/// and because only an abstract class emits the free functions a `super` call
/// names -- a concrete base has no trait for one to be generic over.

/// The body of `Scaled.scale`, reachable from an
/// override the way Dart's `super.scale` is.
pub fn scaled_super_scale<__Self: Scaled + ?Sized + 'static>(
    this_: &__Self,
) -> Result<f64, std::rc::Rc<dyn Object>> {
    Ok(3.0)
}

/// The body of `Scaled.base`, reachable from an
/// override the way Dart's `super.base` is.
pub fn scaled_super_base<__Self: Scaled + ?Sized + 'static>(
    this_: &__Self,
) -> Result<f64, std::rc::Rc<dyn Object>> {
    Ok(5.0)
}

impl DartEq for dyn Scaled {
    fn dart_eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self as *const Self, other as *const Self)
    }
    fn dart_hash_code(&self) -> i64 {
        (self as *const Self as *const u8 as usize as i64) & 0x3fff_ffff
    }
}

pub trait Scaled: DartAny + std::fmt::Debug {
    fn dart_self_scaled(&self) -> std::rc::Rc<dyn Scaled>;

    fn scale(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        scaled_super_scale(self)
    }

    fn base(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        scaled_super_base(self)
    }
}
impl PartialEq for dyn Scaled {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Scaled {}
impl std::hash::Hash for dyn Scaled {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Panel`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Panel {}

impl Panel {
    pub const fn new() -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({ Self {} })
    }

    /// `base` is declared by the mixin, not by `Measured`. The `extends` clause
    /// says `Measured`, and answering from it would call the wrong body.
    pub fn from_mixin(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Ok(scaled_super_base(self)?)
    }

    /// Declared only by the mixin, so there is nothing else it could mean.
    pub fn from_mixin_only(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Ok(scaled_super_scale(self)?)
    }
}

impl FromDynamic for Panel {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Panel {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Panel was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Panel was declared")
    }
}

impl DartNullable for Panel {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Panel {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Panel {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Panel")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Panel")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        if __t == std::any::TypeId::of::<dyn Measured>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Measured>>()
        {
            return Some(std::boxed::Box::new(self.dart_self_measured()));
        }
        if __t == std::any::TypeId::of::<dyn Scaled>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Scaled>>()
        {
            return Some(std::boxed::Box::new(self.dart_self_scaled()));
        }
        None
    }
}

impl Measured for Panel {
    fn dart_self_measured(&self) -> std::rc::Rc<dyn Measured> {
        std::rc::Rc::new(self.clone())
    }

    fn base(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Scaled::base(self)
    }
}

impl Scaled for Panel {
    fn dart_self_scaled(&self) -> std::rc::Rc<dyn Scaled> {
        std::rc::Rc::new(self.clone())
    }
}
