use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Measured`
// (abstract -> trait).

/// The body of `Measured.base`, reachable from an
/// override the way Dart's `super.base` is.
pub fn measured_super_base<__Self: Measured + ?Sized + 'static>(this_: &__Self) -> f64 {
    2.0
}

pub trait Measured: DartAny + std::fmt::Debug {
    fn base(&self) -> f64 {
        measured_super_base(self)
    }
}
impl Object for dyn Measured {
    fn as_any(&self) -> &dyn std::any::Any {
        DartAny::as_any(self)
    }
    fn runtime_type(&self) -> Type {
        DartAny::dart_runtime_type(self)
    }
}
impl PartialEq for dyn Measured {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Measured {}
impl std::hash::Hash for dyn Measured {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Scaled`
// (abstract -> trait).

/// The body of `Scaled.scale`, reachable from an
/// override the way Dart's `super.scale` is.
pub fn scaled_super_scale<__Self: Scaled + ?Sized + 'static>(this_: &__Self) -> f64 {
    3.0
}

/// The body of `Scaled.base`, reachable from an
/// override the way Dart's `super.base` is.
pub fn scaled_super_base<__Self: Scaled + ?Sized + 'static>(this_: &__Self) -> f64 {
    5.0
}

pub trait Scaled: DartAny + std::fmt::Debug {
    fn scale(&self) -> f64 {
        scaled_super_scale(self)
    }

    fn base(&self) -> f64 {
        scaled_super_base(self)
    }
}
impl Object for dyn Scaled {
    fn as_any(&self) -> &dyn std::any::Any {
        DartAny::as_any(self)
    }
    fn runtime_type(&self) -> Type {
        DartAny::dart_runtime_type(self)
    }
}
impl PartialEq for dyn Scaled {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Scaled {}
impl std::hash::Hash for dyn Scaled {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Panel`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Panel {}

impl Panel {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn from_mixin(&self) -> f64 {
        scaled_super_base(self)
    }

    pub fn from_mixin_only(&self) -> f64 {
        scaled_super_scale(self)
    }

    pub fn scale(&self) -> f64 {
        3.0
    }

    pub fn base(&self) -> f64 {
        5.0
    }
}

impl DartAny for Panel {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Panel" }
    }
}

impl Measured for Panel {
    fn base(&self) -> f64 {
        Panel::base(self)
    }
}

impl Scaled for Panel {
    fn scale(&self) -> f64 {
        Panel::scale(self)
    }

    fn base(&self) -> f64 {
        Panel::base(self)
    }
}
