use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `NamedArgs`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct NamedArgs {
    pub a: f64,
    pub b: f64,
    pub c: f64,
}

impl NamedArgs {
    pub const fn new(a: f64, b: f64, c: f64) -> Self {
        Self { a: a, b: b, c: c }
    }

    pub fn weigh(&self, first: f64, second: f64, third: f64) -> f64 {
        (((self.a * first) + (self.b * second)) + (self.c * third))
    }

    pub fn out_of_order(&self) -> f64 {
        self.weigh(1.0, 10.0, 100.0)
    }

    pub fn with_omission(&self) -> f64 {
        self.weigh(1.0, 2.0, 1.0)
    }

    pub fn all_defaults(&self) -> f64 {
        self.weigh(1.0, 2.0, 4.0)
    }
}

impl DartAny for NamedArgs {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "NamedArgs" }
    }
}
