// Generated by tools/dart2rust from upstream `Maybe`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Maybe {
    pub value: Option<f64>,
    pub other: Option<f64>,
}

impl Maybe {
    pub const fn new(value: Option<f64>, other: Option<f64>) -> Self {
        Self {
            value: value,
            other: other,
        }
    }

    pub fn is_missing(&self) -> bool {
        self.value.is_none()
    }

    /// `!=`, which Kernel wraps in a negation.
    pub fn is_present(&self) -> bool {
        (!self.value.is_none())
    }

    /// `null` on the left, which Dart allows and which reads the same.
    pub fn missing_on_the_left(&self) -> bool {
        self.other.is_none()
    }

    /// Two of them, so an implementation that only looked at the first would be
    /// caught.
    pub fn both_missing(&self) -> bool {
        (self.value.is_none() && self.other.is_none())
    }

    /// A null test guarding a null assertion -- the shape upstream uses most.
    pub fn resolve(&self, fallback: f64) -> f64 {
        if self.value.is_none() {
            return fallback;
        }
        self.value.unwrap()
    }
}
