use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `NullCheck`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct NullCheck {
    pub maybe: Option<f64>,
    pub other: Option<f64>,
}

impl NullCheck {
    pub const fn new(maybe: Option<f64>, other: Option<f64>) -> Self {
        Self {
            maybe: maybe,
            other: other,
        }
    }

    pub fn doubled(&self) -> f64 {
        (self.maybe.unwrap() * 2.0)
    }

    pub fn summed(&self) -> f64 {
        (self.maybe.unwrap() + self.other.unwrap())
    }

    pub fn via_call(&self) -> f64 {
        (self.pick(true).unwrap() + self.pick(false).unwrap())
    }

    pub fn pick(&self, first: bool) -> Option<f64> {
        if first {
            return self.maybe;
        }
        self.other
    }

    pub fn with_fallback(&self, fallback: f64) -> f64 {
        (match self.other {
            Some(__value) => __value,
            None => fallback,
        } + self.maybe.unwrap())
    }
}

impl DartAny for NullCheck {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "NullCheck" }
    }
}
