// Generated by tools/dart2rust from upstream `NullCheck`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct NullCheck {
    pub maybe: Option<f64>,
    pub other: Option<f64>,
}

impl NullCheck {
    pub const fn new(maybe: Option<f64>, other: Option<f64>) -> Self {
        Self {
            maybe: maybe,
            other: other,
        }
    }

    /// The plain case.
    pub fn doubled(&self) -> f64 {
        (self.maybe.unwrap() * 2.0)
    }

    /// Two of them in one expression, so an implementation that unwrapped only
    /// the first would still be caught.
    pub fn summed(&self) -> f64 {
        (self.maybe.unwrap() + self.other.unwrap())
    }

    /// `!` on the *result* of something, not on a field.
    pub fn via_call(&self) -> f64 {
        (self.pick(true).unwrap() + self.pick(false).unwrap())
    }

    pub fn pick(&self, first: bool) -> Option<f64> {
        if first {
            return self.maybe;
        }
        self.other
    }

    /// A null-aware fallback beside a `!`, so the two are not confused: `??`
    /// supplies a default, `!` insists there is no need for one.
    pub fn with_fallback(&self, fallback: f64) -> f64 {
        (self.other.unwrap_or_else(|| fallback) + self.maybe.unwrap())
    }
}
