use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Label`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Debug, PartialEq)]
pub struct Label {
    pub name: String,
    pub count: i64,
}

impl Label {
    pub fn new(name: String, count: i64) -> Self {
        Self {
            name: name.clone(),
            count: count,
        }
    }

    pub fn twice(x: f64) -> f64 {
        (x * 2.0)
    }

    pub fn describe(&self) -> String {
        format!("{} has {}", self.name.clone(), self.count)
    }

    pub fn braced(&self) -> String {
        format!("{{{}}}", self.name.clone())
    }

    pub fn doubled(&self, x: f64) -> f64 {
        let f: std::rc::Rc<dyn Fn(f64) -> f64> = std::rc::Rc::new(Label::twice);
        (f)(x)
    }

    pub fn stepped(&self, x: f64) -> f64 {
        let step = |v: f64| (v + 1.0);
        (step)((step)(x))
    }

    pub fn running(&self, x: f64) -> f64 {
        let mut total: f64 = 0.0;
        (Label::twice({
            let __set = (x + 3.0);
            total = __set;
            __set
        }) + total)
    }
}

impl DartAny for Label {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Label" }
    }
}
