use crate::DartAny;

// Generated by tools/dart2rust from upstream `Label`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Debug, PartialEq)]
pub struct Label {
    pub name: String,
    pub count: i64,
}

impl Label {
    pub const fn new(name: String, count: i64) -> Self {
        Self {
            name: name,
            count: count,
        }
    }

    pub fn twice(x: f64) -> f64 {
        (x * 2.0)
    }

    /// `format!`, with the literal pieces becoming the pattern.
    pub fn describe(&self) -> String {
        format!("{} has {}", self.name, self.count)
    }

    /// A literal brace has to survive, since `format!` reads braces.
    pub fn braced(&self) -> String {
        format!("{{{}}}", self.name)
    }

    /// A static method used as a value. Nothing is captured, so none of the
    /// ownership question an instance tear-off raises applies.
    pub fn doubled(&self, x: f64) -> f64 {
        let f: Box<dyn Fn(f64) -> f64> = Box::new(Label::twice);
        (f)(x)
    }

    /// A local function, which is a closure bound to a local.
    pub fn stepped(&self, x: f64) -> f64 {
        let step = |v: f64| (v + 1.0);
        (step)((step)(x))
    }

    /// `total = ..` used for its value, inside the argument of another call.
    /// 7.0 doubled is 14.0, plus the 7.0 the assignment left behind.
    pub fn running(&self, x: f64) -> f64 {
        let mut total: f64 = 0.0;
        (Label::twice({
            let __set = (x + 3.0);
            total = __set;
            __set
        }) + total)
    }
}

impl DartAny for Label {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}
