// Generated by tools/dart2rust from upstream `Temperature`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Temperature {
    _celsius: f32,
}

impl Temperature {
    pub fn new(_celsius: f32) -> Self {
        Self { _celsius: _celsius }
    }

    /// Reads only. Must stay `&self`.
    pub fn celsius(&self) -> f32 {
        self._celsius
    }

    /// Writes. Must become `set_celsius(&mut self, ..)`.
    pub fn set_celsius(&mut self, value: f32) -> () {
        self._celsius = value;
    }

    /// A setter with real logic, not a plain field write -- which is why a setter
    /// cannot be translated as an assignment.
    pub fn set_fahrenheit(&mut self, value: f32) -> () {
        self._celsius = ((value - 32.0) / 1.8);
    }

    pub fn fahrenheit(&self) -> f32 {
        ((self._celsius * 1.8) + 32.0)
    }

    /// Assigns through this object's own setter. Mutating by contagion.
    pub fn warm_by(&mut self, degrees: f32) -> () {
        self.set_celsius((self.celsius() + degrees));
    }

    /// A compound assignment through a setter: the "current value" comes from the
    /// getter, since there may be no field of that name at all.
    pub fn heat_up(&mut self) -> () {
        self.set_fahrenheit((self.fahrenheit() + 18.0));
    }

    /// Reads through both getters. Stays `&self`.
    pub fn difference(&self) -> f32 {
        (self.fahrenheit() - self.celsius())
    }
}
