// Generated by tools/dart2rust from upstream `Shape`
// (abstract -> trait).

/// The body of `Shape.area`, reachable from an
/// override the way Dart's `super.area` is.
pub fn shape_super_area<S: Shape + ?Sized>(this_: &S, scale: f32) -> f32 {
    (100.0 * scale)
}

pub trait Shape {
    fn perimeter(&self) -> f32;

    /// The base's own answer. An override that calls `super.area()` must reach
    /// *this* body.
    fn area(&self, scale: f32) -> f32 {
        shape_super_area(self, scale)
    }
}

// Generated by tools/dart2rust from upstream `Doubled`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Doubled {}

impl Doubled {
    pub const fn new() -> Self {
        Self {}
    }

    /// Adds to whatever the base said. If `super.area` came back here instead,
    /// this would recurse forever rather than return 201.
    pub fn area(&self, scale: f32) -> f32 {
        (shape_super_area(self, scale) + 1.0)
    }

    pub fn perimeter(&self) -> f32 {
        7.0
    }
}

impl Shape for Doubled {
    fn perimeter(&self) -> f32 {
        Doubled::perimeter(self)
    }

    fn area(&self, scale: f32) -> f32 {
        Doubled::area(self, scale)
    }
}

// Generated by tools/dart2rust from upstream `Untouched`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Untouched {}

impl Untouched {
    pub const fn new() -> Self {
        Self {}
    }

    /// Does not override `area`, so it gets the trait's default -- which must be
    /// the same body the base declared.
    pub fn perimeter(&self) -> f32 {
        3.0
    }
}

impl Shape for Untouched {
    fn perimeter(&self) -> f32 {
        Untouched::perimeter(self)
    }
}

// Generated by tools/dart2rust from upstream `Untranslatable`
// (abstract -> trait).

/// A base whose method cannot be translated, so a subclass calling `super` on
/// it must be stopped rather than pointed at a function nobody wrote.

/// The body of `Untranslatable.describe`, reachable from an
/// override the way Dart's `super.describe` is.
pub fn untranslatable_super_describe<S: Untranslatable + ?Sized>(this_: &S) -> String {
    let mut out: String = "".to_string();
    let mut i: i64 = 0;
    while (i < 2) {
        out = format!("{}{}", out, "x".to_string());
        i = (i + 1);
    }
    out
}

pub trait Untranslatable {
    fn size(&self) -> f32;

    /// Uses a `for` loop, which is not translated yet, so this method is
    /// refused. It was a cascade until round twenty-three made cascades work --
    /// a fixture whose "untranslatable" construct becomes translatable stops
    /// testing what it was for, and the two front ends disagreeing is what said
    /// so.
    fn describe(&self) -> String {
        untranslatable_super_describe(self)
    }
}

// Generated by tools/dart2rust from upstream `UsesIt`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct UsesIt {}

impl UsesIt {
    pub const fn new() -> Self {
        Self {}
    }

    /// Calls super on a method the base could not translate. The compiler must
    /// refuse this, not emit `untranslatable_super_describe(self)`.
    pub fn describe(&self) -> String {
        untranslatable_super_describe(self)
    }

    pub fn size(&self) -> f32 {
        5.0
    }
}

impl Untranslatable for UsesIt {
    fn size(&self) -> f32 {
        UsesIt::size(self)
    }

    fn describe(&self) -> String {
        UsesIt::describe(self)
    }
}
