use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Shape`
// (abstract -> trait).

/// The body of `Shape.area`, reachable from an
/// override the way Dart's `super.area` is.
pub fn shape_super_area<__Self: Shape + ?Sized + 'static>(this_: &__Self, scale: f64) -> f64 {
    (100.0 * scale)
}

pub trait Shape: DartAny + std::fmt::Debug {
    fn perimeter(&self) -> f64;

    fn area(&self, scale: f64) -> f64 {
        shape_super_area(self, scale)
    }
}
impl Object for dyn Shape {
    fn as_any(&self) -> &dyn std::any::Any {
        DartAny::as_any(self)
    }
    fn runtime_type(&self) -> Type {
        DartAny::dart_runtime_type(self)
    }
}
impl PartialEq for dyn Shape {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Shape {}
impl std::hash::Hash for dyn Shape {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Doubled`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Doubled {}

impl Doubled {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn area(&self, scale: f64) -> f64 {
        (shape_super_area(self, scale) + 1.0)
    }

    pub fn perimeter(&self) -> f64 {
        7.0
    }
}

impl DartAny for Doubled {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Doubled" }
    }
}

impl Shape for Doubled {
    fn perimeter(&self) -> f64 {
        Doubled::perimeter(self)
    }

    fn area(&self, scale: f64) -> f64 {
        Doubled::area(self, scale)
    }
}

// Generated by tools/dart2rust from upstream `Untouched`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Untouched {}

impl Untouched {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn perimeter(&self) -> f64 {
        3.0
    }
}

impl DartAny for Untouched {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Untouched" }
    }
}

impl Shape for Untouched {
    fn perimeter(&self) -> f64 {
        Untouched::perimeter(self)
    }
}

// Generated by tools/dart2rust from upstream `Untranslatable`
// (abstract -> trait).

/// The body of `Untranslatable.describe`, reachable from an
/// override the way Dart's `super.describe` is.
pub fn untranslatable_super_describe<__Self: Untranslatable + ?Sized + 'static>(
    this_: &__Self,
) -> String {
    let mut out: String = "".to_string();
    let mut i: i64 = 0;
    while (i < 2) {
        out = format!("{}{}", out, "x".to_string());
        i = (i + 1);
    }
    out.clone()
}

pub trait Untranslatable: DartAny + std::fmt::Debug {
    fn size(&self) -> f64;

    fn describe(&self) -> String {
        untranslatable_super_describe(self)
    }
}
impl Object for dyn Untranslatable {
    fn as_any(&self) -> &dyn std::any::Any {
        DartAny::as_any(self)
    }
    fn runtime_type(&self) -> Type {
        DartAny::dart_runtime_type(self)
    }
}
impl PartialEq for dyn Untranslatable {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Untranslatable {}
impl std::hash::Hash for dyn Untranslatable {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `UsesIt`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct UsesIt {}

impl UsesIt {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn describe(&self) -> String {
        untranslatable_super_describe(self)
    }

    pub fn size(&self) -> f64 {
        5.0
    }
}

impl DartAny for UsesIt {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "UsesIt" }
    }
}

impl Untranslatable for UsesIt {
    fn size(&self) -> f64 {
        UsesIt::size(self)
    }

    fn describe(&self) -> String {
        UsesIt::describe(self)
    }
}

// Generated by tools/dart2rust from upstream `NamesItself`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct NamesItself {}

impl NamesItself {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn describe(&self) -> String {
        format!("Instance of '{}'", "NamesItself")
    }
}

impl DartAny for NamesItself {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type {
            name: "NamesItself",
        }
    }
}
