// Generated by tools/dart2rust from upstream `Shape`
// (abstract -> trait).

/// The body of `Shape.area`, reachable from an
/// override the way Dart's `super.area` is.
pub fn shape_super_area<S: Shape + ?Sized>(this_: &S) -> f32 {
    (this_.width() * this_.height())
}

pub trait Shape {
    /// `Shape.width`, which the implementor stores.
    fn width(&self) -> f32;

    /// `Shape.height`, which the implementor stores.
    fn height(&self) -> f32;

    fn area(&self) -> f32 {
        shape_super_area(self)
    }
}

// Generated by tools/dart2rust from upstream `Rectangle`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Rectangle {
    pub width: f32,
    pub height: f32,
}

impl Rectangle {
    pub const fn new(w: f32, h: f32) -> Self {
        Self {
            width: w,
            height: h,
        }
    }
}

impl Shape for Rectangle {
    fn width(&self) -> f32 {
        self.width
    }

    fn height(&self) -> f32 {
        self.height
    }
}

// Generated by tools/dart2rust from upstream `Square`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// Passes a computed argument up, so the substitution has to carry an
/// expression rather than just a name.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Square {
    pub width: f32,
    pub height: f32,
    pub side: f32,
}

impl Square {
    pub const fn new(side: f32) -> Self {
        Self {
            width: side,
            height: side,
            side: side,
        }
    }
}

impl Shape for Square {
    fn width(&self) -> f32 {
        self.width
    }

    fn height(&self) -> f32 {
        self.height
    }
}

// Generated by tools/dart2rust from upstream `Padded`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// Two levels: `Padded` -> `Square` -> `Shape`. Chains go six deep upstream.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Padded {
    pub width: f32,
    pub height: f32,
    pub side: f32,
    pub padding: f32,
}

impl Padded {
    pub const fn new(side: f32, padding: f32) -> Self {
        Self {
            width: side,
            height: side,
            side: side,
            padding: padding,
        }
    }

    pub fn padded_area(&self) -> f32 {
        ((self.width + self.padding) * (self.height + self.padding))
    }
}

impl Shape for Padded {
    fn width(&self) -> f32 {
        self.width
    }

    fn height(&self) -> f32 {
        self.height
    }
}
