// The front end refused 2 member(s) in this library:
// NOT TRANSLATED: top-level computed: unsupported a top-level accessor: computed
// NOT TRANSLATED: Layout: unsupported top-level getter `computed`: computed

pub const K_SPACING: f64 = 8.0;
pub const K_MAX_ITEMS: i64 = 10;
pub const K_VERBOSE: bool = false;
pub const K_DERIVED: f64 = (K_SPACING * 2.0);

// Generated by tools/dart2rust from upstream `Layout`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Layout {
    pub count: i64,
}

impl Layout {
    pub const fn new(count: i64) -> Self {
        Self { count: count }
    }

    pub fn total_spacing(&self) -> f64 {
        (K_SPACING * 3.0)
    }

    /// Reads two different top-level constants, so one standing in for the other
    /// would show up.
    pub fn is_full(&self) -> bool {
        (self.count >= K_MAX_ITEMS)
    }

    pub fn derived(&self) -> f64 {
        K_DERIVED
    }
}
