use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

pub fn computed() -> f64 {
    (8.0 + 1.0)
}

pub const K_SPACING: f64 = 8.0;
pub const K_MAX_ITEMS: i64 = 10;
pub const K_VERBOSE: bool = false;
pub const K_DERIVED: f64 = (8.0 * 2.0);

// Generated by tools/dart2rust from upstream `Layout`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Layout {
    pub count: i64,
}

impl Layout {
    pub const fn new(count: i64) -> Self {
        Self { count: count }
    }

    pub fn total_spacing(&self) -> f64 {
        (8.0 * 3.0)
    }

    pub fn is_full(&self) -> bool {
        (self.count >= 10)
    }

    pub fn derived(&self) -> f64 {
        K_DERIVED
    }

    pub fn uses_computed(&self) -> f64 {
        computed()
    }
}

impl DartAny for Layout {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Layout" }
    }
}
