use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::RangeError;
use crate::StackTrace;
use crate::Type;

// Generated by tools/dart2rust from upstream `Guarded`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Guarded {
    pub limit: f64,
}

impl Guarded {
    pub const fn new(limit: f64) -> Self {
        Self { limit: limit }
    }

    pub fn checked(&self, value: f64) -> f64 {
        if (value > self.limit) {
            panic!(
                "uncaught Dart exception: {:?}",
                RangeError::new("over the limit".to_string())
            );
        }
        value
    }

    pub fn recovered(&self, value: f64) -> f64 {
        let mut result: f64 = 0.0;
        match (|| -> Result<(), std::rc::Rc<dyn Object>> {
            result = self.checked(value);
            Ok(())
        })() {
            Ok(()) => {}
            Err(e) => {
                result = (-1.0);
            }
        }
        result
    }

    pub fn recovered_with_unused_trace(&self, value: f64) -> f64 {
        let mut result: f64 = 0.0;
        match (|| -> Result<(), std::rc::Rc<dyn Object>> {
            result = self.checked(value);
            Ok(())
        })() {
            Ok(()) => {}
            Err(e) => {
                let mut stack = StackTrace::current();
                result = (-2.0);
            }
        }
        result
    }

    pub fn uncaught(&self, value: f64) -> f64 {
        (self.checked(value) + 1.0)
    }

    pub fn returns_from_inside_try(&self, value: f64) -> f64 {
        match (|| -> Result<Option<f64>, std::rc::Rc<dyn Object>> {
            return Ok(Some(self.checked(value)));
            #[allow(unreachable_code)]
            Ok(None)
        })() {
            Ok(Some(__returned)) => return __returned,
            Ok(None) => unreachable!("the try body always returns"),
            Err(e) => {
                return (-3.0);
            }
        }
    }

    pub fn returns_on_one_path(&self, value: f64) -> f64 {
        let mut result: f64 = 0.0;
        match (|| -> Result<Option<f64>, std::rc::Rc<dyn Object>> {
            if (value < 0.0) {
                return Ok(Some((-4.0)));
            }
            result = self.checked(value);
            #[allow(unreachable_code)]
            Ok(None)
        })() {
            Ok(Some(__returned)) => return __returned,
            Ok(None) => {}
            Err(e) => {
                result = (-5.0);
            }
        }
        result
    }
}

impl DartAny for Guarded {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Guarded" }
    }
}

// Generated by tools/dart2rust from upstream `Tally`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tally {
    pub limit: f64,
    pub runs: i64,
}

impl Tally {
    pub fn new(limit: f64) -> Self {
        Self {
            limit: limit,
            runs: 0,
        }
    }

    pub fn checked(&self, value: f64) -> f64 {
        if (value > self.limit) {
            panic!(
                "uncaught Dart exception: {:?}",
                RangeError::new("over the limit".to_string())
            );
        }
        value
    }

    pub fn counted(&mut self, value: f64) -> f64 {
        let __finally = (|| -> Result<Option<f64>, std::convert::Infallible> {
            if (value < 0.0) {
                return Ok(Some((-6.0)));
            }
            return Ok(Some(self.checked(value)));
            #[allow(unreachable_code)]
            Ok(None)
        })();
        self.runs = (self.runs + 1);
        match __finally {
            Ok(Some(__returned)) => return __returned,
            Ok(None) => unreachable!("the try body always returns"),
            Err(__failed) => match __failed {},
        }
    }
}

impl DartAny for Tally {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Tally" }
    }
}
