use crate::RangeError;

// Generated by tools/dart2rust from upstream `Guarded`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Guarded {
    pub limit: f32,
}

impl Guarded {
    pub const fn new(limit: f32) -> Self {
        Self { limit: limit }
    }

    pub fn checked(&self, value: f32) -> Result<f32, RangeError> {
        if (value > self.limit) {
            return Err(RangeError::new("over the limit".to_string()));
        }
        Ok(value)
    }

    /// Catches, so this method does **not** return a Result. That is the whole
    /// test: the failure stops here.
    pub fn recovered(&self, value: f32) -> f32 {
        let mut result: f32 = 0.0;
        match (|| -> Result<(), RangeError> {
            result = self.checked(value)?;
            Ok(())
        })() {
            Ok(()) => {}
            Err(e) => {
                result = (-1.0);
            }
        }
        result
    }

    /// A catch that binds a stack trace and never reads it. Free, since ignoring
    /// something a Result does not carry costs nothing.
    pub fn recovered_with_unused_trace(&self, value: f32) -> f32 {
        let mut result: f32 = 0.0;
        match (|| -> Result<(), RangeError> {
            result = self.checked(value)?;
            Ok(())
        })() {
            Ok(()) => {}
            Err(e) => {
                result = (-2.0);
            }
        }
        result
    }

    /// Does not catch, so the failure keeps travelling and this one does return
    /// a Result. The pair is the point: catching and not catching have to give
    /// different signatures.
    pub fn uncaught(&self, value: f32) -> Result<f32, RangeError> {
        Ok((self.checked(value)? + 1.0))
    }

    /// The fixture's sharpest case. The try body is emitted as a closure, so a
    /// plain `return` here would leave the *closure* and the method would carry
    /// on -- returning whatever came after, and compiling while it did it. So the
    /// closure carries the control flow out as a value instead. If it did not,
    /// this would return 0.0 for every input rather than the two below.
    pub fn returns_from_inside_try(&self, value: f32) -> f32 {
        match (|| -> Result<Option<f32>, RangeError> {
            return Ok(Some(self.checked(value)?));
            #[allow(unreachable_code)]
            Ok(None)
        })() {
            Ok(Some(__returned)) => return __returned,
            Ok(None) => unreachable!("the try body always returns"),
            Err(e) => {
                return (-3.0);
            }
        }
    }

    /// A `return` on only *one* path through the try body. The other path falls
    /// off the end of the closure, which is what `Ok(None)` is for -- without it
    /// this case and the one above cannot be told apart.
    pub fn returns_on_one_path(&self, value: f32) -> f32 {
        let mut result: f32 = 0.0;
        match (|| -> Result<Option<f32>, RangeError> {
            if (value < 0.0) {
                return Ok(Some((-4.0)));
            }
            result = self.checked(value)?;
            #[allow(unreachable_code)]
            Ok(None)
        })() {
            Ok(Some(__returned)) => return __returned,
            Ok(None) => {}
            Err(e) => {
                result = (-5.0);
            }
        }
        result
    }
}

// Generated by tools/dart2rust from upstream `Tally`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// `finally` on its own class, because showing that the finalizer ran needs a
/// field that can change and `Guarded` is const.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tally {
    pub limit: f32,
    pub runs: i64,
}

impl Tally {
    pub fn new(limit: f32) -> Self {
        Self {
            limit: limit,
            runs: 0,
        }
    }

    pub fn checked(&self, value: f32) -> Result<f32, RangeError> {
        if (value > self.limit) {
            return Err(RangeError::new("over the limit".to_string()));
        }
        Ok(value)
    }

    /// Three ways out of the body -- returned early, returned a value that may
    /// throw, and threw -- and `runs` has to go up on all three. A finalizer that
    /// ran only on the ordinary path would pass a test that used just one of
    /// them, which is why the test uses all three in sequence.
    pub fn counted(&mut self, value: f32) -> Result<f32, RangeError> {
        let __finally = (|| -> Result<Option<Result<f32, RangeError>>, RangeError> {
            if (value < 0.0) {
                return Ok(Some(Ok((-6.0))));
            }
            return Ok(Some(Ok(self.checked(value)?)));
            #[allow(unreachable_code)]
            Ok(None)
        })();
        self.runs = (self.runs + 1);
        match __finally {
            Ok(Some(__returned)) => return __returned,
            Ok(None) => unreachable!("the try body always returns"),
            Err(__failed) => return Err(__failed),
        }
    }
}
