use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// Generated by tools/dart2rust from upstream `Figure`
// (abstract -> trait).

pub trait Figure: DartAny + std::fmt::Debug {
    fn area(&self) -> f64;
}
impl Object for dyn Figure {
    fn as_any(&self) -> &dyn std::any::Any {
        DartAny::as_any(self)
    }
    fn runtime_type(&self) -> Type {
        DartAny::dart_runtime_type(self)
    }
}
impl PartialEq for dyn Figure {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Figure {}
impl std::hash::Hash for dyn Figure {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Tile`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tile {
    pub side: f64,
}

impl Tile {
    pub const fn new(side: f64) -> Self {
        Self { side: side }
    }

    pub fn area(&self) -> f64 {
        (self.side * self.side)
    }
}

impl DartAny for Tile {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Tile" }
    }
}

impl Figure for Tile {
    fn area(&self) -> f64 {
        Tile::area(self)
    }
}

// Generated by tools/dart2rust from upstream `Wedge`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Wedge {
    pub width: f64,
    pub height: f64,
}

impl Wedge {
    pub const fn new(width: f64, height: f64) -> Self {
        Self {
            width: width,
            height: height,
        }
    }

    pub fn area(&self) -> f64 {
        ((self.width * self.height) / 2.0)
    }
}

impl DartAny for Wedge {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Wedge" }
    }
}

impl Figure for Wedge {
    fn area(&self) -> f64 {
        Wedge::area(self)
    }
}

// Generated by tools/dart2rust from upstream `Figures`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Figures {}

impl Figures {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn is_tile(s: std::rc::Rc<dyn Figure>) -> bool {
        s.as_any().downcast_ref::<Tile>().is_some()
    }

    pub fn is_not_tile(s: std::rc::Rc<dyn Figure>) -> bool {
        s.as_any().downcast_ref::<Tile>().is_none()
    }

    pub fn area_of_tiles(a: std::rc::Rc<dyn Figure>, b: std::rc::Rc<dyn Figure>) -> f64 {
        let mut total: f64 = 0.0;
        if a.as_any().downcast_ref::<Tile>().is_some() {
            total = (total + a.as_any().downcast_ref::<Tile>().unwrap().clone().area());
        }
        if b.as_any().downcast_ref::<Tile>().is_some() {
            total = (total + b.as_any().downcast_ref::<Tile>().unwrap().clone().area());
        }
        total
    }
}

impl DartAny for Figures {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Figures" }
    }
}

// Generated by tools/dart2rust from upstream `Marker`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Marker {}

impl Marker {
    pub const fn new() -> Self {
        Self {}
    }
}

impl DartAny for Marker {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Marker" }
    }
}

// Generated by tools/dart2rust from upstream `Types`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Types {}

impl Types {
    pub const fn new() -> Self {
        Self {}
    }

    pub fn marker_type() -> Type {
        Type::of("Marker")
    }

    pub fn is_marker(t: Type) -> bool {
        (t == Type::of("Marker"))
    }

    pub fn is_tile(t: Type) -> bool {
        (t == Type::of("Tile"))
    }
}

impl DartAny for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn dart_runtime_type(&self) -> Type {
        Type { name: "Types" }
    }
}
