use crate::dart_prelude::Object;
use crate::dart_prelude::*;
use crate::DartAny;
use crate::Type;

// The front end refused 3 member(s) in this library:
// NOT TRANSLATED: Types: unsupported expression TypeLiteralImpl: Marker
// NOT TRANSLATED: Types: unsupported expression TypeLiteralImpl: Marker
// NOT TRANSLATED: Types: unsupported expression TypeLiteralImpl: Tile

// Generated by tools/dart2rust from upstream `Figure`
// (abstract -> trait).

impl DartEq for dyn Figure {
    fn dart_eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self as *const Self, other as *const Self)
    }
    fn dart_hash_code(&self) -> i64 {
        (self as *const Self as *const u8 as usize as i64) & 0x3fff_ffff
    }
}

pub trait Figure: DartAny + std::fmt::Debug {
    fn dart_self_figure(&self) -> std::rc::Rc<dyn Figure>;

    fn area(&self) -> Result<f64, std::rc::Rc<dyn Object>>;
}
impl PartialEq for dyn Figure {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::addr_eq(self, other)
    }
}
impl Eq for dyn Figure {}
impl std::hash::Hash for dyn Figure {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        (self as *const Self as *const u8 as usize).hash(state)
    }
}

// Generated by tools/dart2rust from upstream `Tile`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tile {
    pub side: f64,
}

impl Tile {
    pub const fn new(side: f64) -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({ Self { side: side } })
    }

    pub fn area(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Ok((self.side * self.side))
    }
}

impl FromDynamic for Tile {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Tile {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Tile was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Tile was declared")
    }
}

impl DartNullable for Tile {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Tile {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Tile {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Tile")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Tile")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        if __t == std::any::TypeId::of::<dyn Figure>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Figure>>()
        {
            return Some(std::boxed::Box::new(self.dart_self_figure()));
        }
        None
    }
}

impl Figure for Tile {
    fn dart_self_figure(&self) -> std::rc::Rc<dyn Figure> {
        std::rc::Rc::new(self.clone())
    }

    fn area(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Tile::area(self)
    }
}

// Generated by tools/dart2rust from upstream `Wedge`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Wedge {
    pub width: f64,
    pub height: f64,
}

impl Wedge {
    pub const fn new(width: f64, height: f64) -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({
            Self {
                width: width,
                height: height,
            }
        })
    }

    pub fn area(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Ok(((self.width * self.height) / 2.0))
    }
}

impl FromDynamic for Wedge {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Wedge {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Wedge was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Wedge was declared")
    }
}

impl DartNullable for Wedge {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Wedge {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Wedge {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Wedge")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Wedge")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        if __t == std::any::TypeId::of::<dyn Figure>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Figure>>()
        {
            return Some(std::boxed::Box::new(self.dart_self_figure()));
        }
        None
    }
}

impl Figure for Wedge {
    fn dart_self_figure(&self) -> std::rc::Rc<dyn Figure> {
        std::rc::Rc::new(self.clone())
    }

    fn area(&self) -> Result<f64, std::rc::Rc<dyn Object>> {
        Wedge::area(self)
    }
}

// Generated by tools/dart2rust from upstream `Figures`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Figures {}

impl Figures {
    pub const fn new() -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({ Self {} })
    }

    /// The plain test: one concrete class, through a trait object.
    pub fn is_tile(s: std::rc::Rc<dyn Figure>) -> Result<bool, std::rc::Rc<dyn Object>> {
        Ok(s.as_any().downcast_ref::<Tile>().is_some())
    }

    /// `is!`, which is not "not `is`" in the IR -- it carries a flag, and
    /// answering it as `is_none()` keeps one `downcast_ref` rather than two.
    pub fn is_not_tile(s: std::rc::Rc<dyn Figure>) -> Result<bool, std::rc::Rc<dyn Object>> {
        Ok(s.as_any().downcast_ref::<Tile>().is_none())
    }

    /// Two tests in one body, so a wrong receiver in either shows.
    pub fn area_of_tiles(
        mut a: std::rc::Rc<dyn Figure>,
        mut b: std::rc::Rc<dyn Figure>,
    ) -> Result<f64, std::rc::Rc<dyn Object>> {
        let mut total: f64 = 0.0;
        if a.as_any().downcast_ref::<Tile>().is_some() {
            total = (total + a.area());
        }
        if b.as_any().downcast_ref::<Tile>().is_some() {
            total = (total + b.area());
        }
        Ok(total)
    }
}

impl FromDynamic for Figures {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Figures {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Figures was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Figures was declared")
    }
}

impl DartNullable for Figures {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Figures {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Figures {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Figures")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Figures")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}

// Generated by tools/dart2rust from upstream `Marker`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

/// A **class name where a value goes**: Dart's `Type`.
///
/// Not the same question as `is`. `x is Foo` asks about a value; `Foo` on its
/// own *is* a value, of type `Type`, and upstream compares it, prints it and
/// uses it as a map key. The prelude has had `Type::of(name)` for that all
/// along and nothing produced one -- which refused `Theme.of`, and `Theme.of`
/// is called 268 times. Four `of` methods stood on this one construct and
/// accounted for 464 of the 670 "called something that was not translated".
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Marker {}

impl Marker {
    pub const fn new() -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({ Self {} })
    }
}

impl FromDynamic for Marker {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Marker {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Marker was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Marker was declared")
    }
}

impl DartNullable for Marker {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Marker {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Marker {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Marker")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Marker")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}

// Generated by tools/dart2rust from upstream `Types`.
//
// Translated, not ported: this is the compiler's output, not a
// hand-written re-expression. See tools/dart2rust/README.md.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Types {}

impl Types {
    pub const fn new() -> Result<Self, std::rc::Rc<dyn Object>> {
        Ok({ Self {} })
    }
}

impl FromDynamic for Types {
    fn from_dynamic(value: &std::rc::Rc<dyn Object>) -> Option<Self> {
        value.dart_cast_any::<Self>()
    }
    fn from_same(value: &Self) -> Option<Self> {
        Some(value.clone())
    }
}

impl NativeAnswer for Types {
    fn from_answer(answer: std::rc::Rc<dyn Object>, symbol: &str) -> Self {
        match answer.dart_cast_any::<Self>() {
            Some(value) => value,
            None => panic!(
                "native `{}` answered {:?} where Types was declared",
                symbol, answer
            ),
        }
    }
    fn absent() -> Self {
        panic!("native answered nothing where Types was declared")
    }
}

impl DartNullable for Types {
    type Or = Option<Self>;
    fn option(or: Option<Self>) -> Option<Self> {
        or
    }
    fn from_option(option: Option<Self>) -> Option<Self> {
        option
    }
}

impl DartEq for Types {
    fn dart_eq(&self, other: &Self) -> bool {
        self == other
    }
}

impl DartAny for Types {
    fn dart_to_string(&self) -> String {
        format!("Instance of '{}'", "Types")
    }
    fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool {
        match other.downcast_ref::<Self>() {
            Some(o) => self.dart_eq(o),
            None => false,
        }
    }
    fn dart_hash_any(&self) -> i64 {
        self.dart_hash_code()
    }
    fn dart_runtime_type(&self) -> Type {
        Type::of("Types")
    }
    fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {
        if __t == std::any::TypeId::of::<Self>()
            || __t == std::any::TypeId::of::<std::rc::Rc<Self>>()
        {
            return Some(std::boxed::Box::new(std::rc::Rc::new(self.clone())));
        }
        if __t == std::any::TypeId::of::<dyn Object>()
            || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>()
        {
            return Some(std::boxed::Box::new(
                std::rc::Rc::new(self.clone()) as std::rc::Rc<dyn Object>
            ));
        }
        None
    }
}
