part of '../backend_rust.dart';

// The struct, its prelude interfaces and its base impls.
augment class RustBackend {
  String _emitStruct() {
    _line('// Generated by tools/dart2rust from upstream `${cls.name}`.');
    _line('//');
    _line('// Translated, not ported: this is the compiler\'s output, not a');
    _line('// hand-written re-expression. See tools/dart2rust/README.md.');
    _line('');
    _doc(cls.doc);
    // `Copy` only when every field is. A `String` field is not, and deriving
    // it anyway does not compile -- which is loud, but the derive is this
    // compiler's own line and it should not write one it knows is wrong.
    // Asked of the *emitted* type: a shared field is an `Rc<Cell<..>>`, which
    // is not `Copy` however copyable the value inside it is. Asking the Dart
    // type instead derived `Copy` for a struct that cannot have it.
    final copyable =
        !cls.counted && _allFields(cls).every((f) => _isCopy(_fieldType(f)));
    // `Debug` and `PartialEq` cannot be derived over a function-typed field
    // (a `dyn Fn` is neither), and a struct holding one got 15 `E0369`s and
    // 14 `E0277`s for the derive alone. Left off there: a `==` on such a
    // class is then an error at the use, which says what it is.
    // Nested too: a `Vec<Option<Rc<dyn Fn()>>>` field cannot be printed.
    final printable = _allFields(cls).every(
      (f) =>
          !f.type.isFunction &&
          !_fieldType(f).contains('dyn Fn') &&
          // A boxed future prints and compares no better than a closure.
          !_fieldType(f).contains('dyn std::future::Future'),
    );
    // A trait-object field compares by identity, and a derived `PartialEq`
    // cannot say so: `self.f == other.f` on an `Rc<dyn Object>` moved the
    // right-hand side (E0507, rustc 1.98 -- reproduced on four lines). The
    // `impl` is written out below instead, field by field, with the
    // prelude's `dart_eq` on those.
    // ..and a counted class's handle: `Rc<DynamicColor>` compares by
    // identity too, which is what Dart says of two references.
    // The field *is* a handle -- `Rc<..>`, or an `Option`/`Vec` of one --
    // not a struct that merely holds one somewhere in its type arguments
    // (`MapEquality<K, V>` compares by value).
    final handle = RegExp(r'^(Option<|Vec<)*std::rc::Rc<');
    // A closure field too: `PointerData._onRespond` is an `Rc<dyn Fn>`,
    // which `DartEq` compares by address as Dart compares closures. Left
    // out, the struct had no `PartialEq` at all and nothing generic over
    // it could be called (`_invoke1<PointerDataPacket>`).
    // ..and a field that *holds* function values anywhere in its type: a
    // `Map<String, WidgetBuilder>` (`WidgetsApp.routes`) has no
    // `PartialEq` to derive from, because `Rc<dyn Fn>` has none, and Dart
    // compares the closures inside it by identity -- which is exactly what
    // `DartEq` says of them (3 at ws793).
    final byIdentity = _allFields(cls)
        .where(
          (f) =>
              f.type.isFunction ||
              handle.hasMatch(_fieldType(f)) ||
              _fieldType(f).contains('dyn Fn'),
        )
        .toList();
    // ..and every field's own class comparable, recursively: a
    // `VecDeque<_StoredMessage>` of a struct holding a closure derives
    // nothing (`==` cannot be applied, 3).
    // ..and not over a projected `T?` field: `<T as DartNullable>::Or:
    // PartialEq` is a where clause a derive cannot write.
    final comparable =
        printable &&
        byIdentity.isEmpty &&
        _allFields(cls).every((f) => !f.type.projected) &&
        _allFields(cls)
            .every((f) => _comparableType(_fieldType(f), {cls.name}));
    // A counted class without an `operator ==` of its own is Dart's
    // `Object.==`: identity. Field by field it walked the object graph --
    // `FocusManager` holds its root scope, which holds its manager -- and
    // overflowed the stack on the first `==` between two (run641).
    final identityEq =
        cls.counted && !cls.methods.any((m) => m.operator == '==');
    // A boxed future is not `Clone`, and a struct holding one (an
    // `AssetBundle`'s caches) cannot derive it; its handle, the `Rc` every
    // counted class is passed by, still is. A value class holding one
    // would have to be cloned by value somewhere and is left to say so.
    final cloneable = _cloneable(cls);
    // A struct with a projected `T?` field writes its `Clone` out below:
    // the derive cannot say `<T as DartNullable>::Or: Clone`, and a bound
    // on the struct's own parameters would have to be repeated by every
    // declaration naming it (`_FutureBuilderState<T>` holding an
    // `AsyncSnapshot<T>`, ws403).
    final projecting = _allFields(cls).any((f) => f.type.projected);
    // ..and every *generic* struct's, for the same reason one step removed:
    // a derive over a field holding a projecting struct (`Option<
    // DropdownMenuItem<T>>`) needs that struct's `Clone`, whose bound is
    // `<T as DartNullable>::Or: Clone` -- said on the impl, where nothing
    // has to repeat it.
    final writesClone =
        cloneable && (projecting || cls.typeParameters.isNotEmpty);
    // A derived `Debug` on `ValueKey<T>` holds only for `T: Debug`, and
    // the `Key` trait it implements has `Debug` above it for every `T:
    // Clone + DartNullable<Or: Clone> + 'static` (18 E0277s the moment the type parameters lost
    // their `Debug` bound). A generic class prints as its class instead;
    // `PartialEq` can still be derived, that impl carries its own `T:
    // PartialEq` and no trait asks for it unconditionally.
    final derivesDebug = printable && cls.typeParameters.isEmpty;
    final derives = [
      if (cloneable && !writesClone) 'Clone',
      if (copyable && !writesClone) 'Copy',
      if (derivesDebug) 'Debug',
      if (comparable && !identityEq) 'PartialEq',
    ];
    if (derives.isNotEmpty) _line('#[derive(${derives.join(', ')})]');
    // `'static` on the struct: an `Rc<dyn Equality<Option<E>>>` field needs
    // its `E` to outlive the trait object (8 E0310s in `collection`).
    _line(
      '${_vis(cls.name)}struct ${cls.name}${_generics(cls, static: true)} {',
    );
    _indent++;
    for (final field in _allFields(cls)) {
      _doc(field.doc);
      _line('${_vis(field.name)}${snake(field.name)}: ${_fieldType(field)},');
    }
    // A counted object knows its own handle (`DartSelf`): a trait body's
    // `this` is `self.dart_self_<trait>()`, 117 `&__Self` where an
    // `Rc<dyn X>` was wanted at ws271.
    // `pub`: a constant instance of the class is spelled as a struct
    // literal wherever it is used (`dart_rc(Struct {..})`), other modules
    // included (E0451 in `SemanticsService`, ws432).
    if (cls.counted) _line('pub __self: DartSelf<Self>,');
    // A Dart class can name a type parameter it never stores -- `Tween<T>`
    // holds `begin` and `end` of type `T?`, but plenty do not. Rust will not
    // have an unused parameter, and `PhantomData` is what it offers instead.
    for (final unused in _unusedParameters(cls)) {
      _line(
        'pub _phantom_${snake(unused)}: '
        'std::marker::PhantomData<$unused>,',
      );
    }
    _indent--;
    _line('}');
    _line('');
    if (writesClone) {
      _line(
        'impl${_implGenerics(cls, keyed: false)} Clone for ${cls.name}${_generics(cls)} {',
      );
      _indent++;
      final copied = [
        for (final f in _allFields(cls))
          '${snake(f.name)}: self.${snake(f.name)}.clone()',
        if (cls.counted) '__self: self.__self.clone()',
        for (final unused in _unusedParameters(cls))
          '_phantom_${snake(unused)}: std::marker::PhantomData',
      ];
      _line('fn clone(&self) -> Self { ${cls.name} { ${copied.join(', ')} } }');
      _indent--;
      _line('}');
      _line('');
      // `Copy` alongside, under the same bound: a derived one asks `Clone`
      // of every `T: Copy`, which the impl above does not give.
      if (copyable) {
        final generics = _implGenerics(
          cls,
          keyed: false,
        ).replaceAll("'static", "'static + Copy");
        _line('impl$generics Copy for ${cls.name}${_generics(cls)} {}');
        _line('');
      }
    }
    if (cls.counted) {
      _line(
        'impl${_implGenerics(cls, keyed: false)} DartSelfRef for ${cls.name}${_generics(cls)} {',
      );
      _indent++;
      _line('fn dart_self_ref(&self) -> &DartSelf<Self> { &self.__self }');
      _indent--;
      _line('}');
      _line('');
    }
    // A struct holding a closure still has to print -- `Rc<DynamicColor>`
    // in a struct that derives `Debug` -- so it prints as its class.
    if (!derivesDebug) {
      // The struct's own bounds, not the impl's: `_MapEntry` holds a
      // `MapEquality<Rc<dyn Object>, ..>` and derives `Debug` over it, and
      // `dyn Object` is no `Hash` -- the key bound the methods need is
      // theirs alone.
      _line(
        'impl${_generics(cls, static: true)} std::fmt::Debug for ${cls.name}${_generics(cls)} {',
      );
      _indent++;
      _line(
        "fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {",
      );
      _indent++;
      _line('write!(f, "Instance of \'${cls.name}\'")');
      _indent--;
      _line('}');
      _indent--;
      _line('}');
    }
    if (byIdentity.isNotEmpty || (identityEq && comparable)) {
      // The projected bound for *every* parameter, not only the ones this
      // class holds projected itself. A field can merely *hold* a generic
      // class whose own `PartialEq` asks for it: `_MenuItem<T>` holds an
      // `Option<DropdownMenuItem<T>>`, and `DropdownMenuItem<T>: PartialEq`
      // requires `<T as DartNullable>::Or: PartialEq`, which `_MenuItem`'s
      // clause never asked for because none of *its* fields is projected
      // ("binary operation `==` cannot be applied", E0369, ws979).
      //
      // Harmless where nothing needs it: `Or` is an associated type every
      // `DartNullable` has, so the clause is satisfiable wherever the
      // parameter's own `PartialEq` is.
      // Every projected field's *base*, which is not always a type
      // parameter: `IterableProperty<T>._value` is
      // `<Rc<dyn DartIterable<T>> as DartNullable>::Or`, and it is that
      // whole handle whose `Or` has to be `PartialEq`.
      final projected = {
        for (final f in _allFields(cls))
          if (f.type.projected)
            type(IrType(f.type.name, arguments: f.type.arguments)),
      };
      final bounds = cls.typeParameters.isEmpty
          ? ''
          : ' where ${{
              for (final p in cls.typeParameters) '$p: PartialEq',
              // ..and for every parameter, not only the ones this class
              // holds projected itself: a field can merely *hold* a generic
              // whose own `PartialEq` asks for it. `_MenuItem<T>` holds an
              // `Option<DropdownMenuItem<T>>`, and that wants
              // `<T as DartNullable>::Or: PartialEq` while none of
              // `_MenuItem`'s own fields is projected (E0369, ws979).
              for (final p in cls.typeParameters) '<$p as DartNullable>::Or: PartialEq',
              for (final p in projected) '<$p as DartNullable>::Or: PartialEq',
            }.join(', ')}';
      _line(
        'impl${_implGenerics(cls)} PartialEq for ${cls.name}${_generics(cls)}$bounds {',
      );
      _indent++;
      // By name: `_allFields` builds its list afresh each call, so the
      // `IrField`s are not the same objects (`source` came out as `==`).
      final identityNames = byIdentity.map((f) => f.name).toSet();
      final terms = [
        for (final f in _allFields(cls))
          // ..and any field Rust cannot compare: `DartEq` composes through
          // `Option`, `Vec` and `Rc`, which is exactly where `==` stops,
          // and it is what Dart compares those by anyway.
          identityNames.contains(f.name) ||
                  !_comparableType(_fieldType(f), {cls.name})
              ? 'self.${snake(f.name)}.dart_eq(&other.${snake(f.name)})'
              : 'self.${snake(f.name)} == other.${snake(f.name)}',
      ];
      _line(
        'fn eq(&self, other: &Self) -> bool { '
        '${identityEq
            ? 'std::ptr::eq(self, other)'
            : terms.isEmpty
            ? 'true'
            : terms.join(' && ')} }',
      );
      _indent--;
      _line('}');
      _line('');
    }

    // Constructors and constants in a block of their own when the methods
    // carry a key bound (`T: PartialEq`, `_implGenerics`): an
    // `ObserverList<Rc<dyn Fn()>>` can then be *made* wherever it is held,
    // and only the methods comparing its items are out of reach.
    final keyed = _implGenerics(cls);
    final unkeyed = _implGenerics(cls, keyed: false);
    _line('impl$unkeyed ${cls.name}${_generics(cls)} {');
    _indent++;
    _emitConstructors();
    if (!_freeStatics(cls.name)) _emitConstants();
    if (keyed != unkeyed) {
      _indent--;
      _line('}');
      _line('');
      _line('impl$keyed ${cls.name}${_generics(cls)} {');
      _indent++;
    }
    _emitMethods();
    _emitLazyAccessors();
    _emitToList();
    _indent--;
    _line('}');
    if (_freeStatics(cls.name)) {
      // A generic class's statics and constants at module level, named
      // with the class, as an abstract class's are (`_freeStatics`).
      _line('');
      _emitConstants(prefix: cls.name);
      for (final method in cls.methods) {
        if (!method.isStatic || method.operator != null) continue;
        _member(
          '${cls.name}.${method.name} (static)',
          () => _emitMethod(
            method,
            as: _abstractStaticName(cls.name, _methodName(method)),
          ),
        );
      }
    }
    // One line per struct rather than one blanket impl over everything: see
    // `DartAny` in the prelude for why the blanket one is quietly wrong.
    _line('');
    _emitDartNullable();
    // `DartEq`, by the `PartialEq` the struct has -- derived, or the
    // manual one above with its bounds -- and by identity when it has none.
    // A generic struct compares field by field through `DartEq`, which
    // every field type has (the `T: DartEq` bound is the struct's own); a
    // `T: PartialEq` bound shut out every `ObserverList<VoidCallback>`
    // (48 at ws445).
    String fieldWise() {
      final parts = [
        for (final f in _allFields(cls))
          'self.${snake(f.name)}.dart_eq(&other.${snake(f.name)})',
      ];
      return parts.isEmpty ? 'true' : parts.join(' && ');
    }

    if (identityEq) {
      _emitDartEq(body: 'std::ptr::eq(self, other)');
    } else if (comparable || byIdentity.isNotEmpty) {
      _emitDartEq(
        body: cls.typeParameters.isEmpty ? 'self == other' : fieldWise(),
      );
    } else {
      _emitDartEq(body: 'std::ptr::eq(self, other)');
    }
    _line(
      // The bounds the inherent impl has: `dart_cast` calls the trait
      // impls, whose `E: Clone` a bare `'static` cannot meet (ws304).
      'impl${_implGenerics(cls, keyed: false)} DartAny for '
      '${cls.name}${_generics(cls)} {',
    );
    _indent++;
    _line('fn dart_to_string(&self) -> String { ${_dartToStringBody()} }');
    _line(
      'fn dart_eq_any(&self, other: &dyn std::any::Any) -> bool { match other.downcast_ref::<Self>() { Some(o) => self.dart_eq(o), None => false } }',
    );
    _line('fn dart_hash_any(&self) -> i64 { self.dart_hash_code() }');
    _line('fn dart_runtime_type(&self) -> Type {');
    _indent++;
    // A generic class names its arguments, as Dart's `runtimeType` does:
    // `RenderAnnotatedRegion<SystemUiOverlayStyle>` is what the render
    // walk's reference prints, and the bare name was the one node of 708
    // that differed (run773).
    _line(
      cls.typeParameters.isEmpty
          ? 'Type::of("${cls.dartName ?? cls.name}")'
          : 'dart_type_applied("${cls.dartName ?? cls.name}", &['
                '${cls.typeParameters.map((p) => 'dart_type_of::<$p>()').join(', ')}])',
    );
    _indent--;
    _line('}');
    // What this object is (`dart_cast_to`): its own struct, and every
    // trait it has an impl for, each through the handle that impl keeps.
    _line(
      'fn dart_cast(&self, __t: std::any::TypeId) -> Option<std::boxed::Box<dyn std::any::Any>> {',
    );
    _indent++;
    final own = cls.counted
        ? 'self.dart_self_ref().get()'
        : cls.typeParameters.isEmpty && _cloneable(cls)
        ? 'std::rc::Rc::new(self.clone())'
        : null;
    // ..and for the handle type itself (`dart_cast_any`): a type parameter
    // is instantiated with `Rc<ScaffoldState>`, not `ScaffoldState`.
    if (own != null) {
      _line(
        'if __t == std::any::TypeId::of::<Self>() || __t == std::any::TypeId::of::<std::rc::Rc<Self>>() { return Some(std::boxed::Box::new($own)); }',
      );
    }
    // ..and as the `Object` it is, for `dart_boxed`: the one handle, not
    // a box around a handle.
    if (cls.counted) {
      _line(
        'if __t == std::any::TypeId::of::<dyn Object>() || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>() { return Some(std::boxed::Box::new(self.dart_self_ref().get() as std::rc::Rc<dyn Object>)); }',
      );
    } else if (own != null) {
      // A value struct behind a fresh handle: an erased twin's `as T` is
      // `dart_cast_any::<Rc<dyn Object>>()` (`found as T` through
      // `get__erased`, the gentrait fixture).
      _line(
        'if __t == std::any::TypeId::of::<dyn Object>() || __t == std::any::TypeId::of::<std::rc::Rc<dyn Object>>() { return Some(std::boxed::Box::new($own as std::rc::Rc<dyn Object>)); }',
      );
    }
    for (final above in _abstractAncestors(cls)) {
      final arguments = _baseArguments(above);
      if (arguments == null) continue;
      final handle = cls.extraImpls.any((w) => w.name == above.name)
          ? '<Self as ${above.name}$arguments>::dart_self_${snakeRaw(above.name)}(self)'
          : 'self.dart_self_${snakeRaw(above.name)}()';
      _line(
        'if __t == std::any::TypeId::of::<dyn ${above.name}$arguments>() || __t == std::any::TypeId::of::<std::rc::Rc<dyn ${above.name}$arguments>>() { return Some(std::boxed::Box::new($handle)); }',
      );
    }
    for (var i = 0; i < cls.extraImpls.length; i++) {
      final wider = cls.extraImpls[i];
      final arguments = '<${wider.arguments.map((a) => type(a)).join(', ')}>';
      final self = i < cls.extraImplSelf.length ? cls.extraImplSelf[i] : null;
      if (self == null) {
        _line(
          'if __t == std::any::TypeId::of::<dyn ${wider.name}$arguments>() || __t == std::any::TypeId::of::<std::rc::Rc<dyn ${wider.name}$arguments>>() { return Some(std::boxed::Box::new(<Self as ${wider.name}$arguments>::dart_self_${snakeRaw(wider.name)}(self))); }',
        );
        continue;
      }
      // An impl written for one instantiation of this generic class: the
      // object answers only when it *is* that instantiation.
      final me = '${cls.name}<${self.map((a) => type(a)).join(', ')}>';
      _line(
        'if __t == std::any::TypeId::of::<dyn ${wider.name}$arguments>() || __t == std::any::TypeId::of::<std::rc::Rc<dyn ${wider.name}$arguments>>() { if let Some(__me) = (self as &dyn std::any::Any).downcast_ref::<$me>() { return Some(std::boxed::Box::new(<$me as ${wider.name}$arguments>::dart_self_${snakeRaw(wider.name)}(__me))); } }',
      );
    }
    _line('None');
    _indent--;
    _line('}');
    _indent--;
    _line('}');
    _emitOperators();
    _emitBaseImpl();
    _emitLazyStatics();
    return _out.join('\n') + '\n';
  }

  /// `impl Base for This`, when this class extends an abstract one.
  ///
  /// The methods **delegate** to the inherent ones rather than repeating their
  /// bodies, and the reason is a real difference between the two languages:
  /// Dart allows a covariant return, so `Alignment operator -()` legally
  /// overrides one declared to return `AlignmentGeometry`. Rust requires the
  /// impl to return exactly what the trait declared. Emitting the body twice
  /// would mean emitting it at two different return types.
  ///
  /// Delegating keeps one body and one idiomatic surface: `Alignment` still has
  /// its `impl Neg` returning an `Alignment`, which is what a Rust caller wants,
  /// and the trait method boxes that up for callers who only know the base.
  /// The prelude's traits for `dart:core` interfaces, with the methods each
  /// asks for: the impl forwards to the class's own.
  static const _preludeInterfaces = {
    'Comparable': [
      'compare_to(&self, other: __A0) -> i64',
      'compare_to(other)',
    ],
    'DartIterator': [
      'move_next(&self) -> bool',
      'move_next()',
      'current(&self) -> __A0',
      'current()',
    ],
  };

  /// The `dart:core` interfaces the prelude has a trait for that this class
  /// answers -- its own, and those an abstract ancestor listed: a class
  /// `implements CharacterRange` and it is `CharacterRange` that
  /// `implements Iterator<String>` (ws814).
  List<IrType> _preludeInterfacesOf(IrClass of) {
    final out = <String, IrType>{};
    for (final c in [of, ..._abstractAncestors(of)]) {
      for (final i in c.interfaces) {
        if (_preludeInterfaces.containsKey(i.name)) out[i.name] ??= i;
      }
    }
    return out.values.toList();
  }

  /// Whether this class has its own method for one of the forwarding calls
  /// (`compare_to(other)`, `current()`).
  ///
  /// The impl forwards to an *inherent* method. Reached only through a
  /// trait, `self.compare_to(other)` names two candidates and neither wins
  /// (E0034); with another arity -- `moveNext(int count)` against the
  /// prelude's `move_next()` -- it is the wrong method. 6 at ws815.
  String? _forwardingCall(String call) {
    final open = call.indexOf('(');
    final name = call.substring(0, open);
    final inside = call.substring(open + 1, call.length - 1).trim();
    final given = inside.isEmpty
        ? const <String>[]
        : [for (final a in inside.split(',')) a.trim()];
    for (final m in cls.methods) {
      if (m.isStatic || m.isSetter || m.operator != null) continue;
      if (snake(m.name) != name) continue;
      if (m.params.length == given.length) return call;
      // An override that *widens* the interface -- `CharacterRange
      // .moveNext([int count = 1])` where the prelude's `Iterator` says
      // `move_next()` -- is forwarded to with its own defaults, which is
      // what the interface means by the call. Withheld instead, the impl
      // was missing and `current()` was on no `dyn CharacterRange` (4 at
      // ws859; the defaults are what `IrParam.defaultValue` is for).
      if (m.params.length < given.length) continue;
      final extra = m.params.skip(given.length).toList();
      if (extra.any((p) => p.defaultValue == null)) continue;
      return '$name(${[for (final a in given) a, for (final p in extra) expr(p.defaultValue!)].join(', ')})';
    }
    return null;
  }

  void _emitPreludeInterfaces() {
    for (final i in _preludeInterfacesOf(cls)) {
      final methods = _preludeInterfaces[i.name];
      if (methods == null) continue;
      // Every call it would make has to land on a method of this class.
      final calls = <int, String>{};
      var forwards = true;
      for (var k = 1; k < methods.length; k += 2) {
        final call = _forwardingCall(methods[k]);
        if (call == null) {
          forwards = false;
        } else {
          calls[k] = call;
        }
      }
      if (!forwards) continue;
      final args = i.arguments.map((a) => type(a)).toList();
      final generic = args.isEmpty ? '' : '<${args.join(', ')}>';
      _member('impl ${i.name} for ${cls.name}', () {
        _line(
          'impl${_implGenerics(cls)} ${i.name}$generic for '
          '${cls.name}${_generics(cls)} {',
        );
        _indent++;
        for (var k = 0; k + 1 < methods.length; k += 2) {
          final signature = methods[k].replaceAll(
            '__A0',
            args.isEmpty ? 'std::rc::Rc<dyn Object>' : args[0],
          );
          _line('fn $signature {');
          _indent++;
          // The class's own method returns `Result`; the prelude trait's
          // signature is fixed.
          _line('self.${calls[k + 1]}${_resultModel ? '.unwrap()' : ''}');
          _indent--;
          _line('}');
        }
        _indent--;
        _line('}');
        _line('');
      });
    }
  }

  /// The `Future<T>` a class says it *is*, from its own `implements` or an
  /// abstract ancestor's; null when it is not one.
  IrType? _isDartFuture(IrClass of) {
    for (final c in [of, ..._abstractAncestors(of)]) {
      for (final i in c.interfaces) {
        if (i.name == 'Future' && i.arguments.length == 1) return i;
      }
    }
    return null;
  }

  /// The translated class an awaited value is, when that class is a `Future`
  /// of Dart's rather than the prelude's: what the await site calls
  /// `dart_into_future` on.
  IrClass? _awaitedClass(IrExpr operand) {
    final name = operand.rustType?.name;
    if (name == null || name == 'Future' || name == 'FutureOr') return null;
    final owner = library[name] ?? library.elsewhere[name];
    if (owner == null || owner.isAbstract) return null;
    return _isDartFuture(owner) == null ? null : owner;
  }

  /// A class that *implements* `Future<T>` is awaited through its own `then`,
  /// which is what Dart's `await` does with any future.
  ///
  /// `TickerFuture implements Future<void>`, so `await controller.reverse()`
  /// is ordinary Dart -- and `Rc<TickerFuture>` is no Rust future at all
  /// ("`Rc<TickerFuture>` is not a future", E0277; 3 stubs on the animation
  /// path at ws972). The interface cannot become a supertrait, because the
  /// prelude's `Future` is the struct `DartFuture<T>` and not a trait.
  ///
  /// An **inherent** method, not `impl IntoFuture for Rc<Self>`: `Rc` is not
  /// `#[fundamental]`, so that impl is not this crate's to write, and the
  /// awaited value is always a handle. An inherent method auto-derefs
  /// through the handle, which is what the await site calls.
  void _emitAwaitable() {
    final future = _isDartFuture(cls);
    if (future == null || cls.isAbstract) return;
    final arg = future.arguments.single;
    // The reified argument the signature carries; `then` itself does not
    // read it. Spelled as the class calls itself, so it says the same thing
    // a written `.then<T>(..)` would.
    final reified = arg.name == 'void'
        ? 'VoidType'
        : (library[arg.name] ?? library.elsewhere[arg.name])?.dartName ??
              arg.name;
    // Through the class's own `then`, whose callback hands the value
    // straight back: `then` is what Dart's `await` calls, and its result is
    // already the prelude's future.
    // Spelled from the class's *own* `then`, not from a shape assumed here:
    // the reified type arguments are hidden trailing parameters that only
    // exist where the type parameter is kept (`__ty_<i>`), so `then` takes
    // three arguments on `TickerFuture` and two on a class whose `R` no one
    // reifies. Written as three either way, that was "this method takes 2
    // arguments but 3 were supplied" (E0061, the `awaitclass` fixture).
    final then = [
      for (final c in [cls, ..._abstractAncestors(cls)])
        ...c.methods.where((m) => m.name == 'then' && !m.isStatic),
    ].firstOrNull;
    if (then == null || then.params.isEmpty) return;
    final rest = <String>[];
    for (final p in then.params.skip(1)) {
      if (p.type.name == 'Type') {
        rest.add('Type::of("$reified")');
      } else if (p.type.nullable) {
        rest.add('None');
      } else {
        // Some other required parameter: this is not the `then` Dart's
        // `await` calls, and guessing a value for it would be inventing
        // behaviour. Left alone, and the await stays a stub that says so.
        return;
      }
    }
    final turbofish = then.typeParameters.isEmpty ? '' : '::<${type(arg)}>';
    _member('impl ${cls.name} (awaitable)', () {
      _line('impl ${cls.name} {');
      _indent++;
      _line('pub fn dart_into_future(&self) -> DartFuture<${type(arg)}> {');
      _indent++;
      _line(
        'match self.then$turbofish(std::rc::Rc::new('
        '|__v: ${type(arg)}| -> Result<_, std::rc::Rc<dyn Object>> '
        '{ Ok(future_or_value(__v)) })'
        '${rest.isEmpty ? '' : ', ${rest.join(', ')}'}) {',
      );
      _indent++;
      _line('Ok(__f) => __f,');
      // `then` may fail before there is a future; the failure is the
      // future's, as it is for any other failing call in an `async` body.
      _line('Err(__e) => DartFuture::ready(Err(__e)),');
      _indent--;
      _line('}');
      _indent--;
      _line('}');
      _indent--;
      _line('}');
      _line('');
    });
  }

  void _emitBaseImpl() {
    _emitAwaitable();
    _emitPreludeInterfaces();
    // Every abstract **ancestor**, not just a direct abstract base. `Padded`
    // extends the concrete `Square`, which extends the abstract `Shape`; with
    // only the direct base considered, `Padded` implemented nothing and
    // `Shape`'s methods were unreachable from it.
    for (final ancestor in _abstractAncestors(cls)) {
      // Wrapped, like every other member. A `super` call or an `is` inside one
      // delegating method used to travel out of `_emitStruct` and take the
      // class with it -- the same gap round 53 found in the constructors.
      _member(
        'impl ${ancestor.name} for ${cls.name}',
        () => _emitImplFor(ancestor),
      );
    }
    // The wider instantiations the program names (`IrClass.extraImpls`):
    // an impl each, its signatures in the wider terms, forwarding to the
    // class's own methods through the coercion rule.
    for (var i = 0; i < cls.extraImpls.length; i++) {
      final wider = cls.extraImpls[i];
      final base = library[wider.name];
      if (base == null) continue;
      final self = i < cls.extraImplSelf.length ? cls.extraImplSelf[i] : null;
      _member(
        'impl ${wider.name}<${wider.arguments.join(', ')}> for ${cls.name}',
        () => _emitImplFor(
          base,
          passedOverride: wider.arguments,
          selfOverride: self,
        ),
      );
    }
  }

  /// The abstract classes above this one, nearest first.
  ///
  /// Mixins count. `class Panel extends Measured with Scaled` has to implement
  /// `Scaled` for `Scaled`'s methods to be reachable through it, exactly as it
  /// implements an abstract superclass -- a mixin is a base that does not sit
  /// on the `extends` chain, and looking only along that chain found none of
  /// them.
  List<IrClass> _abstractAncestors(IrClass of) {
    final found = <String, IrClass>{};
    // Bases are reached by **name**, and `library[...]` resolves a name against
    // this module and then the rest of the crate -- where two libraries are
    // allowed to declare the same one. `NetworkImage` in `image_provider.dart`
    // is abstract and hands its construction to a `NetworkImage` in
    // `_network_image_io.dart`, which implements it; `BitField` does the same.
    // Under a name lookup the second reaches the first, which is the second,
    // and the walk recursed until the stack ended. `seen` is what stops it --
    // and it earns its keep on plain diamonds too, where an ancestor was
    // re-walked once per path that reached it.
    final seen = <IrClass>{};
    void climb(IrClass? from) {
      if (from == null || !seen.add(from)) return;
      for (final name in [
        from.superclass,
        ...from.mixins.map((m) => m.name),
        // `implements` reaches a base too. Dart promises the members without
        // the bodies, which is what a Rust `impl` is.
        ...from.interfaces.map((i) => i.name),
      ]) {
        // ..in another module too: a trait's ancestors decide which trait
        // declares a member (`_declaringTrait`), and `ModalRoute`'s are
        // `widgets`' when the call is in `material` (run672).
        final above = library[name] ?? library.elsewhere[name];
        if (above == null) continue;
        // A class is not its own ancestor. Had the recursion above not ended
        // the run, this is what the same name collision would have emitted:
        // `impl NetworkImage for NetworkImage`.
        if (identical(above, from) || identical(above, of)) continue;
        if (above.isAbstract) found.putIfAbsent(above.name, () => above);
        climb(above);
      }
    }

    climb(of);
    return found.values.toList();
  }

  /// `<f32>` for `impl ParametricCurve<f32> for _Linear`, or nothing.
  ///
  /// Only the *direct* superclass's arguments are known. For a generic
  /// ancestor further up the chain they would have to be composed through each
  /// step, so that impl is refused rather than emitted with the wrong ones.
  String? _baseArguments(IrClass base) {
    if (base.typeParameters.isEmpty) return '';
    final passed = _baseTypeArguments(base);
    if (passed == null) return null;
    return '<${passed.map((a) => type(a)).join(', ')}>';
  }

  /// What this class passed the base's type parameters, or null when it cannot
  /// be worked out from here.
  List<IrType>? _baseTypeArguments(IrClass base) {
    if (base.typeParameters.isEmpty) return const [];
    return _argumentsThrough(cls, const {}, base, {});
  }

  /// Walk up from `current`, carrying the arguments through each step.
  /// `_Linear extends Curve` and `Curve extends ParametricCurve<double>`, so
  /// reaching ParametricCurve means going through Curve -- and a Curve that
  /// had parameters of its own would need ours substituted into what it
  /// passes on. A mixin or interface is a direct base of whichever class
  /// named it, so its arguments are read off the `with`/`implements` clause
  /// -- and followed through: `_SelectableFragment with Selectable`, where
  /// `Selectable implements SelectionHandler` and that `extends
  /// ValueListenable<SelectionGeometry>` (the impl was refused as "arguments
  /// not known here" while the `Selectable` trait required it, 2 E0277).
  List<IrType>? _argumentsThrough(
    IrClass current,
    Map<String, IrType> bound,
    IrClass base,
    Set<String> seen,
  ) {
    if (!seen.add(current.name)) return null;
    Map<String, IrType> binding(IrClass of, List<IrType> passed) => {
      for (var i = 0; i < passed.length; i++) of.typeParameters[i]: passed[i],
    };
    for (final mixin in [...current.mixins, ...current.interfaces]) {
      // Substituted *inside* the argument, not only when the argument is a
      // bare parameter: `FormFieldState<T> extends State<FormField<T>>`
      // passes `FormField<T>`, and `bound[a.name]` left that `T` standing --
      // 28 `E0747`s reading it as a constant.
      final passed = [
        for (final a in mixin.arguments) _substituteType(a, bound),
      ];
      if (mixin.name == base.name) {
        return passed.length == base.typeParameters.length ? passed : null;
      }
      final via = library[mixin.name];
      if (via == null || passed.length != via.typeParameters.length) continue;
      final found = _argumentsThrough(via, binding(via, passed), base, seen);
      if (found != null) return found;
    }
    final next = library[current.superclass];
    if (next == null) return null;
    final passed = [
      for (final a in current.superclassArguments) _substituteType(a, bound),
    ];
    if (next.name == base.name) {
      return passed.length == base.typeParameters.length ? passed : null;
    }
    if (passed.length != next.typeParameters.length) return null;
    return _argumentsThrough(next, binding(next, passed), base, seen);
  }

  /// Whether a getter's result can fill the trait's accessor: the same
  /// type, or one the coercion rule can put there -- an `Option` around
  /// it, a subclass's handle where the slot is a trait object. A
  /// differing *type argument* is not one of those: Dart's covariance
  /// makes a `WidgetStateProperty<Color>` a `WidgetStateProperty<Color?>`
  /// and Rust's does not, so those 82 keep reading the storage and stay a
  /// debt (run701).
  static bool _fitsAccessor(IrType have, IrType slot) {
    if (sameRust(have, slot)) return true;
    if (have.isFunction != slot.isFunction) return false;
    if (have.arguments.length != slot.arguments.length) return false;
    for (var i = 0; i < have.arguments.length; i++) {
      if (!sameRust(have.arguments[i], slot.arguments[i])) return false;
    }
    return true;
  }

  /// Whether a member's body reads `super.<name>`: then it is the base's
  /// storage, whatever else it does with it, and the base's accessor has
  /// to stay that storage.
  static bool _readsSuper(IrMethod m, String name) {
    final walk = _WalkSelf();
    walk.statement(m.body);
    return walk.superMembers.contains(name);
  }

  /// The trait whose impl block is being printed (`_emitImplFor`).
  String? _implFor;
}
