// The Rust that stands in for the parts of `dart:core` and `dart:typed_data`
// that have no library to be translated from.
//
// Round 44 measured what happens when the dill's own `dart:core` is fed
// through the translator: 6608 errors became 16955, because its members are
// `external` and come out as traits with nothing in them. That measurement
// stands, and says nothing about *writing* them: a translated `Duration` is an
// empty trait, a written one is sixty lines of arithmetic.
//
// Round 66 measured how much has to be written. The translated code calls 882
// distinct `dart:` members 30001 times, and 117 of them cover 90% of the uses.
// Most of the top of that list -- `List.[]`, `double.+`, `num.<` -- the backend
// already emits as Rust operators; what is left is the handful of *types* here.
//
// Every one of these is real. Where Dart's semantics and Rust's differ the
// difference is written down rather than smoothed over, because a stub that
// compiles and lies is worse than a name that is missing.
library;

const rustPrelude = r'''
// Generated by tools/dart2rust. See lib/prelude.dart.
//
// `dart:core` and `dart:typed_data` names with no library of their own to be
// translated from. Hand-written, not translated.
#![allow(dead_code, non_snake_case)]

use std::fmt;

/// Dart's `Object`, as the one thing Rust has for "anything": a trait every
/// type implements. `&dyn Object` then accepts what `Object` accepted.
pub trait Object {}

impl<T: ?Sized> Object for T {}

/// Dart's `Duration`: a signed span counted in whole microseconds.
///
/// Not `std::time::Duration`, which is unsigned and counts nanoseconds.
/// Upstream subtracts durations and checks `isNegative`, so the sign has to
/// survive, and every Dart constructor and getter is in microseconds.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Default, Hash)]
pub struct Duration {
    pub microseconds: i64,
}

impl Duration {
    pub const ZERO: Duration = Duration { microseconds: 0 };

    pub const fn from_microseconds(microseconds: i64) -> Self {
        Duration { microseconds }
    }

    pub const fn from_milliseconds(milliseconds: i64) -> Self {
        Duration { microseconds: milliseconds * 1000 }
    }

    pub const fn from_seconds(seconds: i64) -> Self {
        Duration { microseconds: seconds * 1000000 }
    }

    /// Truncating, like Dart's: `inMilliseconds` of 1500us is 1, not 2.
    pub fn in_microseconds(&self) -> i64 {
        self.microseconds
    }

    pub fn in_milliseconds(&self) -> i64 {
        self.microseconds / 1000
    }

    pub fn in_seconds(&self) -> i64 {
        self.microseconds / 1000000
    }

    pub fn in_minutes(&self) -> i64 {
        self.microseconds / 60000000
    }

    pub fn in_hours(&self) -> i64 {
        self.microseconds / 3600000000
    }

    pub fn in_days(&self) -> i64 {
        self.microseconds / 86400000000
    }

    pub fn is_negative(&self) -> bool {
        self.microseconds < 0
    }

    pub fn abs(&self) -> Duration {
        Duration { microseconds: self.microseconds.abs() }
    }

    pub fn compare_to(&self, other: Duration) -> i64 {
        match self.microseconds.cmp(&other.microseconds) {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        }
    }
}

impl std::ops::Add for Duration {
    type Output = Duration;
    fn add(self, other: Duration) -> Duration {
        Duration { microseconds: self.microseconds + other.microseconds }
    }
}

impl std::ops::Sub for Duration {
    type Output = Duration;
    fn sub(self, other: Duration) -> Duration {
        Duration { microseconds: self.microseconds - other.microseconds }
    }
}

impl std::ops::Neg for Duration {
    type Output = Duration;
    fn neg(self) -> Duration {
        Duration { microseconds: -self.microseconds }
    }
}

impl std::ops::Mul<i64> for Duration {
    type Output = Duration;
    fn mul(self, by: i64) -> Duration {
        Duration { microseconds: self.microseconds * by }
    }
}

impl fmt::Display for Duration {
    /// Dart prints `0:00:01.500000`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let us = self.microseconds.abs();
        if self.microseconds < 0 {
            write!(f, "-")?;
        }
        write!(
            f,
            "{}:{:02}:{:02}.{:06}",
            us / 3600000000,
            (us / 60000000) % 60,
            (us / 1000000) % 60,
            us % 1000000
        )
    }
}

/// Dart's `StringBuffer`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StringBuffer {
    text: String,
}

impl StringBuffer {
    pub fn new() -> Self {
        StringBuffer { text: String::new() }
    }

    pub fn write(&mut self, value: &str) {
        self.text.push_str(value);
    }

    pub fn writeln(&mut self, value: &str) {
        self.text.push_str(value);
        self.text.push('\n');
    }

    pub fn write_char_code(&mut self, code: i64) {
        if let Some(c) = char::from_u32(code as u32) {
            self.text.push(c);
        }
    }

    pub fn clear(&mut self) {
        self.text.clear();
    }

    pub fn length(&self) -> i64 {
        self.text.chars().count() as i64
    }

    pub fn is_empty(&self) -> bool {
        self.text.is_empty()
    }

    pub fn is_not_empty(&self) -> bool {
        !self.text.is_empty()
    }
}

impl fmt::Display for StringBuffer {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}

/// Dart's `Set`, backed by a `Vec`.
///
/// Not `HashSet`: Dart puts `double`s and objects with no `hashCode` of their
/// own into sets, and requiring `Hash + Eq` here would refuse code that is
/// perfectly ordinary in Dart. Membership is therefore linear, which is the
/// right trade for a translation -- correct first, and the sets upstream keeps
/// are small.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Set<T> {
    items: Vec<T>,
}

impl<T: PartialEq + Clone> Set<T> {
    pub fn new() -> Self {
        Set { items: Vec::new() }
    }

    pub fn from(items: Vec<T>) -> Self {
        let mut set = Set::new();
        for item in items {
            set.add(item);
        }
        set
    }

    /// Dart returns whether the value was new.
    pub fn add(&mut self, value: T) -> bool {
        if self.contains(&value) {
            return false;
        }
        self.items.push(value);
        true
    }

    pub fn add_all(&mut self, values: Vec<T>) {
        for value in values {
            self.add(value);
        }
    }

    pub fn contains(&self, value: &T) -> bool {
        self.items.iter().any(|item| item == value)
    }

    pub fn remove(&mut self, value: &T) -> bool {
        match self.items.iter().position(|item| item == value) {
            Some(at) => {
                self.items.remove(at);
                true
            }
            None => false,
        }
    }

    pub fn clear(&mut self) {
        self.items.clear();
    }

    pub fn length(&self) -> i64 {
        self.items.len() as i64
    }

    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    pub fn is_not_empty(&self) -> bool {
        !self.items.is_empty()
    }

    pub fn to_list(&self) -> Vec<T> {
        self.items.clone()
    }

    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.items.iter()
    }

    pub fn union(&self, other: &Set<T>) -> Set<T> {
        let mut out = self.clone();
        out.add_all(other.to_list());
        out
    }

    pub fn intersection(&self, other: &Set<T>) -> Set<T> {
        Set {
            items: self
                .items
                .iter()
                .filter(|item| other.contains(item))
                .cloned()
                .collect(),
        }
    }

    pub fn difference(&self, other: &Set<T>) -> Set<T> {
        Set {
            items: self
                .items
                .iter()
                .filter(|item| !other.contains(item))
                .cloned()
                .collect(),
        }
    }
}

impl<T> IntoIterator for Set<T> {
    type Item = T;
    type IntoIter = std::vec::IntoIter<T>;
    fn into_iter(self) -> Self::IntoIter {
        self.items.into_iter()
    }
}

/// Dart's `StackTrace`.
///
/// Opaque on purpose. Dart's is captured by the runtime at the point a throw
/// happens, and there is no runtime here to capture one; what upstream does
/// with it is print it or pass it along, and both work with a string that says
/// so honestly.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StackTrace {
    text: String,
}

impl StackTrace {
    pub fn empty() -> Self {
        StackTrace { text: String::new() }
    }

    pub fn current() -> Self {
        StackTrace { text: "<no stack trace: translated from Dart>".to_string() }
    }
}

impl fmt::Display for StackTrace {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.text)
    }
}

/// Dart's `Zone`.
///
/// A zone is the async context a callback was registered in, so that running
/// it later runs it under the same error handling. Upstream stores one beside
/// each callback -- `dart:ui` keeps a `_zone` next to every platform handler --
/// and then runs the callback in it.
///
/// There is exactly one zone here, because there is no runtime to make a
/// second: `Zone::CURRENT` is it, and `run` calls the callback directly. That
/// is what the root zone does in Dart too. A program that installs a zone of
/// its own to catch errors would not get that behaviour, and this is where to
/// look when it does not.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Zone;

impl Zone {
    pub const CURRENT: Zone = Zone;

    pub fn run<T>(&self, body: impl FnOnce() -> T) -> T {
        body()
    }

    pub fn run_unary<A, T>(&self, body: impl FnOnce(A) -> T, argument: A) -> T {
        body(argument)
    }

    pub fn register_callback<T>(&self, body: impl Fn() -> T) -> impl Fn() -> T {
        body
    }
}

/// Dart's error and exception classes.
///
/// One shape for all of them: a message, and a `Display` that prints what Dart
/// prints. They are thrown and caught by *type* upstream, and the `Result<T,
/// E>` the backend emits carries the type, so nothing else about them is
/// reached.
macro_rules! dart_error {
    ($name:ident, $prefix:literal) => {
        #[derive(Clone, Debug, Default, PartialEq, Eq)]
        pub struct $name {
            pub message: String,
        }

        impl $name {
            pub fn new(message: String) -> Self {
                $name { message }
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                if self.message.is_empty() {
                    f.write_str($prefix)
                } else {
                    write!(f, "{}: {}", $prefix, self.message)
                }
            }
        }
    };
}

dart_error!(StateError, "Bad state");
dart_error!(ArgumentError, "Invalid argument(s)");
dart_error!(UnsupportedError, "Unsupported operation");
dart_error!(UnimplementedError, "UnimplementedError");
dart_error!(FormatException, "FormatException");
dart_error!(AssertionError, "Assertion failed");
dart_error!(ConcurrentModificationError, "Concurrent modification");

/// `RangeError`, which carries the bounds it was given.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct RangeError {
    pub message: String,
    pub start: Option<f64>,
    pub end: Option<f64>,
}

impl RangeError {
    pub fn new(message: String) -> Self {
        RangeError { message, start: None, end: None }
    }

    pub fn range(invalid: f64, min: f64, max: f64) -> Self {
        RangeError {
            message: format!("Invalid value: not in range {}..{}: {}", min, max, invalid),
            start: Some(min),
            end: Some(max),
        }
    }
}

impl fmt::Display for RangeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RangeError: {}", self.message)
    }
}

/// `dart:typed_data`'s fixed-element lists.
///
/// Aliases rather than wrappers: a Dart typed list *is* a list of that element
/// type as far as everything upstream does with it, and an alias keeps every
/// `List` operation the backend already emits working on it.
pub type Uint8List = Vec<u8>;
pub type Int8List = Vec<i8>;
pub type Uint16List = Vec<u16>;
pub type Int16List = Vec<i16>;
pub type Uint32List = Vec<u32>;
pub type Int32List = Vec<i32>;
pub type Uint64List = Vec<u64>;
pub type Int64List = Vec<i64>;
pub type Float32List = Vec<f32>;
pub type Float64List = Vec<f64>;

/// Dart's `ByteData`: a view over bytes with typed accessors.
///
/// Little-endian by default, which is what `Endian.host` is on every platform
/// Flutter ships to. Dart's accessors take an optional `Endian`; the ones that
/// pass one explicitly are not translated yet and will say so rather than
/// silently reading the other way round.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ByteData {
    bytes: Vec<u8>,
}

impl ByteData {
    pub fn new(length: i64) -> Self {
        ByteData { bytes: vec![0; length.max(0) as usize] }
    }

    pub fn view(bytes: Vec<u8>) -> Self {
        ByteData { bytes }
    }

    pub fn length_in_bytes(&self) -> i64 {
        self.bytes.len() as i64
    }

    pub fn buffer(&self) -> Vec<u8> {
        self.bytes.clone()
    }

    pub fn get_uint8(&self, at: i64) -> i64 {
        self.bytes[at as usize] as i64
    }

    pub fn set_uint8(&mut self, at: i64, value: i64) {
        self.bytes[at as usize] = value as u8;
    }

    pub fn get_int8(&self, at: i64) -> i64 {
        self.bytes[at as usize] as i8 as i64
    }

    pub fn set_int8(&mut self, at: i64, value: i64) {
        self.bytes[at as usize] = value as i8 as u8;
    }

    pub fn get_uint16(&self, at: i64) -> i64 {
        u16::from_le_bytes(self.four(at, 2)[..2].try_into().unwrap()) as i64
    }

    pub fn get_int32(&self, at: i64) -> i64 {
        i32::from_le_bytes(self.four(at, 4)[..4].try_into().unwrap()) as i64
    }

    pub fn set_int32(&mut self, at: i64, value: i64) {
        let at = at as usize;
        self.bytes[at..at + 4].copy_from_slice(&(value as i32).to_le_bytes());
    }

    pub fn get_uint32(&self, at: i64) -> i64 {
        u32::from_le_bytes(self.four(at, 4)[..4].try_into().unwrap()) as i64
    }

    pub fn set_uint32(&mut self, at: i64, value: i64) {
        let at = at as usize;
        self.bytes[at..at + 4].copy_from_slice(&(value as u32).to_le_bytes());
    }

    pub fn get_float32(&self, at: i64) -> f32 {
        f32::from_le_bytes(self.four(at, 4)[..4].try_into().unwrap())
    }

    pub fn set_float32(&mut self, at: i64, value: f32) {
        let at = at as usize;
        self.bytes[at..at + 4].copy_from_slice(&value.to_le_bytes());
    }

    pub fn get_float64(&self, at: i64) -> f64 {
        f64::from_le_bytes(self.eight(at)[..8].try_into().unwrap())
    }

    pub fn set_float64(&mut self, at: i64, value: f64) {
        let at = at as usize;
        self.bytes[at..at + 8].copy_from_slice(&value.to_le_bytes());
    }

    fn four(&self, at: i64, n: usize) -> [u8; 4] {
        let at = at as usize;
        let mut out = [0u8; 4];
        out[..n].copy_from_slice(&self.bytes[at..at + n]);
        out
    }

    fn eight(&self, at: i64) -> [u8; 8] {
        let at = at as usize;
        let mut out = [0u8; 8];
        out.copy_from_slice(&self.bytes[at..at + 8]);
        out
    }
}
''';
